// frontend/src/lib/xray/forms/transport/FinalMaskForm.tsx
import { Button, Divider, Form, Input, InputNumber, Select, Space, Switch } from 'antd';
import { DeleteOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons';
import type { FormInstance } from 'antd/es/form';
import type { NamePath } from 'antd/es/form/interface';

import { RandomUtil } from '@/utils';
import { OutboundProtocols } from '@/schemas/primitives';

export interface FinalMaskFormProps {
  name: NamePath;
  network: string;
  protocol: string;
  form: FormInstance;
  // When true, all sections (TCP / UDP / QUIC) are shown regardless of
  // network/protocol. Used by the global sub-JSON finalmask editor where
  // the masks apply to every stream rather than one specific transport.
  showAll?: boolean;
}

const TCP_NETWORKS = ['raw', 'tcp', 'httpupgrade', 'ws', 'grpc', 'xhttp'];

function asPath(name: NamePath): (string | number)[] {
  return Array.isArray(name) ? [...name] : [name];
}

function defaultTcpMaskSettings(type: string): Record<string, unknown> {
  switch (type) {
    case 'fragment':
      return { packets: '1-3', length: '', delay: '', maxSplit: '' };
    case 'sudoku':
      return {
        password: '', ascii: '', customTable: '', customTables: [''],
        paddingMin: 0, paddingMax: 0,
      };
    case 'header-custom':
      return { clients: [], servers: [] };
    default:
      return {};
  }
}

function defaultUdpMaskSettings(type: string): Record<string, unknown> {
  switch (type) {
    case 'salamander':
      return { password: '' };
    case 'mkcp-legacy':
      return { header: '', value: '' };
    case 'xdns':
      return { domains: [] };
    case 'xicmp':
      return { dgram: false, ips: [] };
    case 'realm':
      return { url: '', stunServers: [] };
    case 'header-custom':
      return { client: [], server: [] };
    case 'noise':
      return { reset: 0, noise: [] };
    default:
      return {};
  }
}

function defaultClientServerItem(): Record<string, unknown> {
  return { delay: 0, rand: 0, randRange: '0-255', type: 'array', packet: [] };
}

function defaultUdpClientServerItem(): Record<string, unknown> {
  return { rand: 0, randRange: '0-255', type: 'array', packet: [] };
}

function defaultNoiseItem(): Record<string, unknown> {
  return {
    rand: '1-8192', randRange: '0-255', type: 'array', packet: [], delay: '10-20',
  };
}

function defaultQuicParams(): Record<string, unknown> {
  return {
    congestion: 'bbr',
    debug: false,
    maxIdleTimeout: 30,
    keepAlivePeriod: 10,
    disablePathMTUDiscovery: false,
    maxIncomingStreams: 1024,
    initStreamReceiveWindow: 8388608,
    maxStreamReceiveWindow: 8388608,
    initConnectionReceiveWindow: 20971520,
    maxConnectionReceiveWindow: 20971520,
  };
}

function defaultUdpHop(): Record<string, unknown> {
  return { ports: '20000-50000', interval: '5-10' };
}

export default function FinalMaskForm({ name, network, protocol, form, showAll = false }: FinalMaskFormProps) {
  const base = asPath(name);
  const isHysteria = protocol === OutboundProtocols.Hysteria || protocol === 'hysteria';
  const showTcp = showAll || TCP_NETWORKS.includes(network);
  const showUdp = showAll || isHysteria || network === 'kcp';
  const showQuic = showAll || isHysteria || network === 'xhttp';
  const quicParams = Form.useWatch([...base, 'quicParams'], { form, preserve: true });
  const hasQuicParams = quicParams != null;

  if (!showTcp && !showUdp && !showQuic) return null;

  return (
    <>
      {showTcp && <TcpMasksList base={base} form={form} />}
      {showUdp && <UdpMasksList base={base} form={form} isHysteria={isHysteria} network={network} />}
      {showQuic && (
        <>
          <Form.Item label="QUIC Params">
            <Switch
              checked={hasQuicParams}
              onChange={(v) => {
                form.setFieldValue([...base, 'quicParams'], v ? defaultQuicParams() : undefined);
              }}
            />
          </Form.Item>
          {hasQuicParams && <QuicParamsForm base={[...base, 'quicParams']} form={form} />}
        </>
      )}
    </>
  );
}

function TcpMasksList({ base, form }: { base: (string | number)[]; form: FormInstance }) {
  return (
    <Form.List name={[...base, 'tcp']}>
      {(fields, { add, remove }) => (
        <>
          <Form.Item label="TCP Masks">
            <Button
              type="primary"
              size="small"
              icon={<PlusOutlined />}
              onClick={() => add({ type: 'fragment', settings: defaultTcpMaskSettings('fragment') })}
            />
          </Form.Item>
          {fields.map((field, mIdx) => (
            <TcpMaskItem
              key={field.key}
              fieldName={field.name}
              displayIndex={mIdx + 1}
              form={form}
              listPath={[...base, 'tcp']}
              onRemove={() => remove(field.name)}
            />
          ))}
        </>
      )}
    </Form.List>
  );
}

function TcpMaskItem({
  fieldName, displayIndex, form, listPath, onRemove,
}: {
  fieldName: number;
  displayIndex: number;
  form: FormInstance;
  listPath: (string | number)[];
  onRemove: () => void;
}) {
  // Absolute path for setFieldValue side effects (resetting settings on
  // type change). All Form.Item `name=` use RELATIVE paths within the
  // outer Form.List context.
  const absolutePath = [...listPath, fieldName];

  return (
    <div>
      <Divider style={{ margin: 0 }}>
        TCP Mask {displayIndex}
        <DeleteOutlined className="danger-icon" onClick={onRemove} />
      </Divider>

      <Form.Item label="Type" name={[fieldName, 'type']}>
        <Select
          onChange={(v) =>
            form.setFieldValue([...absolutePath, 'settings'], defaultTcpMaskSettings(v))
          }
          options={[
            { value: 'fragment', label: 'Fragment' },
            { value: 'header-custom', label: 'Header Custom' },
            { value: 'sudoku', label: 'Sudoku' },
          ]}
        />
      </Form.Item>

      <Form.Item
        noStyle
        shouldUpdate={(prev, curr) => {
          const a = getDeep(prev, [...absolutePath, 'type']);
          const b = getDeep(curr, [...absolutePath, 'type']);
          return a !== b;
        }}
      >
        {({ getFieldValue }) => {
          const type = getFieldValue([...absolutePath, 'type']) as string | undefined;
          if (type === 'fragment') {
            return (
              <>
                <Form.Item label="Packets" name={[fieldName, 'settings', 'packets']}>
                  <Select
                    options={[
                      { value: 'tlshello', label: 'tlshello' },
                      { value: '1-3', label: '1-3' },
                      { value: '1-5', label: '1-5' },
                    ]}
                  />
                </Form.Item>
                <Form.Item label="Length" name={[fieldName, 'settings', 'length']}>
                  <Input />
                </Form.Item>
                <Form.Item label="Delay" name={[fieldName, 'settings', 'delay']}>
                  <Input />
                </Form.Item>
                <Form.Item label="Max Split" name={[fieldName, 'settings', 'maxSplit']}>
                  <Input />
                </Form.Item>
              </>
            );
          }
          if (type === 'sudoku') {
            return (
              <>
                <Form.Item label="Password" name={[fieldName, 'settings', 'password']}><Input /></Form.Item>
                <Form.Item label="ASCII" name={[fieldName, 'settings', 'ascii']}><Input /></Form.Item>
                <Form.Item label="Custom Table" name={[fieldName, 'settings', 'customTable']}><Input /></Form.Item>
                <Form.Item label="Custom Tables" name={[fieldName, 'settings', 'customTables']}>
                  <Select mode="tags" style={{ width: '100%' }} tokenSeparators={[',']} />
                </Form.Item>
                <Form.Item label="Padding Min" name={[fieldName, 'settings', 'paddingMin']}>
                  <InputNumber min={0} />
                </Form.Item>
                <Form.Item label="Padding Max" name={[fieldName, 'settings', 'paddingMax']}>
                  <InputNumber min={0} />
                </Form.Item>
              </>
            );
          }
          if (type === 'header-custom') {
            return (
              <HeaderCustomGroups
                tcpFieldName={fieldName}
                form={form}
                absoluteSettingsPath={[...absolutePath, 'settings']}
              />
            );
          }
          return null;
        }}
      </Form.Item>
    </div>
  );
}

// Walks a deep object path safely. Used inside shouldUpdate which gets
// the whole form values blob; we need to compare a deep field across
// prev/curr without crashing on missing intermediates.
function getDeep(obj: unknown, path: (string | number)[]): unknown {
  let cur: unknown = obj;
  for (const key of path) {
    if (cur == null || typeof cur !== 'object') return undefined;
    cur = (cur as Record<string | number, unknown>)[key];
  }
  return cur;
}

function HeaderCustomGroups({
  tcpFieldName, form, absoluteSettingsPath,
}: {
  tcpFieldName: number;
  form: FormInstance;
  absoluteSettingsPath: (string | number)[];
}) {
  return (
    <>
      {(['clients', 'servers'] as const).map((groupKey) => (
        <Form.List key={groupKey} name={[tcpFieldName, 'settings', groupKey]}>
          {(groups, { add: addGroup, remove: removeGroup }) => (
            <>
              <Form.Item label={groupKey === 'clients' ? 'Clients' : 'Servers'}>
                <Button
                  type="primary"
                  size="small"
                  icon={<PlusOutlined />}
                  onClick={() => addGroup([defaultClientServerItem()])}
                />
              </Form.Item>
              {groups.map((group, gi) => (
                <div key={group.key}>
                  <Divider style={{ margin: 0 }}>
                    {groupKey === 'clients' ? 'Clients' : 'Servers'} Group {gi + 1}
                    <DeleteOutlined className="danger-icon" onClick={() => removeGroup(group.name)} />
                  </Divider>
                  <Form.List name={[group.name]}>
                    {(items, { add: addItem, remove: removeItem }) => (
                      <>
                        <Form.Item label="Items">
                          <Button
                            size="small"
                            icon={<PlusOutlined />}
                            onClick={() => addItem(defaultClientServerItem())}
                          />
                        </Form.Item>
                        {items.map((item) => (
                          <ItemEditor
                            key={item.key}
                            fieldName={item.name}
                            form={form}
                            absoluteItemPath={[...absoluteSettingsPath, groupKey, group.name, item.name]}
                            delayMode="number"
                            onRemove={() => removeItem(item.name)}
                          />
                        ))}
                      </>
                    )}
                  </Form.List>
                </div>
              ))}
            </>
          )}
        </Form.List>
      ))}
    </>
  );
}

function UdpMasksList({
  base, form, isHysteria, network,
}: { base: (string | number)[]; form: FormInstance; isHysteria: boolean; network: string }) {
  return (
    <Form.List name={[...base, 'udp']}>
      {(fields, { add, remove }) => (
        <>
          <Form.Item label="UDP Masks">
            <Button
              type="primary"
              size="small"
              icon={<PlusOutlined />}
              onClick={() => {
                const def = isHysteria ? 'salamander' : 'mkcp-legacy';
                add({ type: def, settings: defaultUdpMaskSettings(def) });
              }}
            />
          </Form.Item>
          {fields.map((field, mIdx) => (
            <UdpMaskItem
              key={field.key}
              fieldName={field.name}
              displayIndex={mIdx + 1}
              form={form}
              listPath={[...base, 'udp']}
              isHysteria={isHysteria}
              network={network}
              onRemove={() => remove(field.name)}
            />
          ))}
        </>
      )}
    </Form.List>
  );
}

function UdpMaskItem({
  fieldName, displayIndex, form, listPath, isHysteria, network, onRemove,
}: {
  fieldName: number;
  displayIndex: number;
  form: FormInstance;
  listPath: (string | number)[];
  isHysteria: boolean;
  network: string;
  onRemove: () => void;
}) {
  const absolutePath = [...listPath, fieldName];

  const onTypeChange = (v: string) => {
    form.setFieldValue([...absolutePath, 'settings'], defaultUdpMaskSettings(v));
    if (network === 'kcp') {
      const kcpMtuPath = [...listPath.slice(0, -1), 'kcpSettings', 'mtu'];
      form.setFieldValue(kcpMtuPath, v === 'xdns' ? 900 : 1350);
    }
  };

  const options = isHysteria
    ? [{ value: 'salamander', label: 'Salamander (Hysteria2)' }]
    : [
      { value: 'mkcp-legacy', label: 'mKCP Legacy' },
      { value: 'xdns', label: 'xDNS' },
      { value: 'xicmp', label: 'xICMP' },
      { value: 'realm', label: 'Realm' },
      { value: 'header-custom', label: 'Header Custom' },
      { value: 'noise', label: 'Noise' },
    ];

  return (
    <div>
      <Divider style={{ margin: 0 }}>
        UDP Mask {displayIndex}
        <DeleteOutlined className="danger-icon" onClick={onRemove} />
      </Divider>

      <Form.Item label="Type" name={[fieldName, 'type']}>
        <Select onChange={onTypeChange} options={options} />
      </Form.Item>

      <Form.Item
        noStyle
        shouldUpdate={(prev, curr) => getDeep(prev, [...absolutePath, 'type']) !== getDeep(curr, [...absolutePath, 'type'])}
      >
        {({ getFieldValue }) => {
          const type = getFieldValue([...absolutePath, 'type']) as string | undefined;
          if (type === 'salamander') {
            return (
              <Form.Item label="Password">
                <Space.Compact block>
                  <Form.Item name={[fieldName, 'settings', 'password']} noStyle>
                    <Input placeholder="Obfuscation password" style={{ width: 'calc(100% - 32px)' }} />
                  </Form.Item>
                  <Button
                    icon={<ReloadOutlined />}
                    onClick={() => form.setFieldValue(
                      [...absolutePath, 'settings', 'password'],
                      RandomUtil.randomLowerAndNum(16),
                    )}
                  />
                </Space.Compact>
              </Form.Item>
            );
          }
          if (type === 'mkcp-legacy') {
            return (
              <>
                <Form.Item label="Header" name={[fieldName, 'settings', 'header']}>
                  <Select
                    options={[
                      { value: '', label: 'Original / AES-128-GCM' },
                      { value: 'dns', label: 'DNS' },
                      { value: 'dtls', label: 'DTLS 1.2' },
                      { value: 'srtp', label: 'SRTP' },
                      { value: 'utp', label: 'uTP' },
                      { value: 'wechat', label: 'WeChat Video' },
                      { value: 'wireguard', label: 'WireGuard' },
                    ]}
                  />
                </Form.Item>
                <Form.Item label="Value" name={[fieldName, 'settings', 'value']}>
                  <Input placeholder="password (AES-128-GCM) or domain (DNS header)" />
                </Form.Item>
              </>
            );
          }
          if (type === 'xdns') {
            return (
              <Form.Item label="Domains" name={[fieldName, 'settings', 'domains']}>
                <Select mode="tags" style={{ width: '100%' }} tokenSeparators={[',']} />
              </Form.Item>
            );
          }
          if (type === 'xicmp') {
            return (
              <>
                <Form.Item label="Dgram" name={[fieldName, 'settings', 'dgram']} valuePropName="checked">
                  <Switch />
                </Form.Item>
                <Form.Item label="IPs" name={[fieldName, 'settings', 'ips']}>
                  <Select mode="tags" style={{ width: '100%' }} tokenSeparators={[',']} />
                </Form.Item>
              </>
            );
          }
          if (type === 'realm') {
            return (
              <>
                <Form.Item label="URL" name={[fieldName, 'settings', 'url']}>
                  <Input placeholder="realm://token@host:port/id" />
                </Form.Item>
                <Form.Item label="STUN Servers" name={[fieldName, 'settings', 'stunServers']}>
                  <Select mode="tags" style={{ width: '100%' }} tokenSeparators={[',']} placeholder="host:port" />
                </Form.Item>
              </>
            );
          }
          if (type === 'header-custom') {
            return (
              <UdpHeaderCustom
                udpFieldName={fieldName}
                form={form}
                absoluteSettingsPath={[...absolutePath, 'settings']}
              />
            );
          }
          if (type === 'noise') {
            return (
              <NoiseItems
                udpFieldName={fieldName}
                form={form}
                absoluteSettingsPath={[...absolutePath, 'settings']}
              />
            );
          }
          return null;
        }}
      </Form.Item>
    </div>
  );
}

function UdpHeaderCustom({
  udpFieldName, form, absoluteSettingsPath,
}: {
  udpFieldName: number;
  form: FormInstance;
  absoluteSettingsPath: (string | number)[];
}) {
  return (
    <>
      {(['client', 'server'] as const).map((groupKey) => (
        <Form.List key={groupKey} name={[udpFieldName, 'settings', groupKey]}>
          {(items, { add, remove }) => (
            <>
              <Form.Item label={groupKey === 'client' ? 'Client' : 'Server'}>
                <Button
                  type="primary"
                  size="small"
                  icon={<PlusOutlined />}
                  onClick={() => add(defaultUdpClientServerItem())}
                />
              </Form.Item>
              {items.map((item, ci) => (
                <div key={item.key}>
                  <Divider style={{ margin: 0 }}>
                    {groupKey === 'client' ? 'Client' : 'Server'} {ci + 1}
                    <DeleteOutlined className="danger-icon" onClick={() => remove(item.name)} />
                  </Divider>
                  <ItemEditor
                    fieldName={item.name}
                    form={form}
                    absoluteItemPath={[...absoluteSettingsPath, groupKey, item.name]}
                    onRemove={() => remove(item.name)}
                  />
                </div>
              ))}
            </>
          )}
        </Form.List>
      ))}
    </>
  );
}

function NoiseItems({
  udpFieldName, form, absoluteSettingsPath,
}: {
  udpFieldName: number;
  form: FormInstance;
  absoluteSettingsPath: (string | number)[];
}) {
  return (
    <>
      <Form.Item label="Reset" name={[udpFieldName, 'settings', 'reset']}>
        <InputNumber min={0} />
      </Form.Item>
      <Form.List name={[udpFieldName, 'settings', 'noise']}>
        {(items, { add, remove }) => (
          <>
            <Form.Item label="Noise">
              <Button
                type="primary"
                size="small"
                icon={<PlusOutlined />}
                onClick={() => add(defaultNoiseItem())}
              />
            </Form.Item>
            {items.map((item, ni) => (
              <div key={item.key}>
                <Divider style={{ margin: 0 }}>
                  Noise {ni + 1}
                  <DeleteOutlined className="danger-icon" onClick={() => remove(item.name)} />
                </Divider>
                <ItemEditor
                  fieldName={item.name}
                  form={form}
                  absoluteItemPath={[...absoluteSettingsPath, 'noise', item.name]}
                  delayMode="string"
                  onRemove={() => remove(item.name)}
                />
              </div>
            ))}
          </>
        )}
      </Form.List>
    </>
  );
}

function ItemEditor({
  fieldName, form, absoluteItemPath, delayMode, onRemove: _onRemove,
}: {
  fieldName: number;
  form: FormInstance;
  absoluteItemPath: (string | number)[];
  delayMode?: 'number' | 'string';
  onRemove?: () => void;
}) {
  const onTypeChange = (v: string) => {
    if (v === 'base64') {
      form.setFieldValue([...absoluteItemPath, 'packet'], RandomUtil.randomBase64());
    } else if (v === 'array') {
      form.setFieldValue([...absoluteItemPath, 'rand'], delayMode === 'string' ? '1-8192' : 0);
      form.setFieldValue([...absoluteItemPath, 'packet'], []);
    } else {
      form.setFieldValue([...absoluteItemPath, 'packet'], '');
    }
  };

  return (
    <>
      <Form.Item label="Type" name={[fieldName, 'type']}>
        <Select
          onChange={onTypeChange}
          options={[
            { value: 'array', label: 'Array' },
            { value: 'str', label: 'String' },
            { value: 'hex', label: 'Hex' },
            { value: 'base64', label: 'Base64' },
          ]}
        />
      </Form.Item>

      {delayMode === 'number' && (
        <Form.Item label="Delay (ms)" name={[fieldName, 'delay']}>
          <InputNumber min={0} />
        </Form.Item>
      )}
      {delayMode === 'string' && (
        <Form.Item label="Delay" name={[fieldName, 'delay']}>
          <Input placeholder="10-20" />
        </Form.Item>
      )}

      <Form.Item
        noStyle
        shouldUpdate={(prev, curr) => getDeep(prev, [...absoluteItemPath, 'type']) !== getDeep(curr, [...absoluteItemPath, 'type'])}
      >
        {({ getFieldValue }) => {
          const type = getFieldValue([...absoluteItemPath, 'type']) as string | undefined;
          if (type === 'array') {
            return (
              <>
                <Form.Item label="Rand" name={[fieldName, 'rand']}>
                  {delayMode === 'string' ? (
                    <Input placeholder="0 or 1-8192" />
                  ) : (
                    <InputNumber min={0} />
                  )}
                </Form.Item>
                <Form.Item label="Rand Range" name={[fieldName, 'randRange']}>
                  <Input placeholder="0-255" />
                </Form.Item>
              </>
            );
          }
          if (type === 'base64') {
            return (
              <Form.Item label="Packet">
                <Space.Compact block>
                  <Form.Item name={[fieldName, 'packet']} noStyle>
                    <Input placeholder="binary data" style={{ width: 'calc(100% - 32px)' }} />
                  </Form.Item>
                  <Button
                    icon={<ReloadOutlined />}
                    onClick={() => form.setFieldValue([...absoluteItemPath, 'packet'], RandomUtil.randomBase64())}
                  />
                </Space.Compact>
              </Form.Item>
            );
          }
          return (
            <Form.Item label="Packet" name={[fieldName, 'packet']}>
              <Input placeholder="binary data" />
            </Form.Item>
          );
        }}
      </Form.Item>
    </>
  );
}

function QuicParamsForm({ base, form }: { base: (string | number)[]; form: FormInstance }) {
  const congestion = Form.useWatch([...base, 'congestion'], form) as string | undefined;
  const udpHop = Form.useWatch([...base, 'udpHop'], { form, preserve: true }) as Record<string, unknown> | undefined;
  const hasUdpHop = udpHop != null;

  return (
    <>
      <Form.Item label="Congestion" name={[...base, 'congestion']}>
        <Select
          options={[
            { value: 'reno', label: 'Reno' },
            { value: 'bbr', label: 'BBR' },
            { value: 'brutal', label: 'Brutal' },
            { value: 'force-brutal', label: 'Force Brutal' },
          ]}
        />
      </Form.Item>
      {congestion === 'bbr' && (
        <Form.Item label="BBR Profile" name={[...base, 'bbrProfile']}>
          <Select
            allowClear
            placeholder="standard"
            options={[
              { value: 'conservative', label: 'Conservative' },
              { value: 'standard', label: 'Standard' },
              { value: 'aggressive', label: 'Aggressive' },
            ]}
          />
        </Form.Item>
      )}
      <Form.Item label="Debug" name={[...base, 'debug']} valuePropName="checked">
        <Switch />
      </Form.Item>

      {(congestion === 'brutal' || congestion === 'force-brutal') && (
        <>
          <Form.Item label="Brutal Up" name={[...base, 'brutalUp']}>
            <Input placeholder="e.g. 60 mbps" />
          </Form.Item>
          <Form.Item label="Brutal Down" name={[...base, 'brutalDown']}>
            <Input placeholder="e.g. 100 mbps" />
          </Form.Item>
        </>
      )}

      <Form.Item label="UDP Hop">
        <Switch
          checked={hasUdpHop}
          onChange={(v) => {
            form.setFieldValue([...base, 'udpHop'], v ? defaultUdpHop() : undefined);
          }}
        />
      </Form.Item>
      {hasUdpHop && (
        <>
          <Form.Item label="Hop Ports" name={[...base, 'udpHop', 'ports']}>
            <Input placeholder="e.g. 20000-50000" />
          </Form.Item>
          <Form.Item label="Hop Interval (s)" name={[...base, 'udpHop', 'interval']}>
            <Input placeholder="e.g. 5-10" />
          </Form.Item>
        </>
      )}

      <Form.Item label="Max Idle Timeout (s)" name={[...base, 'maxIdleTimeout']}>
        <InputNumber min={4} max={120} />
      </Form.Item>
      <Form.Item label="Keep Alive Period (s)" name={[...base, 'keepAlivePeriod']}>
        <InputNumber min={2} max={60} />
      </Form.Item>
      <Form.Item label="Disable Path MTU Dis" name={[...base, 'disablePathMTUDiscovery']} valuePropName="checked">
        <Switch />
      </Form.Item>

      <Form.Item label="Max Incoming Streams" name={[...base, 'maxIncomingStreams']}>
        <InputNumber min={8} placeholder="1024 = default" />
      </Form.Item>
      <Form.Item label="Init Stream Window" name={[...base, 'initStreamReceiveWindow']}>
        <InputNumber min={16384} placeholder="8388608 = default" />
      </Form.Item>
      <Form.Item label="Max Stream Window" name={[...base, 'maxStreamReceiveWindow']}>
        <InputNumber min={16384} placeholder="8388608 = default" />
      </Form.Item>
      <Form.Item label="Init Conn Window" name={[...base, 'initConnectionReceiveWindow']}>
        <InputNumber min={16384} placeholder="20971520 = default" />
      </Form.Item>
      <Form.Item label="Max Conn Window" name={[...base, 'maxConnectionReceiveWindow']}>
        <InputNumber min={16384} placeholder="20971520 = default" />
      </Form.Item>
    </>
  );
}

// frontend/src/components/FinalMaskForm.vue
<script setup>
import { computed } from 'vue';
import { DeleteOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons-vue';
import { RandomUtil } from '@/utils';
import { Protocols } from '@/models/inbound.js';

// Mirrors web/html/form/stream/stream_finalmask.html. Used by both the
// inbound and outbound modals — they share the same StreamSettings
// shape (`stream.finalmask`, `stream.addTcpMask()`, etc.) so a single
// component handles both. The host modal passes its protocol through
// so we know whether to show only the Hysteria-specific UDP types.
const props = defineProps({
  stream: { type: Object, required: true },
  protocol: { type: String, default: '' },
});

const isHysteria = computed(() => props.protocol === Protocols.HYSTERIA);
const network = computed(() => props.stream?.network || '');

const showTcp = computed(() => ['raw', 'tcp', 'httpupgrade', 'ws', 'grpc', 'xhttp'].includes(network.value));
const showUdp = computed(() => isHysteria.value || network.value === 'kcp');
const showQuic = computed(() => isHysteria.value || network.value === 'xhttp');

// Reset the per-row settings shape when the user picks a different
// type — mirrors the legacy `mask._getDefaultSettings(type, {})` call.
function changeMaskType(mask, type) {
  mask.type = type;
  mask.settings = mask._getDefaultSettings(type, {});
}

// Special case from the legacy form: switching a UDP mask to xdns
// shrinks the kcp MTU; everything else needs the default 1350.
function changeUdpMaskType(mask, type) {
  changeMaskType(mask, type);
  if (network.value === 'kcp' && props.stream.kcp) {
    props.stream.kcp.mtu = type === 'xdns' ? 900 : 1350;
  }
}

// header-custom and noise rows share the same per-item shape — the
// type select rewires the packet field. Pulled out so the click
// handlers in the template stay readable.
function changeItemType(item, type) {
  item.type = type;
  if (type === 'base64') item.packet = RandomUtil.randomBase64();
  else if (type === 'array') { item.rand = 0; item.packet = []; }
  else item.packet = '';
}

function addUdpMaskWithDefault() {
  const def = isHysteria.value ? 'salamander' : 'mkcp-aes128gcm';
  props.stream.addUdpMask(def);
}

function newClientServerItem() {
  return { delay: 0, rand: 0, randRange: '0-255', type: 'array', packet: [] };
}

function newUdpClientServerItem() {
  return { rand: 0, randRange: '0-255', type: 'array', packet: [] };
}

function newNoiseItem() {
  return { rand: '1-8192', randRange: '0-255', type: 'array', packet: [], delay: '10-20' };
}
</script>

<template>
  <a-form
    v-if="showTcp || showUdp || showQuic"
    :colon="false"
    :label-col="{ md: { span: 8 } }"
    :wrapper-col="{ md: { span: 14 } }"
  >
    <a-divider :style="{ margin: '5px 0 0' }" />

    <!-- ============================== TCP MASKS ============================== -->
    <template v-if="showTcp">
      <a-form-item label="TCP Masks">
        <a-button type="primary" size="small" @click="stream.addTcpMask('fragment')">
          <template #icon><PlusOutlined /></template>
        </a-button>
      </a-form-item>

      <template v-for="(mask, mIdx) in (stream.finalmask.tcp || [])" :key="`tcp-${mIdx}`">
        <a-divider :style="{ margin: '0' }">
          TCP Mask {{ mIdx + 1 }}
          <DeleteOutlined
            :style="{ color: 'rgb(255, 77, 79)', cursor: 'pointer', marginLeft: '8px' }"
            @click="stream.delTcpMask(mIdx)"
          />
        </a-divider>

        <a-form-item label="Type">
          <a-select :value="mask.type" @change="(t) => changeMaskType(mask, t)">
            <a-select-option value="fragment">Fragment</a-select-option>
            <a-select-option value="header-custom">Header Custom</a-select-option>
            <a-select-option value="sudoku">Sudoku</a-select-option>
          </a-select>
        </a-form-item>

        <!-- Fragment -->
        <template v-if="mask.type === 'fragment'">
          <a-form-item label="Packets">
            <a-select v-model:value="mask.settings.packets">
              <a-select-option value="tlshello">tlshello</a-select-option>
              <a-select-option value="1-3">1-3</a-select-option>
              <a-select-option value="1-5">1-5</a-select-option>
            </a-select>
          </a-form-item>
          <a-form-item label="Length">
            <a-input v-model:value="mask.settings.length" placeholder="e.g. 100-200" />
          </a-form-item>
          <a-form-item label="Delay">
            <a-input v-model:value="mask.settings.delay" placeholder="e.g. 10-20" />
          </a-form-item>
          <a-form-item label="Max Split">
            <a-input v-model:value="mask.settings.maxSplit" placeholder="e.g. 3-6" />
          </a-form-item>
        </template>

        <!-- Sudoku -->
        <template v-if="mask.type === 'sudoku'">
          <a-form-item label="Password">
            <a-input v-model:value="mask.settings.password" placeholder="Obfuscation password" />
          </a-form-item>
          <a-form-item label="ASCII">
            <a-input v-model:value="mask.settings.ascii" placeholder="ASCII" />
          </a-form-item>
          <a-form-item label="Custom Table">
            <a-input v-model:value="mask.settings.customTable" placeholder="Custom Table" />
          </a-form-item>
          <a-form-item label="Custom Tables">
            <a-input v-model:value="mask.settings.customTables" placeholder="Custom Tables" />
          </a-form-item>
          <a-form-item label="Padding Min">
            <a-input-number v-model:value="mask.settings.paddingMin" :min="0" />
          </a-form-item>
          <a-form-item label="Padding Max">
            <a-input-number v-model:value="mask.settings.paddingMax" :min="0" />
          </a-form-item>
        </template>

        <!-- Header Custom — clients/servers as 2D groups -->
        <template v-if="mask.type === 'header-custom'">
          <!-- Clients -->
          <a-form-item label="Clients">
            <a-button type="primary" size="small" @click="mask.settings.clients.push([newClientServerItem()])">
              <template #icon><PlusOutlined /></template>
            </a-button>
          </a-form-item>
          <template v-for="(group, gi) in mask.settings.clients" :key="`tcp-cg-${mIdx}-${gi}`">
            <a-divider :style="{ margin: '0' }">
              Clients Group {{ gi + 1 }}
              <DeleteOutlined
                :style="{ color: 'rgb(255, 77, 79)', cursor: 'pointer', marginLeft: '8px' }"
                @click="mask.settings.clients.splice(gi, 1)"
              />
            </a-divider>
            <template v-for="(item, ii) in group" :key="`tcp-ci-${mIdx}-${gi}-${ii}`">
              <a-form-item label="Type">
                <a-select :value="item.type" @change="(t) => changeItemType(item, t)">
                  <a-select-option value="array">Array</a-select-option>
                  <a-select-option value="str">String</a-select-option>
                  <a-select-option value="hex">Hex</a-select-option>
                  <a-select-option value="base64">Base64</a-select-option>
                </a-select>
              </a-form-item>
              <a-form-item label="Delay (ms)">
                <a-input-number v-model:value="item.delay" :min="0" />
              </a-form-item>
              <template v-if="item.type === 'array'">
                <a-form-item label="Rand">
                  <a-input-number v-model:value="item.rand" :min="0" />
                </a-form-item>
                <a-form-item label="Rand Range">
                  <a-input v-model:value="item.randRange" placeholder="0-255" />
                </a-form-item>
              </template>
              <a-form-item v-else label="Packet">
                <a-input-group v-if="item.type === 'base64'" compact>
                  <a-input
                    v-model:value="item.packet"
                    placeholder="binary data"
                    :style="{ width: 'calc(100% - 32px)' }"
                  />
                  <a-button @click="item.packet = RandomUtil.randomBase64()">
                    <template #icon><ReloadOutlined /></template>
                  </a-button>
                </a-input-group>
                <a-input v-else v-model:value="item.packet" placeholder="binary data" />
              </a-form-item>
            </template>
          </template>

          <!-- Servers -->
          <a-form-item label="Servers">
            <a-button type="primary" size="small" @click="mask.settings.servers.push([newClientServerItem()])">
              <template #icon><PlusOutlined /></template>
            </a-button>
          </a-form-item>
          <template v-for="(group, gi) in mask.settings.servers" :key="`tcp-sg-${mIdx}-${gi}`">
            <a-divider :style="{ margin: '0' }">
              Servers Group {{ gi + 1 }}
              <DeleteOutlined
                :style="{ color: 'rgb(255, 77, 79)', cursor: 'pointer', marginLeft: '8px' }"
                @click="mask.settings.servers.splice(gi, 1)"
              />
            </a-divider>
            <template v-for="(item, ii) in group" :key="`tcp-si-${mIdx}-${gi}-${ii}`">
              <a-form-item label="Type">
                <a-select :value="item.type" @change="(t) => changeItemType(item, t)">
                  <a-select-option value="array">Array</a-select-option>
                  <a-select-option value="str">String</a-select-option>
                  <a-select-option value="hex">Hex</a-select-option>
                  <a-select-option value="base64">Base64</a-select-option>
                </a-select>
              </a-form-item>
              <a-form-item label="Delay (ms)">
                <a-input-number v-model:value="item.delay" :min="0" />
              </a-form-item>
              <template v-if="item.type === 'array'">
                <a-form-item label="Rand">
                  <a-input-number v-model:value="item.rand" :min="0" />
                </a-form-item>
                <a-form-item label="Rand Range">
                  <a-input v-model:value="item.randRange" placeholder="0-255" />
                </a-form-item>
              </template>
              <a-form-item v-else label="Packet">
                <a-input-group v-if="item.type === 'base64'" compact>
                  <a-input
                    v-model:value="item.packet"
                    placeholder="binary data"
                    :style="{ width: 'calc(100% - 32px)' }"
                  />
                  <a-button @click="item.packet = RandomUtil.randomBase64()">
                    <template #icon><ReloadOutlined /></template>
                  </a-button>
                </a-input-group>
                <a-input v-else v-model:value="item.packet" placeholder="binary data" />
              </a-form-item>
            </template>
          </template>
        </template>
      </template>
    </template>

    <!-- ============================== UDP MASKS ============================== -->
    <template v-if="showUdp">
      <a-form-item label="UDP Masks">
        <a-button type="primary" size="small" @click="addUdpMaskWithDefault">
          <template #icon><PlusOutlined /></template>
        </a-button>
      </a-form-item>

      <template v-for="(mask, mIdx) in (stream.finalmask.udp || [])" :key="`udp-${mIdx}`">
        <a-divider :style="{ margin: '0' }">
          UDP Mask {{ mIdx + 1 }}
          <DeleteOutlined
            :style="{ color: 'rgb(255, 77, 79)', cursor: 'pointer', marginLeft: '8px' }"
            @click="stream.delUdpMask(mIdx)"
          />
        </a-divider>

        <a-form-item label="Type">
          <a-select :value="mask.type" @change="(t) => changeUdpMaskType(mask, t)">
            <template v-if="isHysteria">
              <a-select-option value="salamander">Salamander (Hysteria2)</a-select-option>
            </template>
            <template v-else>
              <a-select-option value="mkcp-aes128gcm">mKCP AES-128-GCM</a-select-option>
              <a-select-option value="header-dns">Header DNS</a-select-option>
              <a-select-option value="header-dtls">Header DTLS 1.2</a-select-option>
              <a-select-option value="header-srtp">Header SRTP</a-select-option>
              <a-select-option value="header-utp">Header uTP</a-select-option>
              <a-select-option value="header-wechat">Header WeChat Video</a-select-option>
              <a-select-option value="header-wireguard">Header WireGuard</a-select-option>
              <a-select-option value="mkcp-original">mKCP Original</a-select-option>
              <a-select-option value="xdns">xDNS</a-select-option>
              <a-select-option value="xicmp">xICMP</a-select-option>
              <a-select-option value="header-custom">Header Custom</a-select-option>
              <a-select-option value="noise">Noise</a-select-option>
            </template>
          </a-select>
        </a-form-item>

        <a-form-item v-if="['mkcp-aes128gcm', 'salamander'].includes(mask.type)" label="Password">
          <a-input v-model:value="mask.settings.password" placeholder="Obfuscation password" />
        </a-form-item>
        <a-form-item v-if="mask.type === 'header-dns'" label="Domain">
          <a-input v-model:value="mask.settings.domain" placeholder="e.g., www.example.com" />
        </a-form-item>
        <a-form-item v-if="mask.type === 'xdns'" label="Domains">
          <a-select
            v-model:value="mask.settings.domains"
            mode="tags"
            :style="{ width: '100%' }"
            :token-separators="[',']"
            placeholder="e.g., www.example.com"
          />
        </a-form-item>

        <!-- Noise -->
        <template v-if="mask.type === 'noise'">
          <a-form-item label="Reset">
            <a-input-number v-model:value="mask.settings.reset" :min="0" />
          </a-form-item>
          <a-form-item label="Noise">
            <a-button type="primary" size="small" @click="mask.settings.noise.push(newNoiseItem())">
              <template #icon><PlusOutlined /></template>
            </a-button>
          </a-form-item>
          <template v-for="(n, ni) in mask.settings.noise" :key="`udp-noise-${mIdx}-${ni}`">
            <a-divider :style="{ margin: '0' }">
              Noise {{ ni + 1 }}
              <DeleteOutlined
                :style="{ color: 'rgb(255, 77, 79)', cursor: 'pointer', marginLeft: '8px' }"
                @click="mask.settings.noise.splice(ni, 1)"
              />
            </a-divider>
            <a-form-item label="Type">
              <a-select :value="n.type" @change="(t) => changeItemType(n, t)">
                <a-select-option value="array">Array</a-select-option>
                <a-select-option value="str">String</a-select-option>
                <a-select-option value="hex">Hex</a-select-option>
                <a-select-option value="base64">Base64</a-select-option>
              </a-select>
            </a-form-item>
            <template v-if="n.type === 'array'">
              <a-form-item label="Rand">
                <a-input v-model:value="n.rand" placeholder="0 or 1-8192" />
              </a-form-item>
              <a-form-item label="Rand Range">
                <a-input v-model:value="n.randRange" placeholder="0-255" />
              </a-form-item>
            </template>
            <a-form-item v-else label="Packet">
              <a-input-group v-if="n.type === 'base64'" compact>
                <a-input
                  v-model:value="n.packet"
                  placeholder="binary data"
                  :style="{ width: 'calc(100% - 32px)' }"
                />
                <a-button @click="n.packet = RandomUtil.randomBase64()">
                  <template #icon><ReloadOutlined /></template>
                </a-button>
              </a-input-group>
              <a-input v-else v-model:value="n.packet" placeholder="binary data" />
            </a-form-item>
            <a-form-item label="Delay">
              <a-input v-model:value="n.delay" placeholder="10-20" />
            </a-form-item>
          </template>
        </template>

        <!-- Header Custom (UDP) — flat client/server lists -->
        <template v-if="mask.type === 'header-custom'">
          <a-form-item label="Client">
            <a-button type="primary" size="small" @click="mask.settings.client.push(newUdpClientServerItem())">
              <template #icon><PlusOutlined /></template>
            </a-button>
          </a-form-item>
          <template v-for="(c, ci) in mask.settings.client" :key="`udp-c-${mIdx}-${ci}`">
            <a-divider :style="{ margin: '0' }">
              Client {{ ci + 1 }}
              <DeleteOutlined
                :style="{ color: 'rgb(255, 77, 79)', cursor: 'pointer', marginLeft: '8px' }"
                @click="mask.settings.client.splice(ci, 1)"
              />
            </a-divider>
            <a-form-item label="Type">
              <a-select :value="c.type" @change="(t) => changeItemType(c, t)">
                <a-select-option value="array">Array</a-select-option>
                <a-select-option value="str">String</a-select-option>
                <a-select-option value="hex">Hex</a-select-option>
                <a-select-option value="base64">Base64</a-select-option>
              </a-select>
            </a-form-item>
            <template v-if="c.type === 'array'">
              <a-form-item label="Rand">
                <a-input-number v-model:value="c.rand" />
              </a-form-item>
              <a-form-item label="Rand Range">
                <a-input v-model:value="c.randRange" placeholder="0-255" />
              </a-form-item>
            </template>
            <a-form-item v-else label="Packet">
              <a-input-group v-if="c.type === 'base64'" compact>
                <a-input
                  v-model:value="c.packet"
                  placeholder="binary data"
                  :style="{ width: 'calc(100% - 32px)' }"
                />
                <a-button @click="c.packet = RandomUtil.randomBase64()">
                  <template #icon><ReloadOutlined /></template>
                </a-button>
              </a-input-group>
              <a-input v-else v-model:value="c.packet" placeholder="binary data" />
            </a-form-item>
          </template>

          <a-divider :style="{ margin: '0' }" />
          <a-form-item label="Server">
            <a-button type="primary" size="small" @click="mask.settings.server.push(newUdpClientServerItem())">
              <template #icon><PlusOutlined /></template>
            </a-button>
          </a-form-item>
          <template v-for="(s, si) in mask.settings.server" :key="`udp-s-${mIdx}-${si}`">
            <a-divider :style="{ margin: '0' }">
              Server {{ si + 1 }}
              <DeleteOutlined
                :style="{ color: 'rgb(255, 77, 79)', cursor: 'pointer', marginLeft: '8px' }"
                @click="mask.settings.server.splice(si, 1)"
              />
            </a-divider>
            <a-form-item label="Type">
              <a-select :value="s.type" @change="(t) => changeItemType(s, t)">
                <a-select-option value="array">Array</a-select-option>
                <a-select-option value="str">String</a-select-option>
                <a-select-option value="hex">Hex</a-select-option>
                <a-select-option value="base64">Base64</a-select-option>
              </a-select>
            </a-form-item>
            <template v-if="s.type === 'array'">
              <a-form-item label="Rand">
                <a-input-number v-model:value="s.rand" />
              </a-form-item>
              <a-form-item label="Rand Range">
                <a-input v-model:value="s.randRange" placeholder="0-255" />
              </a-form-item>
            </template>
            <a-form-item v-else label="Packet">
              <a-input-group v-if="s.type === 'base64'" compact>
                <a-input
                  v-model:value="s.packet"
                  placeholder="binary data"
                  :style="{ width: 'calc(100% - 32px)' }"
                />
                <a-button @click="s.packet = RandomUtil.randomBase64()">
                  <template #icon><ReloadOutlined /></template>
                </a-button>
              </a-input-group>
              <a-input v-else v-model:value="s.packet" placeholder="binary data" />
            </a-form-item>
          </template>
        </template>

        <!-- xICMP -->
        <template v-if="mask.type === 'xicmp'">
          <a-form-item label="IP">
            <a-input v-model:value="mask.settings.ip" placeholder="0.0.0.0" />
          </a-form-item>
          <a-form-item label="ID">
            <a-input-number v-model:value="mask.settings.id" :min="0" />
          </a-form-item>
        </template>
      </template>
    </template>

    <!-- ============================== QUIC PARAMS ============================== -->
    <template v-if="showQuic">
      <a-form-item label="QUIC Params">
        <a-switch v-model:checked="stream.finalmask.enableQuicParams" />
      </a-form-item>
      <template v-if="stream.finalmask.enableQuicParams && stream.finalmask.quicParams">
        <a-form-item label="Congestion">
          <a-select v-model:value="stream.finalmask.quicParams.congestion">
            <a-select-option value="reno">Reno</a-select-option>
            <a-select-option value="bbr">BBR</a-select-option>
            <a-select-option value="brutal">Brutal</a-select-option>
            <a-select-option value="force-brutal">Force Brutal</a-select-option>
          </a-select>
        </a-form-item>
        <a-form-item label="Debug">
          <a-switch v-model:checked="stream.finalmask.quicParams.debug" />
        </a-form-item>
        <template v-if="['brutal', 'force-brutal'].includes(stream.finalmask.quicParams.congestion)">
          <a-form-item label="Brutal Up">
            <a-input v-model:value="stream.finalmask.quicParams.brutalUp" placeholder="65537" />
          </a-form-item>
          <a-form-item label="Brutal Down">
            <a-input v-model:value="stream.finalmask.quicParams.brutalDown" placeholder="65537" />
          </a-form-item>
        </template>
        <a-form-item label="UDP Hop">
          <a-switch v-model:checked="stream.finalmask.quicParams.hasUdpHop" />
        </a-form-item>
        <template v-if="stream.finalmask.quicParams.hasUdpHop && stream.finalmask.quicParams.udpHop">
          <a-form-item label="Hop Ports">
            <a-input v-model:value="stream.finalmask.quicParams.udpHop.ports" placeholder="e.g. 20000-50000" />
          </a-form-item>
          <a-form-item label="Hop Interval (s)">
            <a-input-number v-model:value="stream.finalmask.quicParams.udpHop.interval" :min="5" />
          </a-form-item>
        </template>
        <a-form-item label="Max Idle Timeout (s)">
          <a-input-number v-model:value="stream.finalmask.quicParams.maxIdleTimeout" :min="4" :max="120" />
        </a-form-item>
        <a-form-item label="Keep Alive Period (s)">
          <a-input-number v-model:value="stream.finalmask.quicParams.keepAlivePeriod" :min="2" :max="60" />
        </a-form-item>
        <a-form-item label="Disable Path MTU Dis">
          <a-switch v-model:checked="stream.finalmask.quicParams.disablePathMTUDiscovery" />
        </a-form-item>
        <a-form-item label="Max Incoming Streams">
          <a-input-number
            v-model:value="stream.finalmask.quicParams.maxIncomingStreams"
            :min="8"
            placeholder="1024 = default"
          />
        </a-form-item>
        <a-form-item label="Init Stream Window">
          <a-input-number
            v-model:value="stream.finalmask.quicParams.initStreamReceiveWindow"
            :min="16384"
            placeholder="8388608 = default"
          />
        </a-form-item>
        <a-form-item label="Max Stream Window">
          <a-input-number
            v-model:value="stream.finalmask.quicParams.maxStreamReceiveWindow"
            :min="16384"
            placeholder="8388608 = default"
          />
        </a-form-item>
        <a-form-item label="Init Conn Window">
          <a-input-number
            v-model:value="stream.finalmask.quicParams.initConnectionReceiveWindow"
            :min="16384"
            placeholder="20971520 = default"
          />
        </a-form-item>
        <a-form-item label="Max Conn Window">
          <a-input-number
            v-model:value="stream.finalmask.quicParams.maxConnectionReceiveWindow"
            :min="16384"
            placeholder="20971520 = default"
          />
        </a-form-item>
      </template>
    </template>
  </a-form>
</template>
