// frontend/src/components/SettingListItem.tsx
import type { ReactNode } from 'react';
import { Col, List, Row } from 'antd';

interface SettingListItemProps {
  paddings?: 'small' | 'default';
  title?: ReactNode;
  description?: ReactNode;
  children?: ReactNode;
  control?: ReactNode;
}

export default function SettingListItem({
  paddings = 'default',
  title,
  description,
  children,
  control,
}: SettingListItemProps) {
  const padding = paddings === 'small' ? '10px 20px' : '20px';
  return (
    <List.Item style={{ padding }}>
      <Row gutter={[8, 16]} style={{ width: '100%' }}>
        <Col xs={24} lg={12}>
          <List.Item.Meta title={title} description={description} />
        </Col>
        <Col xs={24} lg={12}>
          {control ?? children}
        </Col>
      </Row>
    </List.Item>
  );
}

// frontend/src/components/SettingListItem.vue
<script setup>
import { computed } from 'vue';

const props = defineProps({
  paddings: {
    type: String,
    default: 'default',
    validator: (value) => ['small', 'default'].includes(value),
  },
});

const padding = computed(() =>
  props.paddings === 'small' ? '10px 20px !important' : '20px !important',
);
</script>

<template>
  <a-list-item :style="{ padding }">
    <a-row :gutter="[8, 16]">
      <a-col :lg="24" :xl="12">
        <a-list-item-meta>
          <template #title><slot name="title" /></template>
          <template #description><slot name="description" /></template>
        </a-list-item-meta>
      </a-col>
      <a-col :lg="24" :xl="12">
        <slot name="control" />
      </a-col>
    </a-row>
  </a-list-item>
</template>
