// frontend/src/pages/clients/ClientBulkAddModal.vue
<script setup>
import { computed, reactive, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import dayjs from 'dayjs';
import { SyncOutlined } from '@ant-design/icons-vue';
import { message } from 'ant-design-vue';

import { HttpUtil, RandomUtil, SizeFormatter } from '@/utils';
import DateTimePicker from '@/components/DateTimePicker.vue';
import { TLS_FLOW_CONTROL } from '@/models/inbound.js';

const FLOW_OPTIONS = Object.values(TLS_FLOW_CONTROL);

const { t } = useI18n();

const props = defineProps({
  open: { type: Boolean, default: false },
  inbounds: { type: Array, default: () => [] },
  ipLimitEnable: { type: Boolean, default: false },
});

const emit = defineEmits(['update:open', 'saved']);

const JSON_HEADERS = { headers: { 'Content-Type': 'application/json' } };

const saving = ref(false);
const delayedStart = ref(false);

const form = reactive({
  emailMethod: 0,
  firstNum: 1,
  lastNum: 1,
  emailPrefix: '',
  emailPostfix: '',
  quantity: 1,
  subId: '',
  comment: '',
  flow: '',
  limitIp: 0,
  totalGB: 0,
  expiryTime: 0,
  inboundIds: [],
});

const flowCapableIds = computed(() => {
  const ids = new Set();
  for (const row of props.inbounds || []) {
    if (row?.tlsFlowCapable) ids.add(row.id);
  }
  return ids;
});

const showFlow = computed(() =>
  (form.inboundIds || []).some((id) => flowCapableIds.value.has(id)),
);

watch(showFlow, (next) => {
  if (!next) form.flow = '';
});

const expiryDate = computed({
  get: () => (form.expiryTime > 0 ? dayjs(form.expiryTime) : null),
  set: (next) => { form.expiryTime = next ? next.valueOf() : 0; },
});

const delayedExpireDays = computed({
  get: () => (form.expiryTime < 0 ? form.expiryTime / -86400000 : 0),
  set: (days) => { form.expiryTime = -86400000 * (days || 0); },
});

const MULTI_CLIENT_PROTOCOLS = new Set([
  'shadowsocks', 'vless', 'vmess', 'trojan', 'hysteria', 'hysteria2', 'portfallback',
]);

const inboundOptions = computed(() =>
  (props.inbounds || [])
    .filter((ib) => MULTI_CLIENT_PROTOCOLS.has(ib.protocol))
    .map((ib) => ({
      label: `${ib.remark || `#${ib.id}`} · ${ib.protocol}:${ib.port}`,
      value: ib.id,
    })),
);

watch(() => props.open, (next) => {
  if (!next) return;
  form.emailMethod = 0;
  form.firstNum = 1;
  form.lastNum = 1;
  form.emailPrefix = '';
  form.emailPostfix = '';
  form.quantity = 1;
  form.subId = '';
  form.comment = '';
  form.flow = '';
  form.limitIp = 0;
  form.totalGB = 0;
  form.expiryTime = 0;
  form.inboundIds = [];
  delayedStart.value = false;
});

function close() {
  emit('update:open', false);
}

function buildEmails() {
  const method = form.emailMethod;
  const out = [];
  let start;
  let end;
  if (method > 1) {
    start = form.firstNum;
    end = form.lastNum + 1;
  } else {
    start = 0;
    end = form.quantity;
  }
  const prefix = method > 0 && form.emailPrefix.length > 0 ? form.emailPrefix : '';
  const useNum = method > 1;
  const postfix = method > 2 && form.emailPostfix.length > 0 ? form.emailPostfix : '';
  for (let i = start; i < end; i++) {
    let email = '';
    if (method !== 4) email = RandomUtil.randomLowerAndNum(6);
    email += useNum ? prefix + String(i) + postfix : prefix + postfix;
    out.push(email);
  }
  return out;
}

async function submit() {
  if (!Array.isArray(form.inboundIds) || form.inboundIds.length === 0) {
    message.error(t('pages.clients.selectInbound'));
    return;
  }
  const emails = buildEmails();
  if (emails.length === 0) return;

  saving.value = true;
  let ok = 0;
  let failed = 0;
  try {
    for (const email of emails) {
      const client = {
        email,
        subId: form.subId || RandomUtil.randomLowerAndNum(16),
        id: RandomUtil.randomUUID(),
        password: RandomUtil.randomLowerAndNum(16),
        auth: RandomUtil.randomLowerAndNum(16),
        flow: showFlow.value ? (form.flow || '') : '',
        totalGB: Math.round((form.totalGB || 0) * SizeFormatter.ONE_GB),
        expiryTime: form.expiryTime,
        limitIp: Number(form.limitIp) || 0,
        comment: form.comment,
        enable: true,
      };
      const payload = { client, inboundIds: form.inboundIds };
      const msg = await HttpUtil.post('/panel/api/clients/add', payload, JSON_HEADERS);
      if (msg?.success) ok++;
      else failed++;
    }
    if (failed === 0) {
      message.success(t('pages.clients.toasts.bulkCreated', { count: ok }));
    } else {
      message.warning(t('pages.clients.toasts.bulkCreatedMixed', { ok, failed }));
    }
    emit('saved');
    close();
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <a-modal :open="open" :title="t('pages.clients.bulk')" :ok-text="t('create')" :cancel-text="t('close')"
    :confirm-loading="saving" :mask-closable="false" :width="640" @ok="submit" @cancel="close">
    <a-form :colon="false" :label-col="{ sm: { span: 8 } }" :wrapper-col="{ sm: { span: 14 } }">
      <a-form-item :label="t('pages.clients.attachedInbounds')" required>
        <a-select v-model:value="form.inboundIds" mode="multiple" :options="inboundOptions"
          :placeholder="t('pages.clients.selectInbound')" :show-search="true"
          :filter-option="(input, option) => (option.label || '').toLowerCase().includes(input.toLowerCase())" />
      </a-form-item>

      <a-form-item :label="t('pages.clients.method')">
        <a-select v-model:value="form.emailMethod">
          <a-select-option :value="0">Random</a-select-option>
          <a-select-option :value="1">Random + Prefix</a-select-option>
          <a-select-option :value="2">Random + Prefix + Num</a-select-option>
          <a-select-option :value="3">Random + Prefix + Num + Postfix</a-select-option>
          <a-select-option :value="4">Prefix + Num + Postfix</a-select-option>
        </a-select>
      </a-form-item>

      <a-form-item v-if="form.emailMethod > 1" :label="t('pages.clients.first')">
        <a-input-number v-model:value="form.firstNum" :min="1" />
      </a-form-item>
      <a-form-item v-if="form.emailMethod > 1" :label="t('pages.clients.last')">
        <a-input-number v-model:value="form.lastNum" :min="form.firstNum" />
      </a-form-item>
      <a-form-item v-if="form.emailMethod > 0" :label="t('pages.clients.prefix')">
        <a-input v-model:value="form.emailPrefix" />
      </a-form-item>
      <a-form-item v-if="form.emailMethod > 2" :label="t('pages.clients.postfix')">
        <a-input v-model:value="form.emailPostfix" />
      </a-form-item>
      <a-form-item v-if="form.emailMethod < 2" :label="t('pages.clients.clientCount')">
        <a-input-number v-model:value="form.quantity" :min="1" :max="500" />
      </a-form-item>

      <a-form-item>
        <template #label>
          {{ t('subscription.title') }}
          <SyncOutlined class="random-icon" @click="form.subId = RandomUtil.randomLowerAndNum(16)" />
        </template>
        <a-input v-model:value="form.subId" />
      </a-form-item>

      <a-form-item :label="t('comment')">
        <a-input v-model:value="form.comment" />
      </a-form-item>

      <a-form-item v-if="showFlow" :label="t('pages.clients.flow')">
        <a-select v-model:value="form.flow" :style="{ width: '220px' }">
          <a-select-option value="">{{ t('none') }}</a-select-option>
          <a-select-option v-for="k in FLOW_OPTIONS" :key="k" :value="k">{{ k }}</a-select-option>
        </a-select>
      </a-form-item>

      <a-form-item v-if="ipLimitEnable" :label="t('pages.clients.limitIp')">
        <a-input-number v-model:value="form.limitIp" :min="0" />
      </a-form-item>

      <a-form-item :label="t('pages.clients.totalGB')">
        <a-input-number v-model:value="form.totalGB" :min="0" :step="0.1" />
      </a-form-item>

      <a-form-item :label="t('pages.clients.delayedStart')">
        <a-switch v-model:checked="delayedStart" @click="form.expiryTime = 0" />
      </a-form-item>

      <a-form-item v-if="delayedStart" :label="t('pages.clients.expireDays')">
        <a-input-number v-model:value="delayedExpireDays" :min="0" />
      </a-form-item>

      <a-form-item v-else :label="t('pages.inbounds.expireDate')">
        <DateTimePicker v-model:value="expiryDate" />
      </a-form-item>
    </a-form>
  </a-modal>
</template>

<style scoped>
.random-icon {
  margin-left: 4px;
  cursor: pointer;
  color: var(--ant-color-primary, #1677ff);
}
</style>

// frontend/src/pages/clients/ClientBulkAddModal.tsx
import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Button, Form, Input, InputNumber, Modal, Select, Space, Switch, message } from 'antd';
import { ReloadOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import type { Dayjs } from 'dayjs';

import { RandomUtil, SizeFormatter } from '@/utils';
import { TLS_FLOW_CONTROL } from '@/schemas/primitives';
import DateTimePicker from '@/components/DateTimePicker';
import { useClients, type InboundOption } from '@/hooks/useClients';
import { ClientBulkAddFormSchema, type ClientBulkAddFormValues } from '@/schemas/client';

const FLOW_OPTIONS = Object.values(TLS_FLOW_CONTROL);

const MULTI_CLIENT_PROTOCOLS = new Set([
  'shadowsocks', 'vless', 'vmess', 'trojan', 'hysteria',
]);

interface ClientBulkAddModalProps {
  open: boolean;
  inbounds: InboundOption[];
  ipLimitEnable?: boolean;
  onOpenChange: (open: boolean) => void;
  onSaved?: () => void;
}

type FormState = ClientBulkAddFormValues;

function emptyForm(): FormState {
  return {
    emailMethod: 0,
    firstNum: 1,
    lastNum: 1,
    emailPrefix: '',
    emailPostfix: '',
    quantity: 1,
    subId: '',
    comment: '',
    flow: '',
    limitIp: 0,
    totalGB: 0,
    expiryTime: 0,
    reset: 0,
    inboundIds: [],
  };
}

export default function ClientBulkAddModal({
  open,
  inbounds,
  ipLimitEnable = false,
  onOpenChange,
  onSaved,
}: ClientBulkAddModalProps) {
  const { t } = useTranslation();
  const [messageApi, messageContextHolder] = message.useMessage();
  const { bulkCreate } = useClients();

  const [form, setForm] = useState<FormState>(emptyForm);
  const [delayedStart, setDelayedStart] = useState(false);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (!open) return;

    setForm(emptyForm());
    setDelayedStart(false);

  }, [open]);

  function update<K extends keyof FormState>(key: K, value: FormState[K]) {
    setForm((prev) => ({ ...prev, [key]: value }));
  }

  const flowCapableIds = useMemo(() => {
    const ids = new Set<number>();
    for (const row of inbounds || []) {
      if (row?.tlsFlowCapable) ids.add(row.id);
    }
    return ids;
  }, [inbounds]);

  const showFlow = useMemo(
    () => (form.inboundIds || []).some((id) => flowCapableIds.has(id)),
    [form.inboundIds, flowCapableIds],
  );

  useEffect(() => {
    if (!showFlow && form.flow) {

      update('flow', '');
    }
  }, [showFlow, form.flow]);

  const inboundOptions = useMemo(
    () => (inbounds || [])
      .filter((ib) => MULTI_CLIENT_PROTOCOLS.has(ib.protocol || ''))
      .map((ib) => ({
        label: `${ib.remark || `#${ib.id}`} · ${ib.protocol}:${ib.port}`,
        value: ib.id,
      })),
    [inbounds],
  );

  const expiryDate = useMemo<Dayjs | null>(
    () => (form.expiryTime > 0 ? dayjs(form.expiryTime) : null),
    [form.expiryTime],
  );

  const delayedExpireDays = form.expiryTime < 0 ? form.expiryTime / -86400000 : 0;

  function buildEmails(): string[] {
    const method = form.emailMethod;
    const out: string[] = [];
    let start: number;
    let end: number;
    if (method > 1) {
      start = form.firstNum;
      end = form.lastNum + 1;
    } else {
      start = 0;
      end = form.quantity;
    }
    const prefix = method > 0 && form.emailPrefix.length > 0 ? form.emailPrefix : '';
    const useNum = method > 1;
    const postfix = method > 2 && form.emailPostfix.length > 0 ? form.emailPostfix : '';
    for (let i = start; i < end; i++) {
      let email = '';
      if (method !== 4) email = RandomUtil.randomLowerAndNum(6);
      email += useNum ? prefix + String(i) + postfix : prefix + postfix;
      out.push(email);
    }
    return out;
  }

  async function submit() {
    const validated = ClientBulkAddFormSchema.safeParse(form);
    if (!validated.success) {
      messageApi.error(t(validated.error.issues[0]?.message ?? 'somethingWentWrong'));
      return;
    }
    const emails = buildEmails();
    if (emails.length === 0) return;

    setSaving(true);
    try {
      const payloads = emails.map((email) => ({
        client: {
          email,
          subId: form.subId || RandomUtil.randomLowerAndNum(16),
          id: RandomUtil.randomUUID(),
          password: RandomUtil.randomLowerAndNum(16),
          auth: RandomUtil.randomLowerAndNum(16),
          flow: showFlow ? (form.flow || '') : '',
          totalGB: Math.round((form.totalGB || 0) * SizeFormatter.ONE_GB),
          expiryTime: form.expiryTime,
          reset: Number(form.reset) || 0,
          limitIp: Number(form.limitIp) || 0,
          comment: form.comment,
          enable: true,
        },
        inboundIds: form.inboundIds,
      }));
      const msg = await bulkCreate(payloads);
      const ok = msg?.obj?.created ?? 0;
      const skipped = msg?.obj?.skipped ?? [];
      const failed = skipped.length;
      const firstError = skipped[0]?.reason ?? msg?.msg ?? '';
      if (failed === 0 && msg?.success) {
        messageApi.success(t('pages.clients.toasts.bulkCreated', { count: ok }));
      } else {
        messageApi.warning(firstError
          ? `${t('pages.clients.toasts.bulkCreatedMixed', { ok, failed })} — ${firstError}`
          : t('pages.clients.toasts.bulkCreatedMixed', { ok, failed }));
      }
      onSaved?.();
      onOpenChange(false);
    } finally {
      setSaving(false);
    }
  }

  return (
    <>
      {messageContextHolder}
      <Modal
        open={open}
        title={t('pages.clients.bulk')}
        okText={t('create')}
        cancelText={t('close')}
        confirmLoading={saving}
        mask={{ closable: false }}
        width={640}
        onOk={submit}
        onCancel={() => onOpenChange(false)}
      >
        <Form colon={false} labelCol={{ sm: { span: 8 } }} wrapperCol={{ sm: { span: 14 } }}>
          <Form.Item label={t('pages.clients.attachedInbounds')} required>
            <Select
              mode="multiple"
              value={form.inboundIds}
              onChange={(v) => update('inboundIds', v)}
              options={inboundOptions}
              placeholder={t('pages.clients.selectInbound')}
              showSearch={{
                filterOption: (input, option) => ((option?.label as string) || '').toLowerCase().includes(input.toLowerCase()),
              }}
            />
          </Form.Item>

          <Form.Item label={t('pages.clients.method')}>
            <Select
              value={form.emailMethod}
              onChange={(v) => update('emailMethod', v)}
              options={[
                { value: 0, label: 'Random' },
                { value: 1, label: 'Random + Prefix' },
                { value: 2, label: 'Random + Prefix + Num' },
                { value: 3, label: 'Random + Prefix + Num + Postfix' },
                { value: 4, label: 'Prefix + Num + Postfix' },
              ]}
            />
          </Form.Item>

          {form.emailMethod > 1 && (
            <>
              <Form.Item label={t('pages.clients.first')}>
                <InputNumber value={form.firstNum} min={1} onChange={(v) => update('firstNum', Number(v) || 1)} />
              </Form.Item>
              <Form.Item label={t('pages.clients.last')}>
                <InputNumber value={form.lastNum} min={form.firstNum} onChange={(v) => update('lastNum', Number(v) || 1)} />
              </Form.Item>
            </>
          )}
          {form.emailMethod > 0 && (
            <Form.Item label={t('pages.clients.prefix')}>
              <Input value={form.emailPrefix} onChange={(e) => update('emailPrefix', e.target.value)} />
            </Form.Item>
          )}
          {form.emailMethod > 2 && (
            <Form.Item label={t('pages.clients.postfix')}>
              <Input value={form.emailPostfix} onChange={(e) => update('emailPostfix', e.target.value)} />
            </Form.Item>
          )}
          {form.emailMethod < 2 && (
            <Form.Item label={t('pages.clients.clientCount')}>
              <InputNumber value={form.quantity} min={1} max={100} onChange={(v) => update('quantity', Number(v) || 1)} />
            </Form.Item>
          )}

          <Form.Item label={t('pages.clients.subId')}>
            <Space.Compact style={{ display: 'flex' }}>
              <Input
                value={form.subId}
                onChange={(e) => update('subId', e.target.value)}
                style={{ flex: 1 }}
              />
              <Button
                icon={<ReloadOutlined />}
                onClick={() => update('subId', RandomUtil.randomLowerAndNum(16))}
              />
            </Space.Compact>
          </Form.Item>

          <Form.Item label={t('comment')}>
            <Input value={form.comment} onChange={(e) => update('comment', e.target.value)} />
          </Form.Item>

          {showFlow && (
            <Form.Item label={t('pages.clients.flow')}>
              <Select
                value={form.flow}
                onChange={(v) => update('flow', v)}
                style={{ width: 220 }}
                options={[
                  { value: '', label: t('none') },
                  ...FLOW_OPTIONS.map((k) => ({ value: k, label: k })),
                ]}
              />
            </Form.Item>
          )}

          {ipLimitEnable && (
            <Form.Item label={t('pages.clients.limitIp')}>
              <InputNumber value={form.limitIp} min={0} onChange={(v) => update('limitIp', Number(v) || 0)} />
            </Form.Item>
          )}

          <Form.Item label={t('pages.clients.totalGB')}>
            <InputNumber value={form.totalGB} min={0} step={1} onChange={(v) => update('totalGB', Number(v) || 0)} />
          </Form.Item>

          <Form.Item label={t('pages.clients.delayedStart')}>
            <Switch
              checked={delayedStart}
              onClick={() => { setDelayedStart(!delayedStart); update('expiryTime', 0); }}
            />
          </Form.Item>

          {delayedStart ? (
            <Form.Item label={t('pages.clients.expireDays')}>
              <InputNumber
                value={delayedExpireDays}
                min={0}
                onChange={(v) => update('expiryTime', -86400000 * (Number(v) || 0))}
              />
            </Form.Item>
          ) : (
            <Form.Item label={t('pages.inbounds.expireDate')}>
              <DateTimePicker
                value={expiryDate}
                onChange={(next) => update('expiryTime', next ? next.valueOf() : 0)}
              />
            </Form.Item>
          )}

          <Form.Item
            label={t('pages.clients.renew')}
            tooltip={t('pages.clients.renewDesc')}
          >
            <InputNumber
              value={form.reset}
              min={0}
              onChange={(v) => update('reset', Number(v) || 0)}
            />
          </Form.Item>
        </Form>
      </Modal>
    </>
  );
}
