// frontend/src/pages/clients/ClientFormModal.vue
<script setup>
import { computed, reactive, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { message } from 'ant-design-vue';
import dayjs from 'dayjs';
import { HttpUtil, RandomUtil } from '@/utils';
import { DBInbound } from '@/models/dbinbound.js';
import { TLS_FLOW_CONTROL } from '@/models/inbound.js';

const FLOW_OPTIONS = Object.values(TLS_FLOW_CONTROL);

const props = defineProps({
  open: { type: Boolean, default: false },
  mode: { type: String, default: 'add' },
  client: { type: Object, default: null },
  inbounds: { type: Array, default: () => [] },
  attachedIds: { type: Array, default: () => [] },
  ipLimitEnable: { type: Boolean, default: false },
  save: { type: Function, required: true },
});

const emit = defineEmits(['update:open']);
const { t } = useI18n();

const submitting = ref(false);
const form = reactive(emptyForm());

function emptyForm() {
  return {
    email: '',
    subId: '',
    uuid: '',
    password: '',
    auth: '',
    flow: '',
    reverseTag: '',
    totalGB: 0,
    expiryTime: null,
    limitIp: 0,
    comment: '',
    enable: true,
    inboundIds: [],
  };
}

const isEdit = computed(() => props.mode === 'edit');

watch(
  () => props.open,
  (next) => {
    if (!next) return;
    Object.assign(form, emptyForm());
    if (isEdit.value && props.client) {
      form.email = props.client.email || '';
      form.subId = props.client.subId || '';
      form.uuid = props.client.uuid || '';
      form.password = props.client.password || '';
      form.auth = props.client.auth || '';
      form.flow = props.client.flow || '';
      form.reverseTag = props.client.reverse?.tag || '';
      form.totalGB = bytesToGB(props.client.totalGB || 0);
      form.expiryTime = props.client.expiryTime ? dayjs(props.client.expiryTime) : null;
      form.limitIp = props.client.limitIp || 0;
      form.comment = props.client.comment || '';
      form.enable = !!props.client.enable;
      form.inboundIds = Array.isArray(props.attachedIds) ? [...props.attachedIds] : [];
      void loadIps();
    } else {
      form.email = RandomUtil.randomLowerAndNum(9);
      form.uuid = RandomUtil.randomUUID();
      form.subId = RandomUtil.randomLowerAndNum(16);
      form.password = RandomUtil.randomLowerAndNum(16);
      form.auth = RandomUtil.randomLowerAndNum(16);
    }
  },
);

function bytesToGB(bytes) {
  if (!bytes || bytes <= 0) return 0;
  return Math.round((bytes / (1024 * 1024 * 1024)) * 100) / 100;
}

function gbToBytes(gb) {
  if (!gb || gb <= 0) return 0;
  return Math.round(gb * 1024 * 1024 * 1024);
}

const MULTI_CLIENT_PROTOCOLS = new Set([
  'shadowsocks', 'vless', 'vmess', 'trojan', 'hysteria', 'hysteria2', 'portfallback',
]);

const inboundOptions = computed(() =>
  (props.inbounds || [])
    .filter((ib) => MULTI_CLIENT_PROTOCOLS.has(ib.protocol))
    .map((ib) => ({
      label: `${ib.remark || `#${ib.id}`} · ${ib.protocol}:${ib.port}`,
      value: ib.id,
      title: `${ib.remark || ''} (${ib.protocol}:${ib.port})`,
    })),
);

const flowCapableIds = computed(() => {
  const ids = new Set();
  for (const row of props.inbounds || []) {
    try {
      const parsed = new DBInbound(row).toInbound();
      if (parsed.canEnableTlsFlow?.()) ids.add(row.id);
    } catch (_e) { /* ignore unparsable */ }
  }
  return ids;
});

const showFlow = computed(() =>
  (form.inboundIds || []).some((id) => flowCapableIds.value.has(id)),
);

watch(showFlow, (next) => {
  if (!next) form.flow = '';
});

const vlessLikeIds = computed(() => {
  const ids = new Set();
  for (const row of props.inbounds || []) {
    if (row && (row.protocol === 'vless' || row.protocol === 'portfallback')) {
      ids.add(row.id);
    }
  }
  return ids;
});

const showReverseTag = computed(() =>
  (form.inboundIds || []).some((id) => vlessLikeIds.value.has(id)),
);

watch(showReverseTag, (next) => {
  if (!next) form.reverseTag = '';
});

const clientIps = ref([]);
const ipsLoading = ref(false);
const ipsClearing = ref(false);

async function loadIps() {
  if (!isEdit.value || !props.client?.email) return;
  ipsLoading.value = true;
  try {
    const msg = await HttpUtil.post(`/panel/api/clients/ips/${encodeURIComponent(props.client.email)}`);
    if (!msg?.success) { clientIps.value = []; return; }
    const arr = Array.isArray(msg.obj) ? msg.obj : [];
    clientIps.value = arr.filter((x) => typeof x === 'string' && x.length > 0);
  } finally {
    ipsLoading.value = false;
  }
}

async function clearIps() {
  if (!isEdit.value || !props.client?.email) return;
  ipsClearing.value = true;
  try {
    const msg = await HttpUtil.post(`/panel/api/clients/clearIps/${encodeURIComponent(props.client.email)}`);
    if (msg?.success) clientIps.value = [];
  } finally {
    ipsClearing.value = false;
  }
}

function close() {
  emit('update:open', false);
}

function regenerateUUID() {
  form.uuid = RandomUtil.randomUUID();
}

function regeneratePassword() {
  form.password = RandomUtil.randomLowerAndNum(16);
}

function regenerateAuth() {
  form.auth = RandomUtil.randomLowerAndNum(16);
}

function regenerateSubId() {
  form.subId = RandomUtil.randomLowerAndNum(16);
}

function regenerateEmail() {
  form.email = RandomUtil.randomLowerAndNum(9);
}

async function onSubmit() {
  if (!form.email || form.email.trim() === '') {
    message.error(t('pages.clients.email') + ' *');
    return;
  }
  if (!isEdit.value && (!form.inboundIds || form.inboundIds.length === 0)) {
    message.error(t('pages.clients.selectInbound'));
    return;
  }
  const clientPayload = {
    email: form.email.trim(),
    subId: form.subId,
    id: form.uuid,
    password: form.password,
    auth: form.auth,
    flow: showFlow.value ? (form.flow || '') : '',
    totalGB: gbToBytes(form.totalGB),
    expiryTime: form.expiryTime ? form.expiryTime.valueOf() : 0,
    limitIp: Number(form.limitIp) || 0,
    comment: form.comment,
    enable: !!form.enable,
  };
  const reverseTag = showReverseTag.value ? (form.reverseTag || '').trim() : '';
  if (reverseTag) {
    clientPayload.reverse = { tag: reverseTag };
  }

  submitting.value = true;
  try {
    let msg;
    if (isEdit.value) {
      const original = new Set(props.attachedIds || []);
      const next = new Set(form.inboundIds || []);
      const toAttach = [...next].filter((id) => !original.has(id));
      const toDetach = [...original].filter((id) => !next.has(id));
      msg = await props.save(clientPayload, {
        isEdit: true,
        email: props.client.email,
        attach: toAttach,
        detach: toDetach,
      });
    } else {
      msg = await props.save(
        { client: clientPayload, inboundIds: form.inboundIds },
        { isEdit: false },
      );
    }
    if (msg?.success) close();
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <a-modal :open="open" :title="isEdit ? t('pages.clients.editTitle') : t('pages.clients.addTitle')"
    :destroy-on-close="true" :ok-text="isEdit ? t('save') : t('add')" :cancel-text="t('cancel')"
    :ok-button-props="{ loading: submitting }" :width="720" @ok="onSubmit" @cancel="close">
    <a-form layout="vertical" :model="form">
      <a-row :gutter="16">
        <a-col :span="12">
          <a-form-item :label="t('pages.clients.email')" required>
            <a-input-group compact style="display: flex">
              <a-input v-model:value="form.email" :placeholder="t('pages.clients.email')" style="flex: 1" />
              <a-button @click="regenerateEmail">↻</a-button>
            </a-input-group>
          </a-form-item>
        </a-col>
        <a-col :span="12">
          <a-form-item :label="t('pages.clients.subId') || 'subId'">
            <a-input-group compact style="display: flex">
              <a-input v-model:value="form.subId" style="flex: 1" />
              <a-button @click="regenerateSubId">↻</a-button>
            </a-input-group>
          </a-form-item>
        </a-col>
      </a-row>

      <a-row :gutter="16">
        <a-col :span="12">
          <a-form-item label="UUID">
            <a-input-group compact style="display: flex">
              <a-input v-model:value="form.uuid" style="flex: 1" />
              <a-button @click="regenerateUUID">↻</a-button>
            </a-input-group>
          </a-form-item>
        </a-col>
        <a-col :span="12">
          <a-form-item :label="t('pages.clients.password') || 'Password'">
            <a-input-group compact style="display: flex">
              <a-input v-model:value="form.password" style="flex: 1" />
              <a-button @click="regeneratePassword">↻</a-button>
            </a-input-group>
          </a-form-item>
        </a-col>
      </a-row>

      <a-row :gutter="16">
        <a-col :span="12">
          <a-form-item label="Auth (Hysteria)">
            <a-input-group compact style="display: flex">
              <a-input v-model:value="form.auth" style="flex: 1" />
              <a-button @click="regenerateAuth">↻</a-button>
            </a-input-group>
          </a-form-item>
        </a-col>
        <a-col :span="12">
          <a-form-item :label="t('pages.clients.limitIp') || 'IP limit'">
            <a-input-number v-model:value="form.limitIp" :min="0" :disabled="!ipLimitEnable" style="width: 100%" />
          </a-form-item>
        </a-col>
      </a-row>

      <a-row :gutter="16">
        <a-col :span="12">
          <a-form-item :label="t('pages.clients.totalGB') || 'Total (GB, 0 = unlimited)'">
            <a-input-number v-model:value="form.totalGB" :min="0" :step="0.1" style="width: 100%" />
          </a-form-item>
        </a-col>
        <a-col :span="12">
          <a-form-item :label="t('pages.clients.expiryTime') || 'Expiry'">
            <a-date-picker v-model:value="form.expiryTime" show-time style="width: 100%" />
          </a-form-item>
        </a-col>
      </a-row>

      <a-row v-if="showFlow || showReverseTag" :gutter="16">
        <a-col v-if="showFlow" :span="12">
          <a-form-item label="Flow">
            <a-select v-model:value="form.flow">
              <a-select-option value="">none</a-select-option>
              <a-select-option v-for="k in FLOW_OPTIONS" :key="k" :value="k">{{ k }}</a-select-option>
            </a-select>
          </a-form-item>
        </a-col>
        <a-col v-if="showReverseTag" :span="12">
          <a-form-item label="Reverse tag">
            <a-input v-model:value="form.reverseTag" placeholder="Optional reverse tag" />
          </a-form-item>
        </a-col>
      </a-row>

      <a-form-item :label="t('pages.clients.comment') || 'Comment'">
        <a-input v-model:value="form.comment" />
      </a-form-item>

      <a-form-item :label="t('pages.clients.attachedInbounds') || 'Attached inbounds'" :required="!isEdit">
        <a-select v-model:value="form.inboundIds" mode="multiple" :options="inboundOptions" :show-search="true"
          :placeholder="t('pages.clients.selectInbound') || 'Select one or more inbounds'"
          :filter-option="(input, option) => (option.label || '').toLowerCase().includes(input.toLowerCase())" />
      </a-form-item>

      <a-form-item>
        <a-switch v-model:checked="form.enable" />
        <span style="margin-left: 8px">{{ t('enable') }}</span>
      </a-form-item>

      <a-form-item v-if="isEdit && ipLimitEnable" :label="t('pages.clients.ipLog') || 'IP Log'">
        <a-space style="margin-bottom: 8px">
          <a-button size="small" :loading="ipsLoading" @click="loadIps">{{ t('refresh') }}</a-button>
          <a-button size="small" danger :loading="ipsClearing" :disabled="clientIps.length === 0" @click="clearIps">
            {{ t('clearAll') || 'Clear' }}
          </a-button>
        </a-space>
        <div v-if="clientIps.length > 0">
          <a-tag v-for="(ip, idx) in clientIps" :key="idx" color="blue" style="margin-bottom: 4px">{{ ip }}</a-tag>
        </div>
        <a-tag v-else>{{ t('tgbot.noIpRecord') || 'No IP record' }}</a-tag>
      </a-form-item>
    </a-form>
  </a-modal>
</template>

// frontend/src/pages/clients/ClientFormModal.tsx
import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  Button,
  Col,
  Form,
  Input,
  InputNumber,
  Modal,
  Row,
  Select,
  Space,
  Switch,
  Tag,
  message,
} from 'antd';
import dayjs from 'dayjs';
import type { Dayjs } from 'dayjs';

import { HttpUtil, RandomUtil } from '@/utils';
import DateTimePicker from '@/components/DateTimePicker';
import { TLS_FLOW_CONTROL } from '@/schemas/primitives';
import type { ClientRecord, InboundOption } from '@/hooks/useClients';
import { ClientFormSchema, ClientCreateFormSchema } from '@/schemas/client';

const FLOW_OPTIONS = Object.values(TLS_FLOW_CONTROL);

const MULTI_CLIENT_PROTOCOLS = new Set([
  'shadowsocks', 'vless', 'vmess', 'trojan', 'hysteria',
]);

interface ApiMsg<T = unknown> {
  success?: boolean;
  obj?: T;
}

type Mode = 'add' | 'edit';

interface SaveMetaEdit {
  isEdit: true;
  email: string;
  attach: number[];
  detach: number[];
}

interface SaveMetaCreate {
  isEdit: false;
}

interface SaveCreatePayload {
  client: Record<string, unknown>;
  inboundIds: number[];
}

interface ClientFormModalProps {
  open: boolean;
  mode: Mode;
  client: ClientRecord | null;
  inbounds: InboundOption[];
  attachedIds?: number[];
  ipLimitEnable?: boolean;
  tgBotEnable?: boolean;
  save: (
    payload: Record<string, unknown> | SaveCreatePayload,
    meta: SaveMetaEdit | SaveMetaCreate,
  ) => Promise<ApiMsg | null>;
  onOpenChange: (open: boolean) => void;
}

interface FormState {
  email: string;
  subId: string;
  uuid: string;
  password: string;
  auth: string;
  flow: string;
  reverseTag: string;
  totalGB: number;
  expiryDate: Dayjs | null;
  delayedStart: boolean;
  delayedDays: number;
  limitIp: number;
  tgId: number;
  comment: string;
  enable: boolean;
  inboundIds: number[];
}

function emptyForm(): FormState {
  return {
    email: '',
    subId: '',
    uuid: '',
    password: '',
    auth: '',
    flow: '',
    reverseTag: '',
    totalGB: 0,
    expiryDate: null,
    delayedStart: false,
    delayedDays: 0,
    limitIp: 0,
    tgId: 0,
    comment: '',
    enable: true,
    inboundIds: [],
  };
}

function bytesToGB(bytes: number): number {
  if (!bytes || bytes <= 0) return 0;
  return Math.round((bytes / (1024 * 1024 * 1024)) * 100) / 100;
}

function gbToBytes(gb: number): number {
  if (!gb || gb <= 0) return 0;
  return Math.round(gb * 1024 * 1024 * 1024);
}

export default function ClientFormModal({
  open,
  mode,
  client,
  inbounds,
  attachedIds = [],
  ipLimitEnable = false,
  tgBotEnable = false,
  save,
  onOpenChange,
}: ClientFormModalProps) {
  const { t } = useTranslation();
  const [messageApi, messageContextHolder] = message.useMessage();
  const isEdit = mode === 'edit';

  const [form, setForm] = useState<FormState>(emptyForm);
  const [submitting, setSubmitting] = useState(false);
  const [clientIps, setClientIps] = useState<string[]>([]);
  const [ipsLoading, setIpsLoading] = useState(false);
  const [ipsClearing, setIpsClearing] = useState(false);

  function update<K extends keyof FormState>(key: K, value: FormState[K]) {
    setForm((prev) => ({ ...prev, [key]: value }));
  }

  useEffect(() => {
    if (!open) return;

    if (isEdit && client) {
      const et = Number(client.expiryTime) || 0;
      const next: FormState = {
        ...emptyForm(),
        email: client.email || '',
        subId: client.subId || '',
        uuid: client.uuid || '',
        password: client.password || '',
        auth: client.auth || '',
        flow: client.flow || '',
        reverseTag: client.reverse?.tag || '',
        totalGB: bytesToGB(client.totalGB || 0),
        limitIp: client.limitIp || 0,
        tgId: Number(client.tgId) || 0,
        comment: client.comment || '',
        enable: !!client.enable,
        inboundIds: Array.isArray(attachedIds) ? [...attachedIds] : [],
      };
      if (et < 0) {
        next.delayedStart = true;
        next.delayedDays = Math.round(et / -86400000);
        next.expiryDate = null;
      } else {
        next.delayedStart = false;
        next.delayedDays = 0;
        next.expiryDate = et > 0 ? dayjs(et) : null;
      }
      setForm(next);
      void loadIps();
    } else {
      setForm({
        ...emptyForm(),
        email: RandomUtil.randomLowerAndNum(9),
        uuid: RandomUtil.randomUUID(),
        subId: RandomUtil.randomLowerAndNum(16),
        password: RandomUtil.randomLowerAndNum(16),
        auth: RandomUtil.randomLowerAndNum(16),
      });
    }

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, isEdit]);

  const flowCapableIds = useMemo(() => {
    const ids = new Set<number>();
    for (const row of inbounds || []) {
      if (row?.tlsFlowCapable) ids.add(row.id);
    }
    return ids;
  }, [inbounds]);

  const vlessLikeIds = useMemo(() => {
    const ids = new Set<number>();
    for (const row of inbounds || []) {
      if (row && row.protocol === 'vless') ids.add(row.id);
    }
    return ids;
  }, [inbounds]);

  const showFlow = useMemo(
    () => (form.inboundIds || []).some((id) => flowCapableIds.has(id)),
    [form.inboundIds, flowCapableIds],
  );

  const showReverseTag = useMemo(
    () => (form.inboundIds || []).some((id) => vlessLikeIds.has(id)),
    [form.inboundIds, vlessLikeIds],
  );

  useEffect(() => {
    if (!showFlow && form.flow) {

      update('flow', '');
    }
  }, [showFlow, form.flow]);

  useEffect(() => {
    if (!showReverseTag && form.reverseTag) {

      update('reverseTag', '');
    }
  }, [showReverseTag, form.reverseTag]);

  const inboundOptions = useMemo(
    () => (inbounds || [])
      .filter((ib) => MULTI_CLIENT_PROTOCOLS.has(ib.protocol || ''))
      .map((ib) => ({
        label: `${ib.remark || `#${ib.id}`} · ${ib.protocol}:${ib.port}`,
        value: ib.id,
        title: `${ib.remark || ''} (${ib.protocol}:${ib.port})`,
      })),
    [inbounds],
  );

  async function loadIps() {
    if (!isEdit || !client?.email) return;
    setIpsLoading(true);
    try {
      const msg = await HttpUtil.post(`/panel/api/clients/ips/${encodeURIComponent(client.email)}`) as ApiMsg<unknown[]>;
      if (!msg?.success) { setClientIps([]); return; }
      const arr = Array.isArray(msg.obj) ? msg.obj : [];
      setClientIps(arr.filter((x): x is string => typeof x === 'string' && x.length > 0));
    } finally {
      setIpsLoading(false);
    }
  }

  async function clearIps() {
    if (!isEdit || !client?.email) return;
    setIpsClearing(true);
    try {
      const msg = await HttpUtil.post(`/panel/api/clients/clearIps/${encodeURIComponent(client.email)}`) as ApiMsg;
      if (msg?.success) setClientIps([]);
    } finally {
      setIpsClearing(false);
    }
  }

  function close() {
    onOpenChange(false);
  }

  async function onSubmit() {
    const schema = isEdit ? ClientFormSchema : ClientCreateFormSchema;
    const validated = schema.safeParse({
      email: form.email,
      subId: form.subId,
      uuid: form.uuid,
      password: form.password,
      auth: form.auth,
      flow: form.flow,
      reverseTag: form.reverseTag,
      totalGB: form.totalGB,
      delayedStart: form.delayedStart,
      delayedDays: form.delayedDays,
      limitIp: form.limitIp,
      tgId: form.tgId,
      comment: form.comment,
      enable: form.enable,
      inboundIds: form.inboundIds,
    });
    if (!validated.success) {
      const issue = validated.error.issues[0];
      messageApi.error(t(issue?.message ?? 'somethingWentWrong'));
      return;
    }
    const expiryTime = form.delayedStart
      ? -86400000 * (Number(form.delayedDays) || 0)
      : (form.expiryDate ? form.expiryDate.valueOf() : 0);
    const clientPayload: Record<string, unknown> = {
      email: form.email.trim(),
      subId: form.subId,
      id: form.uuid,
      password: form.password,
      auth: form.auth,
      flow: showFlow ? (form.flow || '') : '',
      totalGB: gbToBytes(form.totalGB),
      expiryTime,
      limitIp: Number(form.limitIp) || 0,
      tgId: Number(form.tgId) || 0,
      comment: form.comment,
      enable: !!form.enable,
    };
    const reverseTag = showReverseTag ? (form.reverseTag || '').trim() : '';
    if (reverseTag) {
      clientPayload.reverse = { tag: reverseTag };
    }

    setSubmitting(true);
    try {
      let msg;
      if (isEdit && client) {
        const original = new Set(attachedIds || []);
        const next = new Set(form.inboundIds || []);
        const toAttach = [...next].filter((id) => !original.has(id));
        const toDetach = [...original].filter((id) => !next.has(id));
        msg = await save(clientPayload, {
          isEdit: true,
          email: client.email,
          attach: toAttach,
          detach: toDetach,
        });
      } else {
        msg = await save(
          { client: clientPayload, inboundIds: form.inboundIds },
          { isEdit: false },
        );
      }
      if (msg?.success) close();
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <>
      {messageContextHolder}
      <Modal
        open={open}
        title={isEdit ? t('pages.clients.editTitle') : t('pages.clients.addTitle')}
        destroyOnHidden
        okText={isEdit ? t('save') : t('create')}
        cancelText={t('cancel')}
        okButtonProps={{ loading: submitting }}
        width={720}
        onOk={onSubmit}
        onCancel={close}
      >
        <Form layout="vertical">
          <Row gutter={16}>
            <Col xs={24} md={12}>
              <Form.Item label={t('pages.clients.email')} required>
                <Space.Compact style={{ display: 'flex' }}>
                  <Input
                    value={form.email}
                    placeholder={t('pages.clients.email')}
                    style={{ flex: 1 }}
                    onChange={(e) => update('email', e.target.value)}
                  />
                  <Button onClick={() => update('email', RandomUtil.randomLowerAndNum(12))}>↻</Button>
                </Space.Compact>
              </Form.Item>
            </Col>
            <Col xs={24} md={12}>
              <Form.Item label={t('pages.clients.subId')}>
                <Space.Compact style={{ display: 'flex' }}>
                  <Input value={form.subId} style={{ flex: 1 }} onChange={(e) => update('subId', e.target.value)} />
                  <Button onClick={() => update('subId', RandomUtil.randomLowerAndNum(16))}>↻</Button>
                </Space.Compact>
              </Form.Item>
            </Col>
          </Row>

          <Row gutter={16}>
            <Col xs={24} md={12}>
              <Form.Item label={t('pages.clients.hysteriaAuth')}>
                <Space.Compact style={{ display: 'flex' }}>
                  <Input value={form.auth} style={{ flex: 1 }} onChange={(e) => update('auth', e.target.value)} />
                  <Button onClick={() => update('auth', RandomUtil.randomLowerAndNum(16))}>↻</Button>
                </Space.Compact>
              </Form.Item>
            </Col>
            <Col xs={24} md={12}>
              <Form.Item label={t('pages.clients.password')}>
                <Space.Compact style={{ display: 'flex' }}>
                  <Input value={form.password} style={{ flex: 1 }} onChange={(e) => update('password', e.target.value)} />
                  <Button onClick={() => update('password', RandomUtil.randomLowerAndNum(16))}>↻</Button>
                </Space.Compact>
              </Form.Item>
            </Col>
          </Row>

          <Row gutter={16}>
            <Col xs={24} md={12}>
              <Form.Item label={t('pages.clients.uuid')}>
                <Space.Compact style={{ display: 'flex' }}>
                  <Input value={form.uuid} style={{ flex: 1 }} onChange={(e) => update('uuid', e.target.value)} />
                  <Button onClick={() => update('uuid', RandomUtil.randomUUID())}>↻</Button>
                </Space.Compact>
              </Form.Item>
            </Col>
            <Col xs={24} md={ipLimitEnable ? 8 : 12}>
              <Form.Item label={t('pages.clients.totalGB')}>
                <InputNumber value={form.totalGB} min={0} step={1} style={{ width: '100%' }}
                  onChange={(v) => update('totalGB', Number(v) || 0)} />
              </Form.Item>
            </Col>
            {ipLimitEnable && (
              <Col xs={24} md={4}>
                <Form.Item label={t('pages.clients.limitIp')}>
                  <InputNumber value={form.limitIp} min={0} style={{ width: '100%' }}
                    onChange={(v) => update('limitIp', Number(v) || 0)} />
                </Form.Item>
              </Col>
            )}
          </Row>

          <Row gutter={16}>
            <Col xs={24} md={12}>
              {form.delayedStart ? (
                <Form.Item label={t('pages.clients.expireDays')}>
                  <InputNumber value={form.delayedDays} min={0} style={{ width: '100%' }}
                    onChange={(v) => update('delayedDays', Number(v) || 0)} />
                </Form.Item>
              ) : (
                <Form.Item label={t('pages.clients.expiryTime')}>
                  <DateTimePicker
                    value={form.expiryDate}
                    onChange={(d) => update('expiryDate', d || null)}
                  />
                </Form.Item>
              )}
            </Col>
            <Col xs={24} md={12}>
              <Form.Item label={t('pages.clients.delayedStart')}>
                <Switch
                  checked={form.delayedStart}
                  onChange={(v) => {
                    update('delayedStart', v);
                    if (v) update('expiryDate', null);
                    else update('delayedDays', 0);
                  }}
                />
              </Form.Item>
            </Col>
          </Row>

          {(showFlow || showReverseTag) && (
            <Row gutter={16}>
              {showFlow && (
                <Col xs={24} md={12}>
                  <Form.Item label={t('pages.clients.flow')}>
                    <Select
                      value={form.flow}
                      onChange={(v) => update('flow', v)}
                      options={[
                        { value: '', label: t('none') },
                        ...FLOW_OPTIONS.map((k) => ({ value: k, label: k })),
                      ]}
                    />
                  </Form.Item>
                </Col>
              )}
              {showReverseTag && (
                <Col xs={24} md={12}>
                  <Form.Item label={t('pages.clients.reverseTag')}>
                    <Input value={form.reverseTag} placeholder={t('pages.clients.reverseTagPlaceholder')}
                      onChange={(e) => update('reverseTag', e.target.value)} />
                  </Form.Item>
                </Col>
              )}
            </Row>
          )}

          <Row gutter={16}>
            {tgBotEnable && (
              <Col xs={24} md={12}>
                <Form.Item label={t('pages.clients.telegramId')}>
                  <InputNumber value={form.tgId} min={0} controls={false}
                    placeholder={t('pages.clients.telegramIdPlaceholder')} style={{ width: '100%' }}
                    onChange={(v) => update('tgId', Number(v) || 0)} />
                </Form.Item>
              </Col>
            )}
            <Col xs={24} md={tgBotEnable ? 12 : 24}>
              <Form.Item label={t('pages.clients.comment')}>
                <Input value={form.comment} onChange={(e) => update('comment', e.target.value)} />
              </Form.Item>
            </Col>
          </Row>

          <Form.Item label={t('pages.clients.attachedInbounds')} required={!isEdit}>
            <Select
              mode="multiple"
              value={form.inboundIds}
              onChange={(v) => update('inboundIds', v)}
              options={inboundOptions}
              placeholder={t('pages.clients.selectInbound')}
              showSearch={{
                filterOption: (input, option) => ((option?.label as string) || '').toLowerCase().includes(input.toLowerCase()),
              }}
            />
          </Form.Item>

          <Form.Item>
            <Switch checked={form.enable} onChange={(v) => update('enable', v)} />
            <span style={{ marginLeft: 8 }}>{t('enable')}</span>
          </Form.Item>

          {isEdit && ipLimitEnable && (
            <Form.Item label={t('pages.clients.ipLog')}>
              <Space style={{ marginBottom: 8 }}>
                <Button size="small" loading={ipsLoading} onClick={loadIps}>{t('refresh')}</Button>
                <Button size="small" danger loading={ipsClearing} disabled={clientIps.length === 0} onClick={clearIps}>
                  {t('pages.clients.clearAll')}
                </Button>
              </Space>
              {clientIps.length > 0 ? (
                <div>
                  {clientIps.map((ip, idx) => (
                    <Tag key={idx} color="blue" style={{ marginBottom: 4 }}>{ip}</Tag>
                  ))}
                </div>
              ) : (
                <Tag>{t('tgbot.noIpRecord')}</Tag>
              )}
            </Form.Item>
          )}
        </Form>
      </Modal>
    </>
  );
}
