// frontend/src/pages/xray/BalancerFormModal.vue
<script setup>
import { computed, reactive, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

const { t } = useI18n();

// Balancer add/edit modal — mirrors xray_balancer_modal.html.
// Tag must be unique across other balancers; selector is a tag-mode
// list constrained to existing outbound tags (but lets users type
// new ones for forward-references).

const props = defineProps({
  open: { type: Boolean, default: false },
  balancer: { type: Object, default: null },
  outboundTags: { type: Array, default: () => [] },
  // All other balancer tags (excludes the one currently being edited)
  // — used for the duplicate-tag check.
  otherTags: { type: Array, default: () => [] },
});

const emit = defineEmits(['update:open', 'confirm']);

const STRATEGIES = [
  { value: 'random', label: 'Random' },
  { value: 'roundRobin', label: 'Round robin' },
  { value: 'leastLoad', label: 'Least load' },
  { value: 'leastPing', label: 'Least ping' },
];

const form = reactive({
  tag: '',
  strategy: 'random',
  selector: [],
  fallbackTag: '',
});
const isEdit = ref(false);

watch(() => props.open, (next) => {
  if (!next) return;
  if (props.balancer) {
    isEdit.value = true;
    form.tag = props.balancer.tag || '';
    form.strategy = props.balancer.strategy || 'random';
    form.selector = [...(props.balancer.selector || [])];
    form.fallbackTag = props.balancer.fallbackTag || '';
  } else {
    isEdit.value = false;
    form.tag = '';
    form.strategy = 'random';
    form.selector = [];
    form.fallbackTag = '';
  }
});

const tagEmpty = computed(() => !form.tag?.trim());
const duplicateTag = computed(
  () => !!form.tag && props.otherTags.includes(form.tag.trim()),
);
const emptySelector = computed(() => form.selector.length === 0);
const isValid = computed(
  () => !tagEmpty.value && !duplicateTag.value && !emptySelector.value,
);

const tagValidateStatus = computed(() => {
  if (tagEmpty.value) return 'error';
  if (duplicateTag.value) return 'warning';
  return 'success';
});
const tagHelp = computed(() => {
  if (tagEmpty.value) return 'Tag is required';
  if (duplicateTag.value) return 'Tag already used by another balancer';
  return '';
});

const selectorValidateStatus = computed(() => (emptySelector.value ? 'error' : 'success'));
const selectorHelp = computed(() => (emptySelector.value ? 'Pick at least one outbound' : ''));

function close() { emit('update:open', false); }
function onOk() {
  if (!isValid.value) return;
  emit('confirm', { ...form });
}

const title = computed(() =>
  isEdit.value
    ? `${t('edit')} ${t('pages.xray.Balancers')}`
    : `+ ${t('pages.xray.Balancers')}`,
);
const okText = computed(() =>
  isEdit.value ? t('pages.clients.submitEdit') : t('create'),
);
</script>

<template>
  <a-modal :open="open" :title="title" :ok-text="okText" :cancel-text="t('close')"
    :ok-button-props="{ disabled: !isValid }" :mask-closable="false" @ok="onOk" @cancel="close">
    <a-form :colon="false" :label-col="{ md: { span: 8 } }" :wrapper-col="{ md: { span: 14 } }">
      <a-form-item label="Tag" :validate-status="tagValidateStatus" :help="tagHelp" has-feedback>
        <a-input v-model:value="form.tag" placeholder="unique balancer tag" />
      </a-form-item>

      <a-form-item label="Strategy">
        <a-select v-model:value="form.strategy">
          <a-select-option v-for="s in STRATEGIES" :key="s.value" :value="s.value">{{ s.label }}</a-select-option>
        </a-select>
      </a-form-item>

      <a-form-item label="Selector" :validate-status="selectorValidateStatus" :help="selectorHelp" has-feedback>
        <a-select v-model:value="form.selector" mode="tags" :token-separators="[',']">
          <a-select-option v-for="tag in outboundTags" :key="tag" :value="tag">{{ tag }}</a-select-option>
        </a-select>
      </a-form-item>

      <a-form-item label="Fallback">
        <a-select v-model:value="form.fallbackTag" allow-clear>
          <a-select-option v-for="tag in ['', ...outboundTags]" :key="tag || '__empty'" :value="tag">
            {{ tag || `(${t('none')})` }}
          </a-select-option>
        </a-select>
      </a-form-item>
    </a-form>
  </a-modal>
</template>

// frontend/src/pages/xray/BalancerFormModal.tsx
import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Form, Input, Modal, Select } from 'antd';

export interface BalancerFormValue {
  tag: string;
  strategy: string;
  selector: string[];
  fallbackTag: string;
}

interface BalancerFormModalProps {
  open: boolean;
  balancer: BalancerFormValue | null;
  outboundTags: string[];
  otherTags: string[];
  onClose: () => void;
  onConfirm: (value: BalancerFormValue) => void;
}

const STRATEGIES = [
  { value: 'random', label: 'Random' },
  { value: 'roundRobin', label: 'Round robin' },
  { value: 'leastLoad', label: 'Least load' },
  { value: 'leastPing', label: 'Least ping' },
];

export default function BalancerFormModal({
  open,
  balancer,
  outboundTags,
  otherTags,
  onClose,
  onConfirm,
}: BalancerFormModalProps) {
  const { t } = useTranslation();
  const [tag, setTag] = useState('');
  const [strategy, setStrategy] = useState('random');
  const [selector, setSelector] = useState<string[]>([]);
  const [fallbackTag, setFallbackTag] = useState('');

  const isEdit = balancer != null;

  useEffect(() => {
    if (!open) return;
    if (balancer) {
      setTag(balancer.tag || '');
      setStrategy(balancer.strategy || 'random');
      setSelector([...(balancer.selector || [])]);
      setFallbackTag(balancer.fallbackTag || '');
    } else {
      setTag('');
      setStrategy('random');
      setSelector([]);
      setFallbackTag('');
    }
  }, [open, balancer]);

  const tagEmpty = !tag.trim();
  const duplicateTag = !!tag && otherTags.includes(tag.trim());
  const emptySelector = selector.length === 0;
  const isValid = !tagEmpty && !duplicateTag && !emptySelector;

  const tagValidateStatus: 'error' | 'warning' | 'success' = tagEmpty
    ? 'error'
    : duplicateTag
      ? 'warning'
      : 'success';
  const tagHelp = tagEmpty
    ? 'Tag is required'
    : duplicateTag
      ? 'Tag already used by another balancer'
      : '';

  const selectorValidateStatus: 'error' | 'success' = emptySelector ? 'error' : 'success';
  const selectorHelp = emptySelector ? 'Pick at least one outbound' : '';

  function submit() {
    if (!isValid) return;
    onConfirm({ tag, strategy, selector, fallbackTag });
  }

  const title = isEdit
    ? `${t('edit')} ${t('pages.xray.Balancers')}`
    : `+ ${t('pages.xray.Balancers')}`;
  const okText = isEdit ? t('pages.clients.submitEdit') : t('create');

  const fallbackOptions = useMemo(
    () => ['', ...outboundTags].map((tg) => ({ value: tg, label: tg || `(${t('none')})` })),
    [outboundTags, t],
  );

  return (
    <Modal
      open={open}
      title={title}
      okText={okText}
      cancelText={t('close')}
      okButtonProps={{ disabled: !isValid }}
      mask={{ closable: false }}
      onOk={submit}
      onCancel={onClose}
    >
      <Form colon={false} labelCol={{ md: { span: 8 } }} wrapperCol={{ md: { span: 14 } }}>
        <Form.Item label="Tag" validateStatus={tagValidateStatus} help={tagHelp} hasFeedback>
          <Input value={tag} onChange={(e) => setTag(e.target.value)} placeholder="unique balancer tag" />
        </Form.Item>
        <Form.Item label="Strategy">
          <Select value={strategy} onChange={setStrategy} options={STRATEGIES} />
        </Form.Item>
        <Form.Item
          label="Selector"
          validateStatus={selectorValidateStatus}
          help={selectorHelp}
          hasFeedback
        >
          <Select
            mode="tags"
            value={selector}
            onChange={setSelector}
            tokenSeparators={[',']}
            options={outboundTags.map((tg) => ({ value: tg, label: tg }))}
          />
        </Form.Item>
        <Form.Item label="Fallback">
          <Select value={fallbackTag} onChange={setFallbackTag} allowClear options={fallbackOptions} />
        </Form.Item>
      </Form>
    </Modal>
  );
}
