// frontend/src/pages/xray/basics/BasicsTab.tsx
import { useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import { Alert, Button, Collapse, Input, Modal, Select, Space, Switch } from 'antd';
import { CloudOutlined, ApiOutlined } from '@ant-design/icons';

import { OutboundDomainStrategies } from '@/schemas/primitives';
import { SettingListItem } from '@/components/ui';
import type { XraySettingsValue, SetTemplate } from '@/hooks/useXraySetting';
import './BasicsTab.css';

interface BasicsTabProps {
  templateSettings: XraySettingsValue | null;
  setTemplateSettings: SetTemplate;
  outboundTestUrl: string;
  onChangeOutboundTestUrl: (v: string) => void;
  warpExist: boolean;
  nordExist: boolean;
  onShowWarp: () => void;
  onShowNord: () => void;
  onResetDefault: () => void;
}

const ROUTING_DOMAIN_STRATEGIES = ['AsIs', 'IPIfNonMatch', 'IPOnDemand'];
const LOG_LEVELS = ['none', 'debug', 'info', 'warning', 'error'];
const ACCESS_LOG = ['none', './access.log'];
const ERROR_LOG = ['none', './error.log'];
const MASK_ADDRESS = ['quarter', 'half', 'full'];
const BITTORRENT_PROTOCOLS = ['bittorrent'];

const IPS_OPTIONS = [
  { label: 'Private IPs', value: 'geoip:private' },
  { label: '🇮🇷 Iran', value: 'ext:geoip_IR.dat:ir' },
  { label: '🇨🇳 China', value: 'geoip:cn' },
  { label: '🇷🇺 Russia', value: 'ext:geoip_RU.dat:ru' },
  { label: '🇻🇳 Vietnam', value: 'geoip:vn' },
  { label: '🇪🇸 Spain', value: 'geoip:es' },
  { label: '🇮🇩 Indonesia', value: 'geoip:id' },
  { label: '🇺🇦 Ukraine', value: 'geoip:ua' },
  { label: '🇹🇷 Türkiye', value: 'geoip:tr' },
  { label: '🇧🇷 Brazil', value: 'geoip:br' },
];
const DOMAINS_OPTIONS = [
  { label: '🇮🇷 Iran', value: 'ext:geosite_IR.dat:ir' },
  { label: '🇮🇷 .ir', value: 'regexp:.*\\.ir$' },
  { label: '🇮🇷 .ایران', value: 'regexp:.*\\.xn--mgba3a4f16a$' },
  { label: '🇨🇳 China', value: 'geosite:cn' },
  { label: '🇨🇳 .cn', value: 'regexp:.*\\.cn$' },
  { label: '🇷🇺 Russia', value: 'ext:geosite_RU.dat:ru-available-only-inside' },
  { label: '🇷🇺 .ru', value: 'regexp:.*\\.ru$' },
  { label: '🇷🇺 .su', value: 'regexp:.*\\.su$' },
  { label: '🇷🇺 .рф', value: 'regexp:.*\\.xn--p1ai$' },
  { label: '🇻🇳 .vn', value: 'regexp:.*\\.vn$' },
];
const BLOCK_DOMAINS_OPTIONS = [
  { label: 'Ads All', value: 'geosite:category-ads-all' },
  { label: 'Ads IR 🇮🇷', value: 'ext:geosite_IR.dat:category-ads-all' },
  { label: 'Ads RU 🇷🇺', value: 'ext:geosite_RU.dat:category-ads-all' },
  { label: 'Malware 🇮🇷', value: 'ext:geosite_IR.dat:malware' },
  { label: 'Phishing 🇮🇷', value: 'ext:geosite_IR.dat:phishing' },
  { label: 'Cryptominers 🇮🇷', value: 'ext:geosite_IR.dat:cryptominers' },
  { label: 'Adult +18', value: 'geosite:category-porn' },
  { label: '🇮🇷 Iran', value: 'ext:geosite_IR.dat:ir' },
  { label: '🇮🇷 .ir', value: 'regexp:.*\\.ir$' },
  { label: '🇮🇷 .ایران', value: 'regexp:.*\\.xn--mgba3a4f16a$' },
  { label: '🇨🇳 China', value: 'geosite:cn' },
  { label: '🇨🇳 .cn', value: 'regexp:.*\\.cn$' },
  { label: '🇷🇺 Russia', value: 'ext:geosite_RU.dat:ru-available-only-inside' },
  { label: '🇷🇺 .ru', value: 'regexp:.*\\.ru$' },
  { label: '🇷🇺 .su', value: 'regexp:.*\\.su$' },
  { label: '🇷🇺 .рф', value: 'regexp:.*\\.xn--p1ai$' },
  { label: '🇻🇳 .vn', value: 'regexp:.*\\.vn$' },
];
const SERVICES_OPTIONS = [
  { label: 'Apple', value: 'geosite:apple' },
  { label: 'Meta', value: 'geosite:meta' },
  { label: 'Google', value: 'geosite:google' },
  { label: 'OpenAI', value: 'geosite:openai' },
  { label: 'Spotify', value: 'geosite:spotify' },
  { label: 'Netflix', value: 'geosite:netflix' },
  { label: 'Reddit', value: 'geosite:reddit' },
  { label: 'Speedtest', value: 'geosite:speedtest' },
];

const directSettings = { tag: 'direct', protocol: 'freedom' };
const ipv4Settings = { tag: 'IPv4', protocol: 'freedom', settings: { domainStrategy: 'UseIPv4' } };

function ruleGetter(t: XraySettingsValue | null, outboundTag: string, property: string): string[] {
  if (!t?.routing?.rules) return [];
  const out: string[] = [];
  for (const rule of t.routing.rules) {
    if (
      rule &&
      Object.prototype.hasOwnProperty.call(rule, property) &&
      Object.prototype.hasOwnProperty.call(rule, 'outboundTag') &&
      rule.outboundTag === outboundTag
    ) {
      const v = (rule as Record<string, unknown>)[property];
      if (Array.isArray(v)) out.push(...(v as string[]));
    }
  }
  return out;
}

function ruleSetter(t: XraySettingsValue, outboundTag: string, property: string, data: string[]): void {
  if (!t.routing) return;
  if (!Array.isArray(t.routing.rules)) t.routing.rules = [];
  const current = ruleGetter(t, outboundTag, property);
  if (current.length === 0) {
    t.routing.rules.push({ type: 'field', outboundTag, [property]: data });
    return;
  }
  const next: typeof t.routing.rules = [];
  let inserted = false;
  for (const rule of t.routing.rules) {
    const matches =
      rule &&
      Object.prototype.hasOwnProperty.call(rule, property) &&
      Object.prototype.hasOwnProperty.call(rule, 'outboundTag') &&
      rule.outboundTag === outboundTag;
    if (matches) {
      if (!inserted && data.length > 0) {
        (rule as Record<string, unknown>)[property] = data;
        next.push(rule);
        inserted = true;
      }
    } else {
      next.push(rule);
    }
  }
  t.routing.rules = next;
}

function syncOutbound(t: XraySettingsValue, tag: string, settings: Record<string, unknown>) {
  if (!t.outbounds || !t.routing) return;
  const rules = t.routing.rules || [];
  const haveRules = rules.some((r) => r?.outboundTag === tag);
  const idx = t.outbounds.findIndex((o) => o?.tag === tag);
  if (!haveRules && idx > 0) t.outbounds.splice(idx, 1);
  if (haveRules && idx < 0) t.outbounds.push(settings as never);
}

export default function BasicsTab({
  templateSettings,
  setTemplateSettings,
  outboundTestUrl,
  onChangeOutboundTestUrl,
  warpExist,
  nordExist,
  onShowWarp,
  onShowNord,
  onResetDefault,
}: BasicsTabProps) {
  const { t } = useTranslation();
  const [modal, modalContextHolder] = Modal.useModal();

  const mutate = useCallback(
    (mutator: (next: XraySettingsValue) => void) => {
      setTemplateSettings((prev) => {
        if (!prev) return prev;
        const clone = JSON.parse(JSON.stringify(prev)) as XraySettingsValue;
        mutator(clone);
        return clone;
      });
    },
    [setTemplateSettings],
  );

  function confirmResetDefault() {
    modal.confirm({
      title: t('pages.settings.resetDefaultConfig'),
      okText: t('reset'),
      okType: 'danger',
      cancelText: t('cancel'),
      onOk: () => onResetDefault(),
    });
  }

  const freedomStrategy =
    (templateSettings?.outbounds?.find((o) => o?.protocol === 'freedom' && o?.tag === 'direct')?.settings as
      | { domainStrategy?: string }
      | undefined)?.domainStrategy ?? 'AsIs';

  const routingStrategy = templateSettings?.routing?.domainStrategy ?? 'AsIs';
  const log = (templateSettings?.log || {}) as Record<string, unknown>;
  const policy = (templateSettings?.policy?.system || {}) as Record<string, boolean>;

  const blockedIPs = ruleGetter(templateSettings, 'blocked', 'ip');
  const blockedDomains = ruleGetter(templateSettings, 'blocked', 'domain');
  const blockedProtocols = ruleGetter(templateSettings, 'blocked', 'protocol');
  const directIPs = ruleGetter(templateSettings, 'direct', 'ip');
  const directDomains = ruleGetter(templateSettings, 'direct', 'domain');
  const ipv4Domains = ruleGetter(templateSettings, 'IPv4', 'domain');
  const warpDomains = ruleGetter(templateSettings, 'warp', 'domain');
  const nordTag =
    templateSettings?.outbounds?.find((o) => o?.tag?.startsWith?.('nord-'))?.tag || 'nord';
  const nordDomains = ruleGetter(templateSettings, nordTag, 'domain');

  const torrentActive = BITTORRENT_PROTOCOLS.every((p) => blockedProtocols.includes(p));

  const items = [
    {
      key: '1',
      label: t('pages.xray.generalConfigs'),
      children: (
        <>
          <Alert
            type="warning"
            showIcon
            className="mb-12 hint-alert"
            title={t('pages.xray.generalConfigsDesc')}
          />
          <SettingListItem
            title={t('pages.xray.FreedomStrategy')}
            description={t('pages.xray.FreedomStrategyDesc')}
            paddings="small"
            control={
              <Select
                value={freedomStrategy}
                style={{ width: '100%' }}
                options={OutboundDomainStrategies.map((s) => ({ value: s, label: s }))}
                onChange={(next) => mutate((tt) => {
                  if (!tt.outbounds) tt.outbounds = [];
                  const idx = tt.outbounds.findIndex((o) => o?.protocol === 'freedom' && o?.tag === 'direct');
                  if (idx < 0) {
                    tt.outbounds.push({ protocol: 'freedom', tag: 'direct', settings: { domainStrategy: next } });
                  } else {
                    const ob = tt.outbounds[idx];
                    ob.settings = (ob.settings || {}) as Record<string, unknown>;
                    (ob.settings as Record<string, unknown>).domainStrategy = next;
                  }
                })}
              />
            }
          />
          <SettingListItem
            title={t('pages.xray.RoutingStrategy')}
            description={t('pages.xray.RoutingStrategyDesc')}
            paddings="small"
            control={
              <Select
                value={routingStrategy}
                style={{ width: '100%' }}
                options={ROUTING_DOMAIN_STRATEGIES.map((s) => ({ value: s, label: s }))}
                onChange={(next) => mutate((tt) => {
                  if (tt.routing) tt.routing.domainStrategy = next;
                })}
              />
            }
          />
          <SettingListItem
            title={t('pages.xray.outboundTestUrl')}
            description={t('pages.xray.outboundTestUrlDesc')}
            paddings="small"
            control={
              <Input
                value={outboundTestUrl}
                onChange={(e) => onChangeOutboundTestUrl(e.target.value)}
                placeholder="https://www.google.com/generate_204"
              />
            }
          />
        </>
      ),
    },
    {
      key: '2',
      label: t('pages.xray.statistics'),
      children: (
        <>
          {[
            ['statsInboundUplink', t('pages.xray.statsInboundUplink')],
            ['statsInboundDownlink', t('pages.xray.statsInboundDownlink')],
            ['statsOutboundUplink', t('pages.xray.statsOutboundUplink')],
            ['statsOutboundDownlink', 'Outbound downlink stats'],
          ].map(([field, label]) => (
            <SettingListItem
              key={field}
              title={label}
              paddings="small"
              control={
                <Switch
                  checked={!!policy[field]}
                  onChange={(checked) => mutate((tt) => {
                    if (!tt.policy) tt.policy = {};
                    if (!tt.policy.system) tt.policy.system = {};
                    tt.policy.system[field] = checked;
                  })}
                />
              }
            />
          ))}
        </>
      ),
    },
    {
      key: '3',
      label: t('pages.xray.logConfigs'),
      children: (
        <>
          <Alert
            type="warning"
            showIcon
            className="mb-12 hint-alert"
            title={t('pages.xray.logConfigsDesc')}
          />
          <SettingListItem
            title={t('pages.xray.logLevel')}
            description={t('pages.xray.logLevelDesc')}
            paddings="small"
            control={
              <Select
                value={(log.loglevel as string) || 'warning'}
                style={{ width: '100%' }}
                options={LOG_LEVELS.map((s) => ({ value: s, label: s }))}
                onChange={(v) => mutate((tt) => { if (tt.log) tt.log.loglevel = v; })}
              />
            }
          />
          <SettingListItem
            title={t('pages.xray.accessLog')}
            description={t('pages.xray.accessLogDesc')}
            paddings="small"
            control={
              <Select
                value={(log.access as string) || ''}
                style={{ width: '100%' }}
                options={ACCESS_LOG.map((s) => ({ value: s, label: s }))}
                onChange={(v) => mutate((tt) => { if (tt.log) tt.log.access = v; })}
              />
            }
          />
          <SettingListItem
            title={t('pages.xray.errorLog')}
            description={t('pages.xray.errorLogDesc')}
            paddings="small"
            control={
              <Select
                value={(log.error as string) || ''}
                style={{ width: '100%' }}
                options={[{ value: '', label: t('empty') }, ...ERROR_LOG.map((s) => ({ value: s, label: s }))]}
                onChange={(v) => mutate((tt) => { if (tt.log) tt.log.error = v; })}
              />
            }
          />
          <SettingListItem
            title={t('pages.xray.maskAddress')}
            description={t('pages.xray.maskAddressDesc')}
            paddings="small"
            control={
              <Select
                value={(log.maskAddress as string) || ''}
                style={{ width: '100%' }}
                options={[{ value: '', label: t('empty') }, ...MASK_ADDRESS.map((s) => ({ value: s, label: s }))]}
                onChange={(v) => mutate((tt) => { if (tt.log) tt.log.maskAddress = v; })}
              />
            }
          />
          <SettingListItem
            title={t('pages.xray.dnsLog')}
            description={t('pages.xray.dnsLogDesc')}
            paddings="small"
            control={
              <Switch
                checked={!!log.dnsLog}
                onChange={(v) => mutate((tt) => { if (tt.log) tt.log.dnsLog = v; })}
              />
            }
          />
        </>
      ),
    },
    {
      key: '4',
      label: t('pages.xray.basicRouting'),
      children: (
        <>
          <Alert
            type="warning"
            showIcon
            className="mb-12 hint-alert"
            title={t('pages.xray.blockConnectionsConfigsDesc')}
          />

          <SettingListItem
            title={t('pages.xray.Torrent')}
            paddings="small"
            control={
              <Switch
                checked={torrentActive}
                onChange={(checked) => mutate((tt) => {
                  const next = checked
                    ? [...blockedProtocols, ...BITTORRENT_PROTOCOLS]
                    : blockedProtocols.filter((d) => !BITTORRENT_PROTOCOLS.includes(d));
                  ruleSetter(tt, 'blocked', 'protocol', next);
                })}
              />
            }
          />

          <SettingListItem
            title={t('pages.xray.blockips')}
            paddings="small"
            control={
              <Select
                mode="tags"
                value={blockedIPs}
                style={{ width: '100%' }}
                options={IPS_OPTIONS}
                onChange={(v) => mutate((tt) => ruleSetter(tt, 'blocked', 'ip', v))}
              />
            }
          />

          <SettingListItem
            title={t('pages.xray.blockdomains')}
            paddings="small"
            control={
              <Select
                mode="tags"
                value={blockedDomains}
                style={{ width: '100%' }}
                options={BLOCK_DOMAINS_OPTIONS}
                onChange={(v) => mutate((tt) => ruleSetter(tt, 'blocked', 'domain', v))}
              />
            }
          />

          <Alert
            type="warning"
            showIcon
            className="mb-12 hint-alert"
            title={t('pages.xray.directConnectionsConfigsDesc')}
          />

          <SettingListItem
            title={t('pages.xray.directips')}
            paddings="small"
            control={
              <Select
                mode="tags"
                value={directIPs}
                style={{ width: '100%' }}
                options={IPS_OPTIONS}
                onChange={(v) => mutate((tt) => {
                  ruleSetter(tt, 'direct', 'ip', v);
                  syncOutbound(tt, 'direct', directSettings);
                })}
              />
            }
          />

          <SettingListItem
            title={t('pages.xray.directdomains')}
            paddings="small"
            control={
              <Select
                mode="tags"
                value={directDomains}
                style={{ width: '100%' }}
                options={DOMAINS_OPTIONS}
                onChange={(v) => mutate((tt) => {
                  ruleSetter(tt, 'direct', 'domain', v);
                  syncOutbound(tt, 'direct', directSettings);
                })}
              />
            }
          />

          <SettingListItem
            title={t('pages.xray.ipv4Routing')}
            description={t('pages.xray.ipv4RoutingDesc')}
            paddings="small"
            control={
              <Select
                mode="tags"
                value={ipv4Domains}
                style={{ width: '100%' }}
                options={SERVICES_OPTIONS}
                onChange={(v) => mutate((tt) => {
                  ruleSetter(tt, 'IPv4', 'domain', v);
                  syncOutbound(tt, 'IPv4', ipv4Settings);
                })}
              />
            }
          />

          <SettingListItem
            title={t('pages.xray.warpRouting')}
            description={t('pages.xray.warpRoutingDesc')}
            paddings="small"
            control={
              warpExist ? (
                <Select
                  mode="tags"
                  value={warpDomains}
                  style={{ width: '100%' }}
                  options={SERVICES_OPTIONS}
                  onChange={(v) => mutate((tt) => ruleSetter(tt, 'warp', 'domain', v))}
                />
              ) : (
                <Button type="primary" onClick={onShowWarp} icon={<CloudOutlined />}>
                  WARP
                </Button>
              )
            }
          />

          <SettingListItem
            title={t('pages.xray.nordRouting')}
            description={t('pages.xray.nordRoutingDesc')}
            paddings="small"
            control={
              nordExist ? (
                <Select
                  mode="tags"
                  value={nordDomains}
                  style={{ width: '100%' }}
                  options={SERVICES_OPTIONS}
                  onChange={(v) => mutate((tt) => ruleSetter(tt, nordTag, 'domain', v))}
                />
              ) : (
                <Button type="primary" onClick={onShowNord} icon={<ApiOutlined />}>
                  NordVPN
                </Button>
              )
            }
          />
        </>
      ),
    },
    {
      key: 'reset',
      label: t('pages.settings.resetDefaultConfig'),
      children: (
        <Space style={{ padding: '0 20px' }}>
          <Button danger onClick={confirmResetDefault}>
            {t('pages.settings.resetDefaultConfig')}
          </Button>
        </Space>
      ),
    },
  ];

  return (
    <>
      {modalContextHolder}
      <Collapse defaultActiveKey={['1']} items={items} />
    </>
  );
}

// frontend/src/pages/xray/BasicsTab.vue
<script setup>
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';
import { ExclamationCircleFilled, CloudOutlined, ApiOutlined } from '@ant-design/icons-vue';
import { Modal } from 'ant-design-vue';

import { OutboundDomainStrategies } from '@/models/outbound.js';
import SettingListItem from '@/components/SettingListItem.vue';

const { t } = useI18n();

// Phase 6-ii: structured editor for the most-touched fields of the
// xray template — outbound strategy, routing strategy, log levels,
// stat counters, and the "basic routing" lists (block IPs/domains/
// torrent + direct IPs/domains + IPv4 forced + warp/nord domains).
//
// Mutates the parent's templateSettings reactive directly. The
// useXraySetting composable's deep watch on templateSettings re-
// stringifies into xraySetting so the Advanced JSON tab and the
// dirty-poll see every edit.

const props = defineProps({
  templateSettings: { type: Object, default: null },
  outboundTestUrl: { type: String, default: '' },
  warpExist: { type: Boolean, default: false },
  nordExist: { type: Boolean, default: false },
});

const emit = defineEmits(['update:outbound-test-url', 'show-warp', 'show-nord', 'reset-default']);

function confirmResetDefault() {
  Modal.confirm({
    title: t('pages.settings.resetDefaultConfig'),
    okText: t('reset'),
    okType: 'danger',
    cancelText: t('cancel'),
    onOk: () => { emit('reset-default'); },
  });
}

// === Static option lists (mirror legacy) =============================
const ROUTING_DOMAIN_STRATEGIES = ['AsIs', 'IPIfNonMatch', 'IPOnDemand'];
const LOG_LEVELS = ['none', 'debug', 'info', 'warning', 'error'];
const ACCESS_LOG = ['none', './access.log'];
const ERROR_LOG = ['none', './error.log'];
const MASK_ADDRESS = ['quarter', 'half', 'full'];
const BITTORRENT_PROTOCOLS = ['bittorrent'];

// Country / service lists mirror the legacy panel's settingsData
// (web/html/xray.html on main). Keep additions in sync with that file
// so Vue 3 + legacy stay swappable while the migration finishes.
const IPS_OPTIONS = [
  { label: 'Private IPs', value: 'geoip:private' },
  { label: '🇮🇷 Iran', value: 'ext:geoip_IR.dat:ir' },
  { label: '🇨🇳 China', value: 'geoip:cn' },
  { label: '🇷🇺 Russia', value: 'ext:geoip_RU.dat:ru' },
  { label: '🇻🇳 Vietnam', value: 'geoip:vn' },
  { label: '🇪🇸 Spain', value: 'geoip:es' },
  { label: '🇮🇩 Indonesia', value: 'geoip:id' },
  { label: '🇺🇦 Ukraine', value: 'geoip:ua' },
  { label: '🇹🇷 Türkiye', value: 'geoip:tr' },
  { label: '🇧🇷 Brazil', value: 'geoip:br' },
];
const DOMAINS_OPTIONS = [
  { label: '🇮🇷 Iran', value: 'ext:geosite_IR.dat:ir' },
  { label: '🇮🇷 .ir', value: 'regexp:.*\\.ir$' },
  { label: '🇮🇷 .ایران', value: 'regexp:.*\\.xn--mgba3a4f16a$' },
  { label: '🇨🇳 China', value: 'geosite:cn' },
  { label: '🇨🇳 .cn', value: 'regexp:.*\\.cn$' },
  { label: '🇷🇺 Russia', value: 'ext:geosite_RU.dat:ru-available-only-inside' },
  { label: '🇷🇺 .ru', value: 'regexp:.*\\.ru$' },
  { label: '🇷🇺 .su', value: 'regexp:.*\\.su$' },
  { label: '🇷🇺 .рф', value: 'regexp:.*\\.xn--p1ai$' },
  { label: '🇻🇳 .vn', value: 'regexp:.*\\.vn$' },
];
const BLOCK_DOMAINS_OPTIONS = [
  { label: 'Ads All', value: 'geosite:category-ads-all' },
  { label: 'Ads IR 🇮🇷', value: 'ext:geosite_IR.dat:category-ads-all' },
  { label: 'Ads RU 🇷🇺', value: 'ext:geosite_RU.dat:category-ads-all' },
  { label: 'Malware 🇮🇷', value: 'ext:geosite_IR.dat:malware' },
  { label: 'Phishing 🇮🇷', value: 'ext:geosite_IR.dat:phishing' },
  { label: 'Cryptominers 🇮🇷', value: 'ext:geosite_IR.dat:cryptominers' },
  { label: 'Adult +18', value: 'geosite:category-porn' },
  { label: '🇮🇷 Iran', value: 'ext:geosite_IR.dat:ir' },
  { label: '🇮🇷 .ir', value: 'regexp:.*\\.ir$' },
  { label: '🇮🇷 .ایران', value: 'regexp:.*\\.xn--mgba3a4f16a$' },
  { label: '🇨🇳 China', value: 'geosite:cn' },
  { label: '🇨🇳 .cn', value: 'regexp:.*\\.cn$' },
  { label: '🇷🇺 Russia', value: 'ext:geosite_RU.dat:ru-available-only-inside' },
  { label: '🇷🇺 .ru', value: 'regexp:.*\\.ru$' },
  { label: '🇷🇺 .su', value: 'regexp:.*\\.su$' },
  { label: '🇷🇺 .рф', value: 'regexp:.*\\.xn--p1ai$' },
  { label: '🇻🇳 .vn', value: 'regexp:.*\\.vn$' },
];
const SERVICES_OPTIONS = [
  { label: 'Apple', value: 'geosite:apple' },
  { label: 'Meta', value: 'geosite:meta' },
  { label: 'Google', value: 'geosite:google' },
  { label: 'OpenAI', value: 'geosite:openai' },
  { label: 'Spotify', value: 'geosite:spotify' },
  { label: 'Netflix', value: 'geosite:netflix' },
  { label: 'Reddit', value: 'geosite:reddit' },
  { label: 'Speedtest', value: 'geosite:speedtest' },
];

// === Routing-rule helpers (matches legacy templateRule{Getter,Setter}) ==
function ruleGetter(outboundTag, property) {
  if (!props.templateSettings?.routing?.rules) return [];
  const out = [];
  for (const rule of props.templateSettings.routing.rules) {
    if (
      rule
      && Object.prototype.hasOwnProperty.call(rule, property)
      && Object.prototype.hasOwnProperty.call(rule, 'outboundTag')
      && rule.outboundTag === outboundTag
    ) {
      out.push(...rule[property]);
    }
  }
  return out;
}
function ruleSetter(outboundTag, property, data) {
  if (!props.templateSettings?.routing) return;
  const current = ruleGetter(outboundTag, property);
  if (current.length === 0) {
    props.templateSettings.routing.rules.push({
      type: 'field',
      outboundTag,
      [property]: data,
    });
    return;
  }
  // Replace the property on the FIRST matching rule and drop any later
  // duplicates with the same (outboundTag, property) pair (matches the
  // legacy single-write-then-filter behavior).
  const next = [];
  let inserted = false;
  for (const rule of props.templateSettings.routing.rules) {
    const matches =
      rule
      && Object.prototype.hasOwnProperty.call(rule, property)
      && Object.prototype.hasOwnProperty.call(rule, 'outboundTag')
      && rule.outboundTag === outboundTag;
    if (matches) {
      if (!inserted && data.length > 0) {
        rule[property] = data;
        next.push(rule);
        inserted = true;
      }
    } else {
      next.push(rule);
    }
  }
  props.templateSettings.routing.rules = next;
}

function syncOutbound(tag, settings) {
  // After editing direct/IPv4/warp/nord rules, ensure the matching
  // outbound exists when the rule list has any entries, and is
  // pruned when none remain (legacy syncRulesWithOutbound).
  const t = props.templateSettings;
  if (!t) return;
  const haveRules = t.routing.rules.some((r) => r?.outboundTag === tag);
  const idx = t.outbounds.findIndex((o) => o.tag === tag);
  if (!haveRules && idx > 0) t.outbounds.splice(idx, 1);
  if (haveRules && idx < 0) t.outbounds.push(settings);
}

// === Computed v-models for every Basics field ========================
function rule(tag, property, syncFn) {
  return computed({
    get: () => ruleGetter(tag, property),
    set: (next) => { ruleSetter(tag, property, next); if (syncFn) syncFn(); },
  });
}

const directSettings = { tag: 'direct', protocol: 'freedom' };
const ipv4Settings = { tag: 'IPv4', protocol: 'freedom', settings: { domainStrategy: 'UseIPv4' } };

const freedomStrategy = computed({
  get: () => {
    const ob = props.templateSettings?.outbounds?.find(
      (o) => o.protocol === 'freedom' && o.tag === 'direct',
    );
    return ob?.settings?.domainStrategy ?? 'AsIs';
  },
  set: (next) => {
    const t = props.templateSettings;
    if (!t) return;
    const idx = t.outbounds.findIndex((o) => o.protocol === 'freedom' && o.tag === 'direct');
    if (idx < 0) {
      t.outbounds.push({ protocol: 'freedom', tag: 'direct', settings: { domainStrategy: next } });
    } else {
      t.outbounds[idx].settings = t.outbounds[idx].settings || {};
      t.outbounds[idx].settings.domainStrategy = next;
    }
  },
});

const routingStrategy = computed({
  get: () => props.templateSettings?.routing?.domainStrategy ?? 'AsIs',
  set: (next) => { if (props.templateSettings?.routing) props.templateSettings.routing.domainStrategy = next; },
});

function logField(field, fallback) {
  return computed({
    get: () => props.templateSettings?.log?.[field] ?? fallback,
    set: (next) => { if (props.templateSettings?.log) props.templateSettings.log[field] = next; },
  });
}
const logLevel = logField('loglevel', 'warning');
const accessLog = logField('access', '');
const errorLog = logField('error', '');
const maskAddressLog = logField('maskAddress', '');
const dnslog = logField('dnsLog', false);

function policyField(field) {
  return computed({
    get: () => !!props.templateSettings?.policy?.system?.[field],
    set: (next) => {
      if (!props.templateSettings?.policy?.system) return;
      props.templateSettings.policy.system[field] = next;
    },
  });
}
const statsInboundUplink = policyField('statsInboundUplink');
const statsInboundDownlink = policyField('statsInboundDownlink');
const statsOutboundUplink = policyField('statsOutboundUplink');
const statsOutboundDownlink = policyField('statsOutboundDownlink');

const blockedIPs = rule('blocked', 'ip');
const blockedDomains = rule('blocked', 'domain');
const blockedProtocols = rule('blocked', 'protocol');
const directIPs = rule('direct', 'ip', () => syncOutbound('direct', directSettings));
const directDomains = rule('direct', 'domain', () => syncOutbound('direct', directSettings));
const ipv4Domains = rule('IPv4', 'domain', () => syncOutbound('IPv4', ipv4Settings));
const warpDomains = rule('warp', 'domain');
const nordTag = computed(() => {
  const ob = props.templateSettings?.outbounds?.find((o) => o.tag?.startsWith?.('nord-'));
  return ob?.tag || 'nord';
});
const nordDomains = computed({
  get: () => ruleGetter(nordTag.value, 'domain'),
  set: (next) => ruleSetter(nordTag.value, 'domain', next),
});

const torrentSettings = computed({
  get: () => BITTORRENT_PROTOCOLS.every((p) => blockedProtocols.value.includes(p)),
  set: (next) => {
    if (next) {
      blockedProtocols.value = [...blockedProtocols.value, ...BITTORRENT_PROTOCOLS];
    } else {
      blockedProtocols.value = blockedProtocols.value.filter((d) => !BITTORRENT_PROTOCOLS.includes(d));
    }
  },
});

const localOutboundTestUrl = computed({
  get: () => props.outboundTestUrl,
  set: (next) => emit('update:outbound-test-url', next),
});
</script>

<template>
  <a-collapse default-active-key="1">
    <a-collapse-panel key="1" :header="t('pages.xray.generalConfigs')">
      <a-alert type="warning" class="mb-12 hint-alert" :message="t('pages.xray.generalConfigsDesc')">
        <template #icon>
          <ExclamationCircleFilled style="color: #FFA031;" />
        </template>
      </a-alert>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.FreedomStrategy') }}</template>
        <template #description>{{ t('pages.xray.FreedomStrategyDesc') }}</template>
        <template #control>
          <a-select v-model:value="freedomStrategy" :style="{ width: '100%' }">
            <a-select-option v-for="s in OutboundDomainStrategies" :key="s" :value="s">{{ s }}</a-select-option>
          </a-select>
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.RoutingStrategy') }}</template>
        <template #description>{{ t('pages.xray.RoutingStrategyDesc') }}</template>
        <template #control>
          <a-select v-model:value="routingStrategy" :style="{ width: '100%' }">
            <a-select-option v-for="s in ROUTING_DOMAIN_STRATEGIES" :key="s" :value="s">{{ s }}</a-select-option>
          </a-select>
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.outboundTestUrl') }}</template>
        <template #description>{{ t('pages.xray.outboundTestUrlDesc') }}</template>
        <template #control>
          <a-input v-model:value="localOutboundTestUrl" placeholder="https://www.google.com/generate_204" />
        </template>
      </SettingListItem>
    </a-collapse-panel>

    <a-collapse-panel key="2" :header="t('pages.xray.statistics')">
      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.statsInboundUplink') }}</template>
        <template #control><a-switch v-model:checked="statsInboundUplink" /></template>
      </SettingListItem>
      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.statsInboundDownlink') }}</template>
        <template #control><a-switch v-model:checked="statsInboundDownlink" /></template>
      </SettingListItem>
      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.statsOutboundUplink') }}</template>
        <template #control><a-switch v-model:checked="statsOutboundUplink" /></template>
      </SettingListItem>
      <SettingListItem paddings="small">
        <template #title>Outbound downlink stats</template>
        <template #control><a-switch v-model:checked="statsOutboundDownlink" /></template>
      </SettingListItem>
    </a-collapse-panel>

    <a-collapse-panel key="3" :header="t('pages.xray.logConfigs')">
      <a-alert type="warning" class="mb-12 hint-alert" :message="t('pages.xray.logConfigsDesc')">
        <template #icon>
          <ExclamationCircleFilled style="color: #FFA031;" />
        </template>
      </a-alert>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.logLevel') }}</template>
        <template #description>{{ t('pages.xray.logLevelDesc') }}</template>
        <template #control>
          <a-select v-model:value="logLevel" :style="{ width: '100%' }">
            <a-select-option v-for="s in LOG_LEVELS" :key="s" :value="s">{{ s }}</a-select-option>
          </a-select>
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.accessLog') }}</template>
        <template #description>{{ t('pages.xray.accessLogDesc') }}</template>
        <template #control>
          <a-select v-model:value="accessLog" :style="{ width: '100%' }">
            <a-select-option v-for="s in ACCESS_LOG" :key="s" :value="s">{{ s }}</a-select-option>
          </a-select>
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.errorLog') }}</template>
        <template #description>{{ t('pages.xray.errorLogDesc') }}</template>
        <template #control>
          <a-select v-model:value="errorLog" :style="{ width: '100%' }">
            <a-select-option value="">{{ t('empty') }}</a-select-option>
            <a-select-option v-for="s in ERROR_LOG" :key="s" :value="s">{{ s }}</a-select-option>
          </a-select>
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.maskAddress') }}</template>
        <template #description>{{ t('pages.xray.maskAddressDesc') }}</template>
        <template #control>
          <a-select v-model:value="maskAddressLog" :style="{ width: '100%' }">
            <a-select-option value="">{{ t('empty') }}</a-select-option>
            <a-select-option v-for="s in MASK_ADDRESS" :key="s" :value="s">{{ s }}</a-select-option>
          </a-select>
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.dnsLog') }}</template>
        <template #description>{{ t('pages.xray.dnsLogDesc') }}</template>
        <template #control><a-switch v-model:checked="dnslog" /></template>
      </SettingListItem>
    </a-collapse-panel>

    <a-collapse-panel key="4" :header="t('pages.xray.basicRouting')">
      <a-alert type="warning" class="mb-12 hint-alert" :message="t('pages.xray.blockConnectionsConfigsDesc')">
        <template #icon>
          <ExclamationCircleFilled style="color: #FFA031;" />
        </template>
      </a-alert>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.Torrent') }}</template>
        <template #control><a-switch v-model:checked="torrentSettings" /></template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.blockips') }}</template>
        <template #control>
          <a-select v-model:value="blockedIPs" mode="tags" :style="{ width: '100%' }">
            <a-select-option v-for="p in IPS_OPTIONS" :key="p.value" :value="p.value" :label="p.label">{{ p.label
            }}</a-select-option>
          </a-select>
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.blockdomains') }}</template>
        <template #control>
          <a-select v-model:value="blockedDomains" mode="tags" :style="{ width: '100%' }">
            <a-select-option v-for="p in BLOCK_DOMAINS_OPTIONS" :key="p.value" :value="p.value" :label="p.label">{{
              p.label }}</a-select-option>
          </a-select>
        </template>
      </SettingListItem>

      <a-alert type="warning" class="mb-12 hint-alert" :message="t('pages.xray.directConnectionsConfigsDesc')">
        <template #icon>
          <ExclamationCircleFilled style="color: #FFA031;" />
        </template>
      </a-alert>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.directips') }}</template>
        <template #control>
          <a-select v-model:value="directIPs" mode="tags" :style="{ width: '100%' }">
            <a-select-option v-for="p in IPS_OPTIONS" :key="p.value" :value="p.value" :label="p.label">{{ p.label
            }}</a-select-option>
          </a-select>
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.directdomains') }}</template>
        <template #control>
          <a-select v-model:value="directDomains" mode="tags" :style="{ width: '100%' }">
            <a-select-option v-for="p in DOMAINS_OPTIONS" :key="p.value" :value="p.value" :label="p.label">{{ p.label
            }}</a-select-option>
          </a-select>
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.ipv4Routing') }}</template>
        <template #description>{{ t('pages.xray.ipv4RoutingDesc') }}</template>
        <template #control>
          <a-select v-model:value="ipv4Domains" mode="tags" :style="{ width: '100%' }">
            <a-select-option v-for="p in SERVICES_OPTIONS" :key="p.value" :value="p.value" :label="p.label">{{ p.label
            }}</a-select-option>
          </a-select>
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.warpRouting') }}</template>
        <template #description>{{ t('pages.xray.warpRoutingDesc') }}</template>
        <template #control>
          <a-select v-if="warpExist" v-model:value="warpDomains" mode="tags" :style="{ width: '100%' }">
            <a-select-option v-for="p in SERVICES_OPTIONS" :key="p.value" :value="p.value" :label="p.label">{{ p.label
            }}</a-select-option>
          </a-select>
          <a-button v-else type="primary" @click="emit('show-warp')">
            <template #icon>
              <CloudOutlined />
            </template>
            WARP
          </a-button>
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.xray.nordRouting') }}</template>
        <template #description>{{ t('pages.xray.nordRoutingDesc') }}</template>
        <template #control>
          <a-select v-if="nordExist" v-model:value="nordDomains" mode="tags" :style="{ width: '100%' }">
            <a-select-option v-for="p in SERVICES_OPTIONS" :key="p.value" :value="p.value" :label="p.label">{{ p.label
            }}</a-select-option>
          </a-select>
          <a-button v-else type="primary" @click="emit('show-nord')">
            <template #icon>
              <ApiOutlined />
            </template>
            NordVPN
          </a-button>
        </template>
      </SettingListItem>
    </a-collapse-panel>

    <a-collapse-panel key="reset" :header="t('pages.settings.resetDefaultConfig')">
      <a-space direction="horizontal" :style="{ padding: '0 20px' }">
        <a-button danger @click="confirmResetDefault">
          {{ t('pages.settings.resetDefaultConfig') }}
        </a-button>
      </a-space>
    </a-collapse-panel>
  </a-collapse>
</template>

<style scoped>
.mb-12 {
  margin-bottom: 12px;
}

.hint-alert {
  text-align: center;
}
</style>
