// frontend/src/pages/xray/dns/DnsServerModal.tsx
import { useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { Button, Divider, Form, Input, InputNumber, Modal, Select, Space, Switch } from 'antd';
import { MinusOutlined, PlusOutlined } from '@ant-design/icons';

import { InputAddon } from '@/components/ui';
import {
  DnsQueryStrategySchema,
  DnsServerObjectInnerSchema,
  DnsServerObjectSchema,
  type DnsServerObject,
} from '@/schemas/dns';
import { antdRule } from '@/utils/zodForm';

export type DnsServerValue =
  | string
  | (DnsServerObject & {
      expectIPs?: string[];
      [key: string]: unknown;
    });

interface DnsServerModalProps {
  open: boolean;
  server: DnsServerValue | null;
  isEdit: boolean;
  onClose: () => void;
  onConfirm: (value: DnsServerValue) => void;
}

const STRATEGIES = DnsQueryStrategySchema.options;

type DnsServerForm = {
  address: string;
  port: number;
  domains: string[];
  expectedIPs: string[];
  unexpectedIPs: string[];
  queryStrategy: string;
  skipFallback: boolean;
  disableCache: boolean;
  finalQuery: boolean;
  tag: string;
  clientIP: string;
  serveStale: boolean;
  serveExpiredTTL: number;
  timeoutMs: number;
};

function defaultFormValues(): DnsServerForm {
  return {
    address: 'localhost',
    port: 53,
    domains: [],
    expectedIPs: [],
    unexpectedIPs: [],
    queryStrategy: 'UseIP',
    skipFallback: false,
    disableCache: false,
    finalQuery: false,
    tag: '',
    clientIP: '',
    serveStale: false,
    serveExpiredTTL: 0,
    timeoutMs: 4000,
  };
}

function valuesFromServer(server: DnsServerValue | null): DnsServerForm {
  if (server == null) return defaultFormValues();
  if (typeof server === 'string') return { ...defaultFormValues(), address: server };
  const parsed = DnsServerObjectSchema.safeParse(server);
  const data = parsed.success ? parsed.data : null;
  return {
    ...defaultFormValues(),
    ...(data ?? {}),
    address: (data?.address ?? server.address) || 'localhost',
    domains: data?.domains ?? server.domains ?? [],
    expectedIPs: data?.expectedIPs ?? server.expectedIPs ?? server.expectIPs ?? [],
    unexpectedIPs: data?.unexpectedIPs ?? server.unexpectedIPs ?? [],
    queryStrategy: data?.queryStrategy ?? server.queryStrategy ?? 'UseIP',
    skipFallback: data?.skipFallback ?? server.skipFallback ?? false,
    disableCache: data?.disableCache ?? server.disableCache ?? false,
    finalQuery: data?.finalQuery ?? server.finalQuery ?? false,
    tag: data?.tag ?? server.tag ?? '',
    clientIP: data?.clientIP ?? server.clientIP ?? '',
    serveStale: data?.serveStale ?? server.serveStale ?? false,
    serveExpiredTTL: data?.serveExpiredTTL ?? server.serveExpiredTTL ?? 0,
    timeoutMs: data?.timeoutMs ?? server.timeoutMs ?? 4000,
  };
}

function valuesToWire(values: DnsServerForm): DnsServerValue {
  const isPlain
    = values.domains.length === 0
    && values.expectedIPs.length === 0
    && values.unexpectedIPs.length === 0
    && values.port === 53
    && values.queryStrategy === 'UseIP'
    && values.skipFallback === false
    && values.disableCache === false
    && values.finalQuery === false
    && !values.tag
    && !values.clientIP
    && values.serveStale === false
    && values.serveExpiredTTL === 0
    && values.timeoutMs === 4000;
  if (isPlain) return values.address;

  const out: Record<string, unknown> = {
    address: values.address,
    port: values.port,
    domains: values.domains.filter(Boolean),
    expectedIPs: values.expectedIPs.filter(Boolean),
    unexpectedIPs: values.unexpectedIPs.filter(Boolean),
    queryStrategy: values.queryStrategy,
    skipFallback: values.skipFallback,
    disableCache: values.disableCache,
    finalQuery: values.finalQuery,
    serveStale: values.serveStale,
    serveExpiredTTL: values.serveExpiredTTL,
    timeoutMs: values.timeoutMs,
  };
  if (values.tag) out.tag = values.tag;
  if (values.clientIP) out.clientIP = values.clientIP;
  return out as DnsServerValue;
}

const shape = DnsServerObjectInnerSchema.shape;

export default function DnsServerModal({
  open,
  server,
  isEdit,
  onClose,
  onConfirm,
}: DnsServerModalProps) {
  const { t } = useTranslation();
  const [form] = Form.useForm<DnsServerForm>();

  useEffect(() => {
    if (!open) return;
    form.setFieldsValue(valuesFromServer(server));
  }, [open, server, form]);

  async function submit() {
    const values = await form.validateFields();
    onConfirm(valuesToWire(values));
  }

  const title = isEdit ? t('pages.xray.dns.edit') : t('pages.xray.dns.add');

  return (
    <Modal
      open={open}
      title={title}
      okText={t('confirm')}
      cancelText={t('close')}
      mask={{ closable: false }}
      onOk={submit}
      onCancel={onClose}
    >
      <Form
        form={form}
        colon={false}
        labelCol={{ md: { span: 8 } }}
        wrapperCol={{ md: { span: 14 } }}
        initialValues={defaultFormValues()}
      >
        <Form.Item
          label={t('pages.inbounds.address')}
          name="address"
          rules={[antdRule(shape.address, t)]}
        >
          <Input />
        </Form.Item>
        <Form.Item
          label={t('pages.inbounds.port')}
          name="port"
          rules={[antdRule(shape.port, t)]}
        >
          <InputNumber min={1} max={65535} />
        </Form.Item>
        <Form.Item label={t('pages.xray.dns.tag')} name="tag">
          <Input />
        </Form.Item>
        <Form.Item label={t('pages.xray.dns.clientIp')} name="clientIP">
          <Input />
        </Form.Item>
        <Form.Item label={t('pages.xray.dns.strategy')} name="queryStrategy">
          <Select
            style={{ width: '100%' }}
            options={STRATEGIES.map((s) => ({ value: s, label: s }))}
          />
        </Form.Item>
        <Form.Item
          label={t('pages.xray.dns.timeoutMs')}
          name="timeoutMs"
          rules={[antdRule(shape.timeoutMs, t)]}
        >
          <InputNumber min={0} step={500} />
        </Form.Item>

        <Divider style={{ margin: '5px 0' }} />

        <Form.List name="domains">
          {(fields, { add, remove }) => (
            <Form.Item label={t('pages.xray.dns.domains')}>
              <Button size="small" type="primary" icon={<PlusOutlined />} onClick={() => add('')} />
              {fields.map((field) => (
                <Space.Compact key={field.key} block style={{ marginTop: 4 }}>
                  <Form.Item name={field.name} noStyle>
                    <Input />
                  </Form.Item>
                  <InputAddon onClick={() => remove(field.name)}>
                    <MinusOutlined />
                  </InputAddon>
                </Space.Compact>
              ))}
            </Form.Item>
          )}
        </Form.List>

        <Form.List name="expectedIPs">
          {(fields, { add, remove }) => (
            <Form.Item label={t('pages.xray.dns.expectIPs')}>
              <Button size="small" type="primary" icon={<PlusOutlined />} onClick={() => add('')} />
              {fields.map((field) => (
                <Space.Compact key={field.key} block style={{ marginTop: 4 }}>
                  <Form.Item name={field.name} noStyle>
                    <Input />
                  </Form.Item>
                  <InputAddon onClick={() => remove(field.name)}>
                    <MinusOutlined />
                  </InputAddon>
                </Space.Compact>
              ))}
            </Form.Item>
          )}
        </Form.List>

        <Form.List name="unexpectedIPs">
          {(fields, { add, remove }) => (
            <Form.Item label={t('pages.xray.dns.unexpectIPs')}>
              <Button size="small" type="primary" icon={<PlusOutlined />} onClick={() => add('')} />
              {fields.map((field) => (
                <Space.Compact key={field.key} block style={{ marginTop: 4 }}>
                  <Form.Item name={field.name} noStyle>
                    <Input />
                  </Form.Item>
                  <InputAddon onClick={() => remove(field.name)}>
                    <MinusOutlined />
                  </InputAddon>
                </Space.Compact>
              ))}
            </Form.Item>
          )}
        </Form.List>

        <Divider style={{ margin: '5px 0' }} />

        <Form.Item label={t('pages.xray.dns.skipFallback')} name="skipFallback" valuePropName="checked">
          <Switch />
        </Form.Item>
        <Form.Item label={t('pages.xray.dns.finalQuery')} name="finalQuery" valuePropName="checked">
          <Switch />
        </Form.Item>
        <Form.Item label={t('pages.xray.dns.disableCache')} name="disableCache" valuePropName="checked">
          <Switch />
        </Form.Item>
        <Form.Item label={t('pages.xray.dns.serveStale')} name="serveStale" valuePropName="checked">
          <Switch />
        </Form.Item>
        <Form.Item label={t('pages.xray.dns.serveExpiredTTL')} name="serveExpiredTTL">
          <InputNumber min={0} step={60} />
        </Form.Item>
      </Form>
    </Modal>
  );
}

// frontend/src/pages/xray/DnsServerModal.vue
<script setup>
import { computed, reactive, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { PlusOutlined, MinusOutlined } from '@ant-design/icons-vue';

const { t } = useI18n();

const props = defineProps({
  open: { type: Boolean, default: false },
  server: { type: [Object, String, null], default: null },
  isEdit: { type: Boolean, default: false },
});

const emit = defineEmits(['update:open', 'confirm']);

const DEFAULT_SERVER = () => ({
  address: 'localhost',
  port: 53,
  domains: [],
  expectedIPs: [],
  unexpectedIPs: [],
  queryStrategy: 'UseIP',
  skipFallback: false,
  disableCache: false,
  finalQuery: false,
  tag: '',
  clientIP: '',
  serveStale: false,
  serveExpiredTTL: 0,
  timeoutMs: 4000,
});

const STRATEGIES = ['UseSystem', 'UseIP', 'UseIPv4', 'UseIPv6'];

const form = reactive(DEFAULT_SERVER());

watch(() => props.open, (next) => {
  if (!next) return;
  Object.assign(form, DEFAULT_SERVER());
  if (props.server == null) return;
  if (typeof props.server === 'string') {
    form.address = props.server;
    return;
  }
  const incoming = props.server;
  Object.assign(form, {
    ...DEFAULT_SERVER(),
    ...incoming,
    domains: [...(incoming.domains || [])],
    expectedIPs: [...(incoming.expectedIPs || incoming.expectIPs || [])],
    unexpectedIPs: [...(incoming.unexpectedIPs || [])],
  });
});

function close() { emit('update:open', false); }

function onOk() {
  const isPlain = form.domains.length === 0
    && form.expectedIPs.length === 0
    && form.unexpectedIPs.length === 0
    && form.port === 53
    && form.queryStrategy === 'UseIP'
    && form.skipFallback === false
    && form.disableCache === false
    && form.finalQuery === false
    && !form.tag
    && !form.clientIP
    && form.serveStale === false
    && form.serveExpiredTTL === 0
    && form.timeoutMs === 4000;
  if (isPlain) {
    emit('confirm', form.address);
    return;
  }
  const out = {
    address: form.address,
    port: form.port,
    domains: [...form.domains].filter(Boolean),
    expectedIPs: [...form.expectedIPs].filter(Boolean),
    unexpectedIPs: [...form.unexpectedIPs].filter(Boolean),
    queryStrategy: form.queryStrategy,
    skipFallback: form.skipFallback,
    disableCache: form.disableCache,
    finalQuery: form.finalQuery,
    serveStale: form.serveStale,
    serveExpiredTTL: form.serveExpiredTTL,
    timeoutMs: form.timeoutMs,
  };
  if (form.tag) out.tag = form.tag;
  if (form.clientIP) out.clientIP = form.clientIP;
  emit('confirm', out);
}

const title = computed(() =>
  props.isEdit ? t('pages.xray.dns.edit') : t('pages.xray.dns.add'),
);
</script>

<template>
  <a-modal :open="open" :title="title" :ok-text="t('confirm')" :cancel-text="t('close')" :mask-closable="false"
    @ok="onOk" @cancel="close">
    <a-form :colon="false" :label-col="{ md: { span: 8 } }" :wrapper-col="{ md: { span: 14 } }">
      <a-form-item :label="t('pages.inbounds.address')">
        <a-input v-model:value="form.address" />
      </a-form-item>
      <a-form-item :label="t('pages.inbounds.port')">
        <a-input-number v-model:value="form.port" :min="1" :max="65535" />
      </a-form-item>
      <a-form-item :label="t('pages.xray.dns.tag')">
        <a-input v-model:value="form.tag" />
      </a-form-item>
      <a-form-item :label="t('pages.xray.dns.clientIp')">
        <a-input v-model:value="form.clientIP" />
      </a-form-item>
      <a-form-item :label="t('pages.xray.dns.strategy')">
        <a-select v-model:value="form.queryStrategy" :style="{ width: '100%' }">
          <a-select-option v-for="s in STRATEGIES" :key="s" :value="s">{{ s }}</a-select-option>
        </a-select>
      </a-form-item>
      <a-form-item :label="t('pages.xray.dns.timeoutMs')">
        <a-input-number v-model:value="form.timeoutMs" :min="0" :step="500" />
      </a-form-item>

      <a-divider :style="{ margin: '5px 0' }" />

      <a-form-item :label="t('pages.xray.dns.domains')">
        <a-button size="small" type="primary" @click="form.domains.push('')">
          <template #icon>
            <PlusOutlined />
          </template>
        </a-button>
        <template v-for="(_, idx) in form.domains" :key="`d${idx}`">
          <a-input v-model:value="form.domains[idx]" :style="{ marginTop: '4px' }">
            <template #addonAfter>
              <MinusOutlined @click="form.domains.splice(idx, 1)" />
            </template>
          </a-input>
        </template>
      </a-form-item>

      <a-form-item :label="t('pages.xray.dns.expectIPs')">
        <a-button size="small" type="primary" @click="form.expectedIPs.push('')">
          <template #icon>
            <PlusOutlined />
          </template>
        </a-button>
        <template v-for="(_, idx) in form.expectedIPs" :key="`e${idx}`">
          <a-input v-model:value="form.expectedIPs[idx]" :style="{ marginTop: '4px' }">
            <template #addonAfter>
              <MinusOutlined @click="form.expectedIPs.splice(idx, 1)" />
            </template>
          </a-input>
        </template>
      </a-form-item>

      <a-form-item :label="t('pages.xray.dns.unexpectIPs')">
        <a-button size="small" type="primary" @click="form.unexpectedIPs.push('')">
          <template #icon>
            <PlusOutlined />
          </template>
        </a-button>
        <template v-for="(_, idx) in form.unexpectedIPs" :key="`u${idx}`">
          <a-input v-model:value="form.unexpectedIPs[idx]" :style="{ marginTop: '4px' }">
            <template #addonAfter>
              <MinusOutlined @click="form.unexpectedIPs.splice(idx, 1)" />
            </template>
          </a-input>
        </template>
      </a-form-item>

      <a-divider :style="{ margin: '5px 0' }" />

      <a-form-item :label="t('pages.xray.dns.skipFallback')">
        <a-switch v-model:checked="form.skipFallback" />
      </a-form-item>
      <a-form-item :label="t('pages.xray.dns.finalQuery')">
        <a-switch v-model:checked="form.finalQuery" />
      </a-form-item>
      <a-form-item :label="t('pages.xray.dns.disableCache')">
        <a-switch v-model:checked="form.disableCache" />
      </a-form-item>
      <a-form-item :label="t('pages.xray.dns.serveStale')">
        <a-switch v-model:checked="form.serveStale" />
      </a-form-item>
      <a-form-item :label="t('pages.xray.dns.serveExpiredTTL')">
        <a-input-number v-model:value="form.serveExpiredTTL" :min="0" :step="60" />
      </a-form-item>
    </a-form>
  </a-modal>
</template>
