// frontend/src/components/TextModal.vue
<script setup>
import { CopyOutlined, DownloadOutlined } from '@ant-design/icons-vue';
import { message } from 'ant-design-vue';

import { ClipboardManager, FileManager } from '@/utils';

// Read-only text modal — used to surface multi-line export blobs
// (subscription URLs, raw inbound JSON, generated share links) the
// way the legacy txtModal did.

defineProps({
  open: { type: Boolean, default: false },
  title: { type: String, default: '' },
  content: { type: String, default: '' },
  // When set, surfaces a download button that writes `content` to a
  // text file with this name.
  fileName: { type: String, default: '' },
});

const emit = defineEmits(['update:open']);

function close() {
  emit('update:open', false);
}

async function copy(value) {
  const ok = await ClipboardManager.copyText(value || '');
  if (ok) {
    message.success('Copied');
    close();
  }
}

function download(content, name) {
  if (!name) return;
  FileManager.downloadTextFile(content, name);
}
</script>

<template>
  <a-modal :open="open" :title="title" :closable="true" @cancel="close">
    <a-textarea
      :value="content"
      readonly
      :auto-size="{ minRows: 10, maxRows: 20 }"
      class="text-modal-content"
    />
    <template #footer>
      <a-button v-if="fileName" @click="download(content, fileName)">
        <template #icon><DownloadOutlined /></template>
        {{ fileName }}
      </a-button>
      <a-button type="primary" @click="copy(content)">
        <template #icon><CopyOutlined /></template>
        Copy
      </a-button>
    </template>
  </a-modal>
</template>

<style scoped>
.text-modal-content {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  font-size: 12px;
  overflow-y: auto;
}
</style>

// frontend/src/components/feedback/TextModal.tsx
import { Button, Input, Modal, message } from 'antd';
import { CopyOutlined, DownloadOutlined } from '@ant-design/icons';
import { useTranslation } from 'react-i18next';

import JsonEditor from '@/components/form/JsonEditor';
import { ClipboardManager, FileManager } from '@/utils';

interface TextModalProps {
  open: boolean;
  onClose: () => void;
  title: string;
  content: string;
  fileName?: string;
  json?: boolean;
}

export default function TextModal({ open, onClose, title, content, fileName = '', json = false }: TextModalProps) {
  const { t } = useTranslation();
  const [messageApi, messageContextHolder] = message.useMessage();
  async function copy() {
    const ok = await ClipboardManager.copyText(content || '');
    if (ok) {
      messageApi.success(t('copied'));
      onClose();
    }
  }

  function download() {
    if (!fileName) return;
    FileManager.downloadTextFile(content, fileName);
  }

  return (
    <>
      {messageContextHolder}
      <Modal
        open={open}
        title={title}
        onCancel={onClose}
        destroyOnHidden
      footer={(
        <>
          {fileName && (
            <Button icon={<DownloadOutlined />} onClick={download}>{fileName}</Button>
          )}
          <Button type="primary" icon={<CopyOutlined />} onClick={copy}>{t('copy')}</Button>
        </>
      )}
    >
      {json ? (
        <JsonEditor value={content} readOnly minHeight="240px" maxHeight="60vh" />
      ) : (
        <Input.TextArea
          value={content}
          readOnly
          autoSize={{ minRows: 10, maxRows: 20 }}
          style={{
            fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
            fontSize: 12,
            overflowY: 'auto',
          }}
        />
      )}
      </Modal>
    </>
  );
}
