// frontend/src/pages/settings/SubscriptionFormatsTab.tsx
import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import {
  Button,
  Collapse,
  Input,
  InputNumber,
  Select,
  Space,
  Switch,
} from 'antd';
import type { AllSetting } from '@/models/setting';
import SettingListItem from '@/components/SettingListItem';
import './SubscriptionFormatsTab.css';

interface SubscriptionFormatsTabProps {
  allSetting: AllSetting;
  updateSetting: (patch: Partial<AllSetting>) => void;
}

const DEFAULT_FRAGMENT = {
  packets: 'tlshello',
  length: '100-200',
  interval: '10-20',
  maxSplit: '300-400',
};
const DEFAULT_NOISES: { type: string; packet: string; delay: string; applyTo: string }[] = [
  { type: 'rand', packet: '10-20', delay: '10-16', applyTo: 'ip' },
];
const DEFAULT_MUX = {
  enabled: true,
  concurrency: 8,
  xudpConcurrency: 16,
  xudpProxyUDP443: 'reject',
};
const DEFAULT_RULES: { type: string; outboundTag: string; domain?: string[]; ip?: string[] }[] = [
  { type: 'field', outboundTag: 'direct', domain: ['geosite:category-ir'] },
  { type: 'field', outboundTag: 'direct', ip: ['geoip:private', 'geoip:ir'] },
];

const directIPsOptions = [
  { label: 'Private IP', value: 'geoip:private' },
  { label: '🇮🇷 Iran', value: 'geoip:ir' },
  { label: '🇨🇳 China', value: 'geoip:cn' },
  { label: '🇷🇺 Russia', value: 'geoip:ru' },
  { label: '🇻🇳 Vietnam', value: 'geoip:vn' },
  { label: '🇪🇸 Spain', value: 'geoip:es' },
  { label: '🇮🇩 Indonesia', value: 'geoip:id' },
  { label: '🇺🇦 Ukraine', value: 'geoip:ua' },
  { label: '🇹🇷 Türkiye', value: 'geoip:tr' },
  { label: '🇧🇷 Brazil', value: 'geoip:br' },
];
const directDomainsOptions = [
  { label: 'Private DNS', value: 'geosite:private' },
  { label: '🇮🇷 Iran', value: 'geosite:category-ir' },
  { label: '🇨🇳 China', value: 'geosite:cn' },
  { label: '🇷🇺 Russia', value: 'geosite:category-ru' },
  { label: 'Apple', value: 'geosite:apple' },
  { label: 'Meta', value: 'geosite:meta' },
  { label: 'Google', value: 'geosite:google' },
];

function sanitizePath(input: string): string {
  return String(input ?? '').replace(/[:*]/g, '');
}

function normalizePath(input: string): string {
  let p = input || '/';
  if (!p.startsWith('/')) p = '/' + p;
  if (!p.endsWith('/')) p += '/';
  p = p.replace(/\/+/g, '/');
  return p;
}

function readJson<T>(raw: string, fallback: T): T {
  try {
    if (!raw) return fallback;
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}

export default function SubscriptionFormatsTab({ allSetting, updateSetting }: SubscriptionFormatsTabProps) {
  const { t } = useTranslation();

  const fragment = allSetting.subJsonFragment !== '';
  const noisesEnabled = allSetting.subJsonNoises !== '';
  const muxEnabled = allSetting.subJsonMux !== '';
  const directEnabled = allSetting.subJsonRules !== '';

  const fragmentObj = useMemo(
    () => (fragment ? readJson<typeof DEFAULT_FRAGMENT>(allSetting.subJsonFragment, DEFAULT_FRAGMENT) : DEFAULT_FRAGMENT),
    [allSetting.subJsonFragment, fragment],
  );

  function setFragmentEnabled(v: boolean) {
    updateSetting({ subJsonFragment: v ? JSON.stringify(DEFAULT_FRAGMENT) : '' });
  }

  function setFragmentField<K extends keyof typeof DEFAULT_FRAGMENT>(key: K, value: string) {
    if (value === '') return;
    const next = { ...fragmentObj, [key]: value };
    updateSetting({ subJsonFragment: JSON.stringify(next) });
  }

  const noisesArray = useMemo(
    () => (noisesEnabled ? readJson<typeof DEFAULT_NOISES>(allSetting.subJsonNoises, DEFAULT_NOISES) : []),
    [allSetting.subJsonNoises, noisesEnabled],
  );

  function setNoisesEnabled(v: boolean) {
    updateSetting({ subJsonNoises: v ? JSON.stringify(DEFAULT_NOISES) : '' });
  }

  function setNoisesArray(next: typeof DEFAULT_NOISES) {
    if (noisesEnabled) updateSetting({ subJsonNoises: JSON.stringify(next) });
  }

  function addNoise() {
    setNoisesArray([...noisesArray, { ...DEFAULT_NOISES[0] }]);
  }

  function removeNoise(index: number) {
    const next = [...noisesArray];
    next.splice(index, 1);
    setNoisesArray(next);
  }

  function updateNoiseField(index: number, field: keyof typeof DEFAULT_NOISES[number], value: string) {
    const next = [...noisesArray];
    next[index] = { ...next[index], [field]: value };
    setNoisesArray(next);
  }

  const muxObj = useMemo(
    () => (muxEnabled ? readJson<typeof DEFAULT_MUX>(allSetting.subJsonMux, DEFAULT_MUX) : DEFAULT_MUX),
    [allSetting.subJsonMux, muxEnabled],
  );

  function setMuxEnabled(v: boolean) {
    updateSetting({ subJsonMux: v ? JSON.stringify(DEFAULT_MUX) : '' });
  }

  function setMuxField<K extends keyof typeof DEFAULT_MUX>(key: K, value: typeof DEFAULT_MUX[K]) {
    const next = { ...muxObj, [key]: value };
    updateSetting({ subJsonMux: JSON.stringify(next) });
  }

  const ruleArray = useMemo(() => {
    if (!directEnabled) return null;
    return readJson<typeof DEFAULT_RULES | null>(allSetting.subJsonRules, null);
  }, [allSetting.subJsonRules, directEnabled]);

  const directIPs = useMemo(() => {
    if (!ruleArray) return [];
    const ipRule = ruleArray.find((r) => r.ip);
    return ipRule?.ip ?? [];
  }, [ruleArray]);

  const directDomains = useMemo(() => {
    if (!ruleArray) return [];
    const dRule = ruleArray.find((r) => r.domain);
    return dRule?.domain ?? [];
  }, [ruleArray]);

  function setDirectEnabled(v: boolean) {
    updateSetting({ subJsonRules: v ? JSON.stringify(DEFAULT_RULES) : '' });
  }

  function setDirectIPs(value: string[]) {
    if (!ruleArray) return;
    let rules = [...ruleArray];
    if (value.length === 0) {
      rules = rules.filter((r) => !r.ip);
    } else {
      let idx = rules.findIndex((r) => r.ip);
      if (idx === -1) {
        rules.push({ ...DEFAULT_RULES[1] });
        idx = rules.length - 1;
      }
      rules[idx] = { ...rules[idx], ip: [...value] };
    }
    updateSetting({ subJsonRules: JSON.stringify(rules) });
  }

  function setDirectDomains(value: string[]) {
    if (!ruleArray) return;
    let rules = [...ruleArray];
    if (value.length === 0) {
      rules = rules.filter((r) => !r.domain);
    } else {
      let idx = rules.findIndex((r) => r.domain);
      if (idx === -1) {
        rules.push({ ...DEFAULT_RULES[0] });
        idx = rules.length - 1;
      }
      rules[idx] = { ...rules[idx], domain: [...value] };
    }
    updateSetting({ subJsonRules: JSON.stringify(rules) });
  }

  return (
    <Collapse defaultActiveKey="1" items={[
      {
        key: '1',
        label: t('pages.settings.panelSettings'),
        children: (
          <>
            {allSetting.subJsonEnable && (
              <>
                <SettingListItem paddings="small" title={<>JSON {t('pages.settings.subPath')}</>} description={t('pages.settings.subPathDesc')}>
                  <Input
                    value={allSetting.subJsonPath}
                    placeholder="/json/"
                    onChange={(e) => updateSetting({ subJsonPath: sanitizePath(e.target.value) })}
                    onBlur={() => updateSetting({ subJsonPath: normalizePath(allSetting.subJsonPath) })}
                  />
                </SettingListItem>
                <SettingListItem paddings="small" title={<>JSON {t('pages.settings.subURI')}</>} description={t('pages.settings.subURIDesc')}>
                  <Input
                    value={allSetting.subJsonURI}
                    placeholder="(http|https)://domain[:port]/path/"
                    onChange={(e) => updateSetting({ subJsonURI: e.target.value })}
                  />
                </SettingListItem>
              </>
            )}
            {allSetting.subClashEnable && (
              <>
                <SettingListItem paddings="small" title={<>Clash {t('pages.settings.subPath')}</>} description={t('pages.settings.subPathDesc')}>
                  <Input
                    value={allSetting.subClashPath}
                    placeholder="/clash/"
                    onChange={(e) => updateSetting({ subClashPath: sanitizePath(e.target.value) })}
                    onBlur={() => updateSetting({ subClashPath: normalizePath(allSetting.subClashPath) })}
                  />
                </SettingListItem>
                <SettingListItem paddings="small" title={<>Clash {t('pages.settings.subURI')}</>} description={t('pages.settings.subURIDesc')}>
                  <Input
                    value={allSetting.subClashURI}
                    placeholder="(http|https)://domain[:port]/path/"
                    onChange={(e) => updateSetting({ subClashURI: e.target.value })}
                  />
                </SettingListItem>
              </>
            )}
          </>
        ),
      },
      {
        key: '2',
        label: t('pages.settings.fragment'),
        children: (
          <>
            <SettingListItem paddings="small" title={t('pages.settings.fragment')} description={t('pages.settings.fragmentDesc')}>
              <Switch checked={fragment} onChange={setFragmentEnabled} />
            </SettingListItem>
            {fragment && (
              <div className="nested-block">
                <Collapse items={[
                  {
                    key: 'sett',
                    label: t('pages.settings.fragmentSett'),
                    children: (
                      <>
                        <SettingListItem paddings="small" title="Packets">
                          <Input value={fragmentObj.packets} placeholder="1-1 | 1-3 | tlshello | …"
                            onChange={(e) => setFragmentField('packets', e.target.value)} />
                        </SettingListItem>
                        <SettingListItem paddings="small" title="Length">
                          <Input value={fragmentObj.length} placeholder="100-200"
                            onChange={(e) => setFragmentField('length', e.target.value)} />
                        </SettingListItem>
                        <SettingListItem paddings="small" title="Interval">
                          <Input value={fragmentObj.interval} placeholder="10-20"
                            onChange={(e) => setFragmentField('interval', e.target.value)} />
                        </SettingListItem>
                        <SettingListItem paddings="small" title="Max split">
                          <Input value={fragmentObj.maxSplit} placeholder="300-400"
                            onChange={(e) => setFragmentField('maxSplit', e.target.value)} />
                        </SettingListItem>
                      </>
                    ),
                  },
                ]} />
              </div>
            )}
          </>
        ),
      },
      {
        key: '3',
        label: 'Noises',
        children: (
          <>
            <SettingListItem paddings="small" title="Noises" description={t('pages.settings.noisesDesc')}>
              <Switch checked={noisesEnabled} onChange={setNoisesEnabled} />
            </SettingListItem>
            {noisesEnabled && (
              <div className="nested-block">
                <Collapse items={noisesArray.map((noise, index) => ({
                  key: String(index),
                  label: `Noise №${index + 1}`,
                  children: (
                    <>
                      <SettingListItem paddings="small" title="Type">
                        <Select
                          value={noise.type}
                          style={{ width: '100%' }}
                          onChange={(v) => updateNoiseField(index, 'type', v)}
                          options={['rand', 'base64', 'str', 'hex'].map((p) => ({ value: p, label: p }))}
                        />
                      </SettingListItem>
                      <SettingListItem paddings="small" title="Packet">
                        <Input value={noise.packet} placeholder="5-10"
                          onChange={(e) => updateNoiseField(index, 'packet', e.target.value)} />
                      </SettingListItem>
                      <SettingListItem paddings="small" title="Delay (ms)">
                        <Input value={noise.delay} placeholder="10-20"
                          onChange={(e) => updateNoiseField(index, 'delay', e.target.value)} />
                      </SettingListItem>
                      <SettingListItem paddings="small" title="Apply to">
                        <Select
                          value={noise.applyTo}
                          style={{ width: '100%' }}
                          onChange={(v) => updateNoiseField(index, 'applyTo', v)}
                          options={['ip', 'ipv4', 'ipv6'].map((p) => ({ value: p, label: p }))}
                        />
                      </SettingListItem>
                      <Space style={{ padding: '10px 20px' }}>
                        {noisesArray.length > 1 && (
                          <Button type="primary" danger onClick={() => removeNoise(index)}>
                            {t('delete')}
                          </Button>
                        )}
                      </Space>
                    </>
                  ),
                }))} />
                <Button type="primary" style={{ marginTop: 10 }} onClick={addNoise}>+ Noise</Button>
              </div>
            )}
          </>
        ),
      },
      {
        key: '4',
        label: t('pages.settings.mux'),
        children: (
          <>
            <SettingListItem paddings="small" title={t('pages.settings.mux')} description={t('pages.settings.muxDesc')}>
              <Switch checked={muxEnabled} onChange={setMuxEnabled} />
            </SettingListItem>
            {muxEnabled && (
              <div className="nested-block">
                <Collapse items={[
                  {
                    key: 'sett',
                    label: t('pages.settings.muxSett'),
                    children: (
                      <>
                        <SettingListItem paddings="small" title="Concurrency">
                          <InputNumber value={muxObj.concurrency} min={-1} max={1024} style={{ width: '100%' }}
                            onChange={(v) => setMuxField('concurrency', Number(v) || 0)} />
                        </SettingListItem>
                        <SettingListItem paddings="small" title="xudp concurrency">
                          <InputNumber value={muxObj.xudpConcurrency} min={-1} max={1024} style={{ width: '100%' }}
                            onChange={(v) => setMuxField('xudpConcurrency', Number(v) || 0)} />
                        </SettingListItem>
                        <SettingListItem paddings="small" title="xudp UDP 443">
                          <Select
                            value={muxObj.xudpProxyUDP443}
                            style={{ width: '100%' }}
                            onChange={(v) => setMuxField('xudpProxyUDP443', v)}
                            options={['reject', 'allow', 'skip'].map((p) => ({ value: p, label: p }))}
                          />
                        </SettingListItem>
                      </>
                    ),
                  },
                ]} />
              </div>
            )}
          </>
        ),
      },
      {
        key: '5',
        label: t('pages.settings.direct'),
        children: (
          <>
            <SettingListItem paddings="small" title={t('pages.settings.direct')} description={t('pages.settings.directDesc')}>
              <Switch checked={directEnabled} onChange={setDirectEnabled} />
            </SettingListItem>
            {directEnabled && (
              <div className="nested-block">
                <Collapse items={[
                  {
                    key: 'rules',
                    label: t('pages.settings.direct'),
                    children: (
                      <>
                        <SettingListItem paddings="small" title={<>{t('pages.settings.direct')} IPs</>}>
                          <Select
                            mode="tags"
                            value={directIPs}
                            style={{ width: '100%' }}
                            onChange={setDirectIPs}
                            options={directIPsOptions}
                          />
                        </SettingListItem>
                        <SettingListItem paddings="small" title={<>{t('pages.settings.direct')} {t('domainName')}</>}>
                          <Select
                            mode="tags"
                            value={directDomains}
                            style={{ width: '100%' }}
                            onChange={setDirectDomains}
                            options={directDomainsOptions}
                          />
                        </SettingListItem>
                      </>
                    ),
                  },
                ]} />
              </div>
            )}
          </>
        ),
      },
    ]} />
  );
}

// frontend/src/pages/settings/SubscriptionFormatsTab.vue
<script setup>
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';
import SettingListItem from '@/components/SettingListItem.vue';

const { t } = useI18n();

const props = defineProps({
  allSetting: { type: Object, required: true },
});

// === Defaults (match legacy) ============================================
const DEFAULT_FRAGMENT = {
  packets: 'tlshello',
  length: '100-200',
  interval: '10-20',
  maxSplit: '300-400',
};
const DEFAULT_NOISES = [{ type: 'rand', packet: '10-20', delay: '10-16', applyTo: 'ip' }];
const DEFAULT_MUX = {
  enabled: true,
  concurrency: 8,
  xudpConcurrency: 16,
  xudpProxyUDP443: 'reject',
};
const DEFAULT_RULES = [
  { type: 'field', outboundTag: 'direct', domain: ['geosite:category-ir'] },
  { type: 'field', outboundTag: 'direct', ip: ['geoip:private', 'geoip:ir'] },
];

const directIPsOptions = [
  { label: 'Private IP', value: 'geoip:private' },
  { label: '🇮🇷 Iran', value: 'geoip:ir' },
  { label: '🇨🇳 China', value: 'geoip:cn' },
  { label: '🇷🇺 Russia', value: 'geoip:ru' },
  { label: '🇻🇳 Vietnam', value: 'geoip:vn' },
  { label: '🇪🇸 Spain', value: 'geoip:es' },
  { label: '🇮🇩 Indonesia', value: 'geoip:id' },
  { label: '🇺🇦 Ukraine', value: 'geoip:ua' },
  { label: '🇹🇷 Türkiye', value: 'geoip:tr' },
  { label: '🇧🇷 Brazil', value: 'geoip:br' },
];
const directDomainsOptions = [
  { label: 'Private DNS', value: 'geosite:private' },
  { label: '🇮🇷 Iran', value: 'geosite:category-ir' },
  { label: '🇨🇳 China', value: 'geosite:cn' },
  { label: '🇷🇺 Russia', value: 'geosite:category-ru' },
  { label: 'Apple', value: 'geosite:apple' },
  { label: 'Meta', value: 'geosite:meta' },
  { label: 'Google', value: 'geosite:google' },
];

// === Path helpers (json + clash share the same shape) ===================
function makePath(field) {
  return computed({
    get: () => props.allSetting[field],
    set: (v) => {
      props.allSetting[field] = String(v ?? '').replace(/[:*]/g, '');
    },
  });
}
function normalizePath(field) {
  let p = props.allSetting[field] || '/';
  if (!p.startsWith('/')) p = '/' + p;
  if (!p.endsWith('/')) p += '/';
  p = p.replace(/\/+/g, '/');
  props.allSetting[field] = p;
}
const subJsonPath = makePath('subJsonPath');
const subClashPath = makePath('subClashPath');

// === Fragment ===========================================================
// `subJsonFragment` is a JSON-encoded object when enabled, "" when off.
function readJson(field, fallback) {
  try {
    const raw = props.allSetting[field];
    if (!raw) return fallback;
    return JSON.parse(raw);
  } catch (_e) {
    return fallback;
  }
}
function writeJson(field, value) {
  props.allSetting[field] = JSON.stringify(value);
}

const fragment = computed({
  get: () => props.allSetting.subJsonFragment !== '',
  set: (v) => {
    props.allSetting.subJsonFragment = v ? JSON.stringify(DEFAULT_FRAGMENT) : '';
  },
});
function makeFragmentField(key) {
  return computed({
    get: () => (fragment.value ? readJson('subJsonFragment', DEFAULT_FRAGMENT)[key] : ''),
    set: (v) => {
      if (v === '') return;
      const f = readJson('subJsonFragment', { ...DEFAULT_FRAGMENT });
      f[key] = v;
      writeJson('subJsonFragment', f);
    },
  });
}
const fragmentPackets = makeFragmentField('packets');
const fragmentLength = makeFragmentField('length');
const fragmentInterval = makeFragmentField('interval');
const fragmentMaxSplit = makeFragmentField('maxSplit');

// === Noises =============================================================
const noises = computed({
  get: () => props.allSetting.subJsonNoises !== '',
  set: (v) => {
    props.allSetting.subJsonNoises = v ? JSON.stringify(DEFAULT_NOISES) : '';
  },
});
const noisesArray = computed({
  get: () => (noises.value ? readJson('subJsonNoises', DEFAULT_NOISES) : []),
  set: (value) => { if (noises.value) writeJson('subJsonNoises', value); },
});
function addNoise() {
  noisesArray.value = [...noisesArray.value, { ...DEFAULT_NOISES[0] }];
}
function removeNoise(index) {
  const next = [...noisesArray.value];
  next.splice(index, 1);
  noisesArray.value = next;
}
function updateNoiseField(index, field, value) {
  const next = [...noisesArray.value];
  next[index] = { ...next[index], [field]: value };
  noisesArray.value = next;
}

// === Mux ================================================================
const enableMux = computed({
  get: () => props.allSetting.subJsonMux !== '',
  set: (v) => {
    props.allSetting.subJsonMux = v ? JSON.stringify(DEFAULT_MUX) : '';
  },
});
function makeMuxField(key, fallback) {
  return computed({
    get: () => (enableMux.value ? readJson('subJsonMux', DEFAULT_MUX)[key] : fallback),
    set: (v) => {
      const m = readJson('subJsonMux', { ...DEFAULT_MUX });
      m[key] = v;
      writeJson('subJsonMux', m);
    },
  });
}
const muxConcurrency = makeMuxField('concurrency', -1);
const muxXudpConcurrency = makeMuxField('xudpConcurrency', -1);
const muxXudpProxyUDP443 = makeMuxField('xudpProxyUDP443', 'reject');

// === Direct routing rules ==============================================
// `subJsonRules` is a JSON array of xray routing rules. We surface the
// IP and domain fields of the two seed rules as multi-select tags.
const enableDirect = computed({
  get: () => props.allSetting.subJsonRules !== '',
  set: (v) => {
    props.allSetting.subJsonRules = v ? JSON.stringify(DEFAULT_RULES) : '';
  },
});
function ruleArray() {
  if (!enableDirect.value) return null;
  const rules = readJson('subJsonRules', null);
  return Array.isArray(rules) ? rules : null;
}
const directIPs = computed({
  get: () => {
    const rules = ruleArray();
    if (!rules) return [];
    const ipRule = rules.find((r) => r.ip);
    return ipRule?.ip ?? [];
  },
  set: (value) => {
    let rules = ruleArray();
    if (!rules) return;
    if (value.length === 0) {
      rules = rules.filter((r) => !r.ip);
    } else {
      let idx = rules.findIndex((r) => r.ip);
      if (idx === -1) idx = rules.push({ ...DEFAULT_RULES[1] }) - 1;
      rules[idx].ip = [...value];
    }
    writeJson('subJsonRules', rules);
  },
});
const directDomains = computed({
  get: () => {
    const rules = ruleArray();
    if (!rules) return [];
    const dRule = rules.find((r) => r.domain);
    return dRule?.domain ?? [];
  },
  set: (value) => {
    let rules = ruleArray();
    if (!rules) return;
    if (value.length === 0) {
      rules = rules.filter((r) => !r.domain);
    } else {
      let idx = rules.findIndex((r) => r.domain);
      if (idx === -1) idx = rules.push({ ...DEFAULT_RULES[0] }) - 1;
      rules[idx].domain = [...value];
    }
    writeJson('subJsonRules', rules);
  },
});
</script>

<template>
  <a-collapse default-active-key="1">
    <a-collapse-panel key="1" :header="t('pages.settings.panelSettings')">
      <SettingListItem v-if="allSetting.subJsonEnable" paddings="small">
        <template #title>JSON {{ t('pages.settings.subPath') }}</template>
        <template #description>{{ t('pages.settings.subPathDesc') }}</template>
        <template #control>
          <a-input v-model:value="subJsonPath" type="text" placeholder="/json/" @blur="normalizePath('subJsonPath')" />
        </template>
      </SettingListItem>

      <SettingListItem v-if="allSetting.subJsonEnable" paddings="small">
        <template #title>JSON {{ t('pages.settings.subURI') }}</template>
        <template #description>{{ t('pages.settings.subURIDesc') }}</template>
        <template #control>
          <a-input v-model:value="allSetting.subJsonURI" type="text" placeholder="(http|https)://domain[:port]/path/" />
        </template>
      </SettingListItem>

      <SettingListItem v-if="allSetting.subClashEnable" paddings="small">
        <template #title>Clash {{ t('pages.settings.subPath') }}</template>
        <template #description>{{ t('pages.settings.subPathDesc') }}</template>
        <template #control>
          <a-input v-model:value="subClashPath" type="text" placeholder="/clash/"
            @blur="normalizePath('subClashPath')" />
        </template>
      </SettingListItem>

      <SettingListItem v-if="allSetting.subClashEnable" paddings="small">
        <template #title>Clash {{ t('pages.settings.subURI') }}</template>
        <template #description>{{ t('pages.settings.subURIDesc') }}</template>
        <template #control>
          <a-input v-model:value="allSetting.subClashURI" type="text"
            placeholder="(http|https)://domain[:port]/path/" />
        </template>
      </SettingListItem>
    </a-collapse-panel>

    <a-collapse-panel key="2" :header="t('pages.settings.fragment')">
      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.fragment') }}</template>
        <template #description>{{ t('pages.settings.fragmentDesc') }}</template>
        <template #control>
          <a-switch v-model:checked="fragment" />
        </template>
      </SettingListItem>

      <a-list-item v-if="fragment" class="nested-block">
        <a-collapse>
          <a-collapse-panel :header="t('pages.settings.fragmentSett')">
            <SettingListItem paddings="small">
              <template #title>Packets</template>
              <template #control>
                <a-input v-model:value="fragmentPackets" placeholder="1-1 | 1-3 | tlshello | …" />
              </template>
            </SettingListItem>
            <SettingListItem paddings="small">
              <template #title>Length</template>
              <template #control>
                <a-input v-model:value="fragmentLength" placeholder="100-200" />
              </template>
            </SettingListItem>
            <SettingListItem paddings="small">
              <template #title>Interval</template>
              <template #control>
                <a-input v-model:value="fragmentInterval" placeholder="10-20" />
              </template>
            </SettingListItem>
            <SettingListItem paddings="small">
              <template #title>Max split</template>
              <template #control>
                <a-input v-model:value="fragmentMaxSplit" placeholder="300-400" />
              </template>
            </SettingListItem>
          </a-collapse-panel>
        </a-collapse>
      </a-list-item>
    </a-collapse-panel>

    <a-collapse-panel key="3" header="Noises">
      <SettingListItem paddings="small">
        <template #title>Noises</template>
        <template #description>{{ t('pages.settings.noisesDesc') }}</template>
        <template #control>
          <a-switch v-model:checked="noises" />
        </template>
      </SettingListItem>

      <a-list-item v-if="noises" class="nested-block">
        <a-collapse>
          <a-collapse-panel v-for="(noise, index) in noisesArray" :key="index" :header="`Noise №${index + 1}`">
            <SettingListItem paddings="small">
              <template #title>Type</template>
              <template #control>
                <a-select :value="noise.type" :style="{ width: '100%' }"
                  @change="(v) => updateNoiseField(index, 'type', v)">
                  <a-select-option v-for="p in ['rand', 'base64', 'str', 'hex']" :key="p" :value="p">
                    {{ p }}
                  </a-select-option>
                </a-select>
              </template>
            </SettingListItem>
            <SettingListItem paddings="small">
              <template #title>Packet</template>
              <template #control>
                <a-input :value="noise.packet" placeholder="5-10"
                  @input="(e) => updateNoiseField(index, 'packet', e.target.value)" />
              </template>
            </SettingListItem>
            <SettingListItem paddings="small">
              <template #title>Delay (ms)</template>
              <template #control>
                <a-input :value="noise.delay" placeholder="10-20"
                  @input="(e) => updateNoiseField(index, 'delay', e.target.value)" />
              </template>
            </SettingListItem>
            <SettingListItem paddings="small">
              <template #title>Apply to</template>
              <template #control>
                <a-select :value="noise.applyTo" :style="{ width: '100%' }"
                  @change="(v) => updateNoiseField(index, 'applyTo', v)">
                  <a-select-option v-for="p in ['ip', 'ipv4', 'ipv6']" :key="p" :value="p">
                    {{ p }}
                  </a-select-option>
                </a-select>
              </template>
            </SettingListItem>

            <a-space direction="horizontal" :style="{ padding: '10px 20px' }">
              <a-button v-if="noisesArray.length > 1" type="primary" danger @click="removeNoise(index)">
                {{ t('delete') }}
              </a-button>
            </a-space>
          </a-collapse-panel>
        </a-collapse>

        <a-button type="primary" :style="{ marginTop: '10px' }" @click="addNoise">+ Noise</a-button>
      </a-list-item>
    </a-collapse-panel>

    <a-collapse-panel key="4" :header="t('pages.settings.mux')">
      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.mux') }}</template>
        <template #description>{{ t('pages.settings.muxDesc') }}</template>
        <template #control>
          <a-switch v-model:checked="enableMux" />
        </template>
      </SettingListItem>

      <a-list-item v-if="enableMux" class="nested-block">
        <a-collapse>
          <a-collapse-panel :header="t('pages.settings.muxSett')">
            <SettingListItem paddings="small">
              <template #title>Concurrency</template>
              <template #control>
                <a-input-number v-model:value="muxConcurrency" :min="-1" :max="1024" :style="{ width: '100%' }" />
              </template>
            </SettingListItem>
            <SettingListItem paddings="small">
              <template #title>xudp concurrency</template>
              <template #control>
                <a-input-number v-model:value="muxXudpConcurrency" :min="-1" :max="1024" :style="{ width: '100%' }" />
              </template>
            </SettingListItem>
            <SettingListItem paddings="small">
              <template #title>xudp UDP 443</template>
              <template #control>
                <a-select v-model:value="muxXudpProxyUDP443" :style="{ width: '100%' }">
                  <a-select-option v-for="p in ['reject', 'allow', 'skip']" :key="p" :value="p">
                    {{ p }}
                  </a-select-option>
                </a-select>
              </template>
            </SettingListItem>
          </a-collapse-panel>
        </a-collapse>
      </a-list-item>
    </a-collapse-panel>

    <a-collapse-panel key="5" :header="t('pages.settings.direct')">
      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.direct') }}</template>
        <template #description>{{ t('pages.settings.directDesc') }}</template>
        <template #control>
          <a-switch v-model:checked="enableDirect" />
        </template>
      </SettingListItem>

      <a-list-item v-if="enableDirect" class="nested-block">
        <a-collapse>
          <a-collapse-panel :header="t('pages.settings.direct')">
            <SettingListItem paddings="small">
              <template #title>{{ t('pages.settings.direct') }} IPs</template>
              <template #control>
                <a-select v-model:value="directIPs" mode="tags" :style="{ width: '100%' }">
                  <a-select-option v-for="p in directIPsOptions" :key="p.value" :value="p.value" :label="p.label">
                    {{ p.label }}
                  </a-select-option>
                </a-select>
              </template>
            </SettingListItem>
            <SettingListItem paddings="small">
              <template #title>{{ t('pages.settings.direct') }} {{ t('domainName') }}</template>
              <template #control>
                <a-select v-model:value="directDomains" mode="tags" :style="{ width: '100%' }">
                  <a-select-option v-for="p in directDomainsOptions" :key="p.value" :value="p.value" :label="p.label">
                    {{ p.label }}
                  </a-select-option>
                </a-select>
              </template>
            </SettingListItem>
          </a-collapse-panel>
        </a-collapse>
      </a-list-item>
    </a-collapse-panel>
  </a-collapse>
</template>

<style scoped>
.nested-block {
  padding: 10px 20px;
}
</style>
