// frontend/src/pages/index/BackupModal.vue
<script setup>
import { useI18n } from 'vue-i18n';
import { DownloadOutlined, UploadOutlined } from '@ant-design/icons-vue';
import { HttpUtil, PromiseUtil } from '@/utils';

const { t } = useI18n();

defineProps({
  open: { type: Boolean, default: false },
  basePath: { type: String, default: '' },
});

const emit = defineEmits(['update:open', 'busy']);

function close() {
  emit('update:open', false);
}

function exportDb() {
  // The Go endpoint streams x-ui.db as a download. Setting
  // window.location triggers a browser download without leaving
  // the page (the Go side responds with Content-Disposition: attachment).
  window.location = window.X_UI_BASE_PATH+'panel/api/server/getDb';
}

function importDb() {
  const fileInput = document.createElement('input');
  fileInput.type = 'file';
  fileInput.accept = '.db';
  fileInput.addEventListener('change', async (e) => {
    const dbFile = e.target.files?.[0];
    if (!dbFile) return;

    const formData = new FormData();
    formData.append('db', dbFile);

    close();
    emit('busy', { busy: true, tip: t('pages.index.importDatabase') + '…' });

    const upload = await HttpUtil.post('/panel/api/server/importDB', formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    });
    if (!upload?.success) {
      emit('busy', { busy: false });
      return;
    }

    emit('busy', { busy: true, tip: t('pages.settings.restartPanel') + '…' });
    const restart = await HttpUtil.post('/panel/setting/restartPanel');
    if (restart?.success) {
      await PromiseUtil.sleep(5000);
      window.location.reload();
    } else {
      emit('busy', { busy: false });
    }
  });
  fileInput.click();
}
</script>

<template>
  <a-modal :open="open" :title="t('pages.index.backupTitle')" :closable="true" :footer="null" @cancel="close">
    <a-list bordered class="backup-list">
      <a-list-item class="backup-item">
        <a-list-item-meta>
          <template #title>{{ t('pages.index.exportDatabase') }}</template>
          <template #description>{{ t('pages.index.exportDatabaseDesc') }}</template>
        </a-list-item-meta>
        <a-button type="primary" @click="exportDb">
          <template #icon>
            <DownloadOutlined />
          </template>
        </a-button>
      </a-list-item>

      <a-list-item class="backup-item">
        <a-list-item-meta>
          <template #title>{{ t('pages.index.importDatabase') }}</template>
          <template #description>{{ t('pages.index.importDatabaseDesc') }}</template>
        </a-list-item-meta>
        <a-button type="primary" @click="importDb">
          <template #icon>
            <UploadOutlined />
          </template>
        </a-button>
      </a-list-item>
    </a-list>
  </a-modal>
</template>

<style scoped>
.backup-list {
  width: 100%;
}

.backup-item {
  display: flex;
  align-items: center;
  gap: 16px;
}
</style>

// frontend/src/pages/index/BackupModal.tsx
import { useTranslation } from 'react-i18next';
import { Button, Modal } from 'antd';
import { DownloadOutlined, UploadOutlined } from '@ant-design/icons';

import { HttpUtil, PromiseUtil } from '@/utils';
import './BackupModal.css';

interface BusyEvent {
  busy: boolean;
  tip?: string;
}

interface BackupModalProps {
  open: boolean;
  basePath: string;
  onClose: () => void;
  onBusy: (e: BusyEvent) => void;
}

export default function BackupModal({ open, basePath: _basePath, onClose, onBusy }: BackupModalProps) {
  const { t } = useTranslation();
  const isPostgres = window.X_UI_DB_TYPE === 'postgres';

  function exportDb() {
    window.location.href = (window.X_UI_BASE_PATH || '') + 'panel/api/server/getDb';
  }

  function exportMigration() {
    window.location.href = (window.X_UI_BASE_PATH || '') + 'panel/api/server/getMigration';
  }

  function importDb() {
    const fileInput = document.createElement('input');
    fileInput.type = 'file';
    fileInput.accept = isPostgres ? '.dump' : '.db';
    fileInput.addEventListener('change', async (e) => {
      const dbFile = (e.target as HTMLInputElement).files?.[0];
      if (!dbFile) return;

      const formData = new FormData();
      formData.append('db', dbFile);

      onClose();
      onBusy({ busy: true, tip: `${t('pages.index.importDatabase')}…` });

      const upload = await HttpUtil.post('/panel/api/server/importDB', formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });
      if (!upload?.success) {
        onBusy({ busy: false });
        return;
      }

      onBusy({ busy: true, tip: `${t('pages.settings.restartPanel')}…` });
      const restart = await HttpUtil.post('/panel/api/setting/restartPanel');
      if (restart?.success) {
        await PromiseUtil.sleep(5000);
        window.location.reload();
      } else {
        onBusy({ busy: false });
      }
    });
    fileInput.click();
  }

  return (
    <Modal
      open={open}
      title={t('pages.index.backupTitle')}
      footer={null}
      onCancel={onClose}
    >
      {isPostgres && (
        <div className="backup-description" style={{ marginBottom: 16 }}>
          {t('pages.index.backupPostgresNote')}
        </div>
      )}
      <div className="backup-list">
        <div className="backup-item">
          <div className="backup-meta">
            <div className="backup-title">{t('pages.index.exportDatabase')}</div>
            <div className="backup-description">
              {isPostgres ? t('pages.index.exportDatabasePgDesc') : t('pages.index.exportDatabaseDesc')}
            </div>
          </div>
          <Button type="primary" onClick={exportDb} icon={<DownloadOutlined />} />
        </div>

        <div className="backup-item">
          <div className="backup-meta">
            <div className="backup-title">{t('pages.index.migrationDownload')}</div>
            <div className="backup-description">
              {isPostgres ? t('pages.index.migrationDownloadPgDesc') : t('pages.index.migrationDownloadDesc')}
            </div>
          </div>
          <Button type="primary" onClick={exportMigration} icon={<DownloadOutlined />} />
        </div>

        <div className="backup-item">
          <div className="backup-meta">
            <div className="backup-title">{t('pages.index.importDatabase')}</div>
            <div className="backup-description">
              {isPostgres ? t('pages.index.importDatabasePgDesc') : t('pages.index.importDatabaseDesc')}
            </div>
          </div>
          <Button type="primary" onClick={importDb} icon={<UploadOutlined />} />
        </div>
      </div>
    </Modal>
  );
}
