// frontend/src/pages/index/CustomGeoSection.tsx
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Alert, Button, message, Modal, Space, Table, Tag, Tooltip } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import {
  PlusOutlined,
  ReloadOutlined,
  EditOutlined,
  DeleteOutlined,
  InboxOutlined,
} from '@ant-design/icons';

import { HttpUtil, ClipboardManager } from '@/utils';
import CustomGeoFormModal from './CustomGeoFormModal';
import type { CustomGeoRecord } from './CustomGeoFormModal';
import './CustomGeoSection.css';

interface CustomGeoSectionProps {
  active: boolean;
}

interface CustomGeoListRecord extends CustomGeoRecord {
  lastUpdatedAt?: number;
}

function formatTime(ts?: number): string {
  if (!ts) return '';
  const d = new Date(ts * 1000);
  if (isNaN(d.getTime())) return String(ts);
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

function relativeTime(ts?: number): string {
  if (!ts) return '';
  const diff = Math.floor(Date.now() / 1000) - ts;
  if (diff < 60) return 'just now';
  if (diff < 3600) return `${Math.floor(diff / 60)} min ago`;
  if (diff < 86400) return `${Math.floor(diff / 3600)} h ago`;
  if (diff < 2592000) return `${Math.floor(diff / 86400)} d ago`;
  return formatTime(ts);
}

function extDisplay(record: CustomGeoListRecord): string {
  const fn = record.type === 'geoip'
    ? `geoip_${record.alias}.dat`
    : `geosite_${record.alias}.dat`;
  return `ext:${fn}:tag`;
}

export default function CustomGeoSection({ active }: CustomGeoSectionProps) {
  const { t } = useTranslation();
  const [modal, modalContextHolder] = Modal.useModal();
  const [list, setList] = useState<CustomGeoListRecord[]>([]);
  const [loading, setLoading] = useState(false);
  const [updatingAll, setUpdatingAll] = useState(false);
  const [actionId, setActionId] = useState<number | null>(null);
  const [formOpen, setFormOpen] = useState(false);
  const [editingRecord, setEditingRecord] = useState<CustomGeoListRecord | null>(null);

  const loadList = useCallback(async () => {
    setLoading(true);
    try {
      const msg = await HttpUtil.get('/panel/api/custom-geo/list');
      if (msg?.success && Array.isArray(msg.obj)) setList(msg.obj);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (active) loadList();
  }, [active, loadList]);

  function openAdd() {
    setEditingRecord(null);
    setFormOpen(true);
  }

  function openEdit(record: CustomGeoListRecord) {
    setEditingRecord(record);
    setFormOpen(true);
  }

  async function copyExt(record: CustomGeoListRecord) {
    const text = extDisplay(record);
    const ok = await ClipboardManager.copyText(text);
    if (ok) message.success(`${t('copied')}: ${text}`);
  }

  function confirmDelete(record: CustomGeoListRecord) {
    modal.confirm({
      title: t('pages.index.customGeoDelete'),
      content: t('pages.index.customGeoDeleteConfirm'),
      okText: t('delete'),
      okType: 'danger',
      cancelText: t('cancel'),
      onOk: async () => {
        const msg = await HttpUtil.post(`/panel/api/custom-geo/delete/${record.id}`);
        if (msg?.success) await loadList();
      },
    });
  }

  async function downloadOne(id: number) {
    setActionId(id);
    try {
      const msg = await HttpUtil.post(`/panel/api/custom-geo/download/${id}`);
      if (msg?.success) await loadList();
    } finally {
      setActionId(null);
    }
  }

  async function updateAll() {
    setUpdatingAll(true);
    try {
      const msg = await HttpUtil.post('/panel/api/custom-geo/update-all');
      const ok = msg?.obj?.succeeded?.length || 0;
      const failed = msg?.obj?.failed?.length || 0;
      if (msg?.success || ok > 0) {
        await loadList();
        if (failed > 0) message.warning(`Updated ${ok}, failed ${failed}`);
      }
    } finally {
      setUpdatingAll(false);
    }
  }

  const columns = useMemo<ColumnsType<CustomGeoListRecord>>(
    () => [
      {
        title: t('pages.index.customGeoAlias'),
        key: 'alias',
        width: 200,
        render: (_v, record) => (
          <div className="custom-geo-alias-cell">
            <Tag color={record.type === 'geoip' ? 'cyan' : 'purple'} className="custom-geo-type-tag">
              {record.type}
            </Tag>
            <span className="custom-geo-alias">{record.alias}</span>
          </div>
        ),
      },
      {
        title: t('pages.index.customGeoUrl'),
        key: 'url',
        ellipsis: true,
        render: (_v, record) => (
          <Tooltip placement="topLeft" title={record.url}>
            <a
              href={record.url}
              target="_blank"
              rel="noopener noreferrer"
              className="custom-geo-url"
            >
              {record.url}
            </a>
          </Tooltip>
        ),
      },
      {
        title: t('pages.index.customGeoExtColumn'),
        key: 'extDat',
        width: 220,
        render: (_v, record) => (
          <Tooltip title={t('copy')}>
            <code
              className="custom-geo-ext-code custom-geo-copyable"
              onClick={() => copyExt(record)}
            >
              {extDisplay(record)}
            </code>
          </Tooltip>
        ),
      },
      {
        title: t('pages.index.customGeoLastUpdated'),
        key: 'lastUpdatedAt',
        width: 140,
        render: (_v, record) =>
          record.lastUpdatedAt ? (
            <Tooltip title={formatTime(record.lastUpdatedAt)}>
              <span>{relativeTime(record.lastUpdatedAt)}</span>
            </Tooltip>
          ) : (
            <span className="custom-geo-muted">—</span>
          ),
      },
      {
        title: t('pages.index.customGeoActions'),
        key: 'action',
        width: 120,
        render: (_v, record) => (
          <Space size="small">
            <Tooltip title={t('pages.index.customGeoEdit')}>
              <Button
                type="link"
                size="small"
                icon={<EditOutlined />}
                onClick={() => openEdit(record)}
              />
            </Tooltip>
            <Tooltip title={t('pages.index.customGeoDownload')}>
              <Button
                type="link"
                size="small"
                loading={actionId === record.id}
                icon={<ReloadOutlined />}
                onClick={() => downloadOne(record.id)}
              />
            </Tooltip>
            <Tooltip title={t('pages.index.customGeoDelete')}>
              <Button
                type="link"
                size="small"
                danger
                icon={<DeleteOutlined />}
                onClick={() => confirmDelete(record)}
              />
            </Tooltip>
          </Space>
        ),
      },
    ],
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [t, actionId],
  );

  return (
    <div className="custom-geo-section">
      {modalContextHolder}
      <Alert
        type="info"
        showIcon
        className="mb-10"
        message={t('pages.index.customGeoRoutingHint')}
      />

      <div className="toolbar">
        <Button type="primary" loading={loading} onClick={openAdd} icon={<PlusOutlined />}>
          {t('pages.index.customGeoAdd')}
        </Button>
        <Button
          loading={updatingAll}
          disabled={list.length === 0}
          onClick={updateAll}
          icon={<ReloadOutlined />}
        >
          {t('pages.index.geofilesUpdateAll')}
        </Button>
        {list.length > 0 && <span className="custom-geo-count">{list.length}</span>}
      </div>

      <Table
        columns={columns}
        dataSource={list}
        pagination={false}
        rowKey={(r) => r.id}
        loading={loading}
        size="small"
        scroll={{ x: 760 }}
        locale={{
          emptyText: (
            <div className="custom-geo-empty">
              <InboxOutlined className="custom-geo-empty-icon" />
              <div>{t('pages.index.customGeoEmpty')}</div>
            </div>
          ),
        }}
      />

      <CustomGeoFormModal
        open={formOpen}
        record={editingRecord}
        onClose={() => setFormOpen(false)}
        onSaved={loadList}
      />
    </div>
  );
}

// frontend/src/pages/index/CustomGeoSection.vue
<script setup>
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { Modal, message } from 'ant-design-vue';
import {
  PlusOutlined,
  ReloadOutlined,
  EditOutlined,
  DeleteOutlined,
  InboxOutlined,
} from '@ant-design/icons-vue';

import { HttpUtil, ClipboardManager } from '@/utils';
import CustomGeoFormModal from './CustomGeoFormModal.vue';

const { t } = useI18n();

const props = defineProps({
  // Re-fetch the list when the parent collapse expands this section.
  active: { type: Boolean, default: false },
});

const list = ref([]);
const loading = ref(false);
const updatingAll = ref(false);
const actionId = ref(null);

const formOpen = ref(false);
const editingRecord = ref(null);

// Computed so column titles re-render after a locale swap.
const columns = computed(() => [
  { title: t('pages.index.customGeoAlias'), key: 'alias', width: 200 },
  { title: t('pages.index.customGeoUrl'), key: 'url', ellipsis: true },
  { title: t('pages.index.customGeoExtColumn'), key: 'extDat', width: 220 },
  { title: t('pages.index.customGeoLastUpdated'), key: 'lastUpdatedAt', width: 140 },
  { title: t('pages.index.customGeoActions'), key: 'action', width: 120 },
]);

async function loadList() {
  loading.value = true;
  try {
    const msg = await HttpUtil.get('/panel/api/custom-geo/list');
    if (msg?.success && Array.isArray(msg.obj)) list.value = msg.obj;
  } finally {
    loading.value = false;
  }
}

function openAdd() {
  editingRecord.value = null;
  formOpen.value = true;
}

function openEdit(record) {
  editingRecord.value = record;
  formOpen.value = true;
}

function extDisplay(record) {
  const fn = record.type === 'geoip'
    ? `geoip_${record.alias}.dat`
    : `geosite_${record.alias}.dat`;
  return `ext:${fn}:tag`;
}

async function copyExt(record) {
  const text = extDisplay(record);
  const ok = await ClipboardManager.copyText(text);
  if (ok) message.success(`${t('copied')}: ${text}`);
}

function formatTime(ts) {
  if (!ts) return '';
  const d = new Date(ts * 1000);
  if (isNaN(d.getTime())) return String(ts);
  const pad = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

// Tiny inline relative-time formatter so we don't pull in moment.
function relativeTime(ts) {
  if (!ts) return '';
  const diff = Math.floor(Date.now() / 1000) - ts;
  if (diff < 60) return 'just now';
  if (diff < 3600) return `${Math.floor(diff / 60)} min ago`;
  if (diff < 86400) return `${Math.floor(diff / 3600)} h ago`;
  if (diff < 2592000) return `${Math.floor(diff / 86400)} d ago`;
  return formatTime(ts);
}

function confirmDelete(record) {
  Modal.confirm({
    title: t('pages.index.customGeoDelete'),
    content: t('pages.index.customGeoDeleteConfirm'),
    okText: t('delete'),
    okType: 'danger',
    cancelText: t('cancel'),
    onOk: async () => {
      const msg = await HttpUtil.post(`/panel/api/custom-geo/delete/${record.id}`);
      if (msg?.success) await loadList();
    },
  });
}

async function downloadOne(id) {
  actionId.value = id;
  try {
    const msg = await HttpUtil.post(`/panel/api/custom-geo/download/${id}`);
    if (msg?.success) await loadList();
  } finally {
    actionId.value = null;
  }
}

async function updateAll() {
  updatingAll.value = true;
  try {
    const msg = await HttpUtil.post('/panel/api/custom-geo/update-all');
    const ok = msg?.obj?.succeeded?.length || 0;
    const failed = msg?.obj?.failed?.length || 0;
    if (msg?.success || ok > 0) {
      await loadList();
      if (failed > 0) message.warning(`Updated ${ok}, failed ${failed}`);
    }
  } finally {
    updatingAll.value = false;
  }
}

// Lazy-load: only fetch when the parent collapse opens this panel.
watch(() => props.active, (next) => { if (next) loadList(); }, { immediate: true });
</script>

<template>
  <div class="custom-geo-section">
    <a-alert type="info" show-icon class="mb-10" :message="t('pages.index.customGeoRoutingHint')" />

    <div class="toolbar">
      <a-button type="primary" :loading="loading" @click="openAdd">
        <template #icon>
          <PlusOutlined />
        </template>
        {{ t('pages.index.customGeoAdd') }}
      </a-button>
      <a-button :loading="updatingAll" :disabled="!list.length" @click="updateAll">
        <template #icon>
          <ReloadOutlined />
        </template>
        {{ t('pages.index.geofilesUpdateAll') }}
      </a-button>
      <span v-if="list.length" class="custom-geo-count">{{ list.length }}</span>
    </div>

    <a-table :columns="columns" :data-source="list" :pagination="false" :row-key="(r) => r.id" :loading="loading"
      size="small" :scroll="{ x: 760 }">
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'alias'">
          <div class="custom-geo-alias-cell">
            <a-tag :color="record.type === 'geoip' ? 'cyan' : 'purple'" class="custom-geo-type-tag">
              {{ record.type }}
            </a-tag>
            <span class="custom-geo-alias">{{ record.alias }}</span>
          </div>
        </template>

        <template v-else-if="column.key === 'url'">
          <a-tooltip placement="topLeft" :title="record.url">
            <a :href="record.url" target="_blank" rel="noopener noreferrer" class="custom-geo-url">
              {{ record.url }}
            </a>
          </a-tooltip>
        </template>

        <template v-else-if="column.key === 'extDat'">
          <a-tooltip :title="t('copy')">
            <code class="custom-geo-ext-code custom-geo-copyable" @click="copyExt(record)">
              {{ extDisplay(record) }}
            </code>
          </a-tooltip>
        </template>

        <template v-else-if="column.key === 'lastUpdatedAt'">
          <a-tooltip v-if="record.lastUpdatedAt" :title="formatTime(record.lastUpdatedAt)">
            <span>{{ relativeTime(record.lastUpdatedAt) }}</span>
          </a-tooltip>
          <span v-else class="custom-geo-muted">—</span>
        </template>

        <template v-else-if="column.key === 'action'">
          <a-space size="small">
            <a-tooltip :title="t('pages.index.customGeoEdit')">
              <a-button type="link" size="small" @click="openEdit(record)">
                <template #icon>
                  <EditOutlined />
                </template>
              </a-button>
            </a-tooltip>
            <a-tooltip :title="t('pages.index.customGeoDownload')">
              <a-button type="link" size="small" :loading="actionId === record.id" @click="downloadOne(record.id)">
                <template #icon>
                  <ReloadOutlined />
                </template>
              </a-button>
            </a-tooltip>
            <a-tooltip :title="t('pages.index.customGeoDelete')">
              <a-button type="link" size="small" danger @click="confirmDelete(record)">
                <template #icon>
                  <DeleteOutlined />
                </template>
              </a-button>
            </a-tooltip>
          </a-space>
        </template>
      </template>

      <template #emptyText>
        <div class="custom-geo-empty">
          <InboxOutlined class="custom-geo-empty-icon" />
          <div>{{ t('pages.index.customGeoEmpty') }}</div>
        </div>
      </template>
    </a-table>

    <CustomGeoFormModal v-model:open="formOpen" :record="editingRecord" @saved="loadList" />
  </div>
</template>

<style scoped>
.mb-10 {
  margin-bottom: 10px;
}

.toolbar {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 8px;
  margin-bottom: 10px;
}

.custom-geo-count {
  margin-left: 4px;
  padding: 2px 8px;
  border-radius: 10px;
  background: rgba(0, 0, 0, 0.05);
  font-size: 12px;
  opacity: 0.75;
}

:global(body.dark) .custom-geo-count {
  background: rgba(255, 255, 255, 0.08);
}

.custom-geo-alias-cell {
  display: flex;
  align-items: center;
  gap: 6px;
}

.custom-geo-alias {
  font-weight: 500;
  word-break: break-all;
}

.custom-geo-type-tag {
  margin: 0;
}

.custom-geo-url {
  word-break: break-all;
}

.custom-geo-ext-code {
  cursor: pointer;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  font-size: 12px;
  padding: 2px 6px;
  border-radius: 4px;
  background: rgba(0, 0, 0, 0.05);
  user-select: all;
}

.custom-geo-copyable:hover {
  background: rgba(0, 0, 0, 0.1);
}

:global(body.dark) .custom-geo-ext-code {
  background: rgba(255, 255, 255, 0.08);
}

:global(body.dark) .custom-geo-copyable:hover {
  background: rgba(255, 255, 255, 0.14);
}

.custom-geo-muted {
  opacity: 0.5;
}

.custom-geo-empty {
  text-align: center;
  padding: 18px 0;
  opacity: 0.6;
}

.custom-geo-empty-icon {
  font-size: 32px;
  margin-bottom: 6px;
  display: block;
}
</style>
