// frontend/src/pages/index/CustomGeoFormModal.vue
<script setup>
import { reactive, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { message } from 'ant-design-vue';
import { HttpUtil } from '@/utils';

const { t } = useI18n();

const props = defineProps({
  open: { type: Boolean, default: false },
  // Populate with the record when editing; null/undefined when adding.
  record: { type: Object, default: null },
});

const emit = defineEmits(['update:open', 'saved']);

const form = reactive({ type: 'geosite', alias: '', url: '' });
const saving = ref(false);

const editing = ref(false);
const editId = ref(null);

watch(() => props.open, (next) => {
  if (!next) return;
  if (props.record) {
    editing.value = true;
    editId.value = props.record.id;
    form.type = props.record.type;
    form.alias = props.record.alias;
    form.url = props.record.url;
  } else {
    editing.value = false;
    editId.value = null;
    form.type = 'geosite';
    form.alias = '';
    form.url = '';
  }
});

function close() {
  emit('update:open', false);
}

function validate() {
  // Backend expects a filesystem-safe alias; legacy enforces the same regex.
  if (!/^[a-z0-9_-]+$/.test(form.alias || '')) {
    message.error(t('pages.index.customGeoValidationAlias'));
    return false;
  }
  const u = (form.url || '').trim();
  if (!/^https?:\/\//i.test(u)) {
    message.error(t('pages.index.customGeoValidationUrl'));
    return false;
  }
  try {
    const parsed = new URL(u);
    if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
      message.error(t('pages.index.customGeoValidationUrl'));
      return false;
    }
  } catch (_e) {
    message.error(t('pages.index.customGeoValidationUrl'));
    return false;
  }
  return true;
}

async function submit() {
  if (!validate()) return;
  saving.value = true;
  try {
    const url = editing.value
      ? `/panel/api/custom-geo/update/${editId.value}`
      : '/panel/api/custom-geo/add';
    const msg = await HttpUtil.post(url, form);
    if (msg?.success) {
      emit('saved');
      close();
    }
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <a-modal :open="open" :title="editing ? t('pages.index.customGeoModalEdit') : t('pages.index.customGeoModalAdd')"
    :confirm-loading="saving" :ok-text="t('pages.index.customGeoModalSave')" :cancel-text="t('close')" @ok="submit"
    @cancel="close">
    <a-form layout="vertical">
      <a-form-item :label="t('pages.index.customGeoType')">
        <a-select v-model:value="form.type" :disabled="editing">
          <a-select-option value="geosite">geosite</a-select-option>
          <a-select-option value="geoip">geoip</a-select-option>
        </a-select>
      </a-form-item>
      <a-form-item :label="t('pages.index.customGeoAlias')">
        <a-input v-model:value="form.alias" :disabled="editing"
          :placeholder="t('pages.index.customGeoAliasPlaceholder')" />
      </a-form-item>
      <a-form-item :label="t('pages.index.customGeoUrl')">
        <a-input v-model:value="form.url" placeholder="https://" />
      </a-form-item>
    </a-form>
  </a-modal>
</template>

// frontend/src/pages/index/CustomGeoFormModal.tsx
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Form, Input, message, Modal, Select } from 'antd';

import { HttpUtil } from '@/utils';

export interface CustomGeoRecord {
  id: number;
  type: 'geosite' | 'geoip';
  alias: string;
  url: string;
}

interface CustomGeoFormModalProps {
  open: boolean;
  record: CustomGeoRecord | null;
  onClose: () => void;
  onSaved: () => void;
}

export default function CustomGeoFormModal({
  open,
  record,
  onClose,
  onSaved,
}: CustomGeoFormModalProps) {
  const { t } = useTranslation();
  const [type, setType] = useState<'geosite' | 'geoip'>('geosite');
  const [alias, setAlias] = useState('');
  const [url, setUrl] = useState('');
  const [saving, setSaving] = useState(false);

  const editing = record != null;

  useEffect(() => {
    if (!open) return;
    if (record) {
      setType(record.type);
      setAlias(record.alias);
      setUrl(record.url);
    } else {
      setType('geosite');
      setAlias('');
      setUrl('');
    }
  }, [open, record]);

  function validate(): boolean {
    if (!/^[a-z0-9_-]+$/.test(alias || '')) {
      message.error(t('pages.index.customGeoValidationAlias'));
      return false;
    }
    const u = (url || '').trim();
    if (!/^https?:\/\//i.test(u)) {
      message.error(t('pages.index.customGeoValidationUrl'));
      return false;
    }
    try {
      const parsed = new URL(u);
      if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
        message.error(t('pages.index.customGeoValidationUrl'));
        return false;
      }
    } catch {
      message.error(t('pages.index.customGeoValidationUrl'));
      return false;
    }
    return true;
  }

  async function submit() {
    if (!validate()) return;
    setSaving(true);
    try {
      const apiUrl = editing
        ? `/panel/api/custom-geo/update/${record!.id}`
        : '/panel/api/custom-geo/add';
      const msg = await HttpUtil.post(apiUrl, { type, alias, url });
      if (msg?.success) {
        onSaved();
        onClose();
      }
    } finally {
      setSaving(false);
    }
  }

  return (
    <Modal
      open={open}
      title={editing ? t('pages.index.customGeoModalEdit') : t('pages.index.customGeoModalAdd')}
      confirmLoading={saving}
      okText={t('pages.index.customGeoModalSave')}
      cancelText={t('close')}
      onOk={submit}
      onCancel={onClose}
    >
      <Form layout="vertical">
        <Form.Item label={t('pages.index.customGeoType')}>
          <Select
            value={type}
            disabled={editing}
            onChange={(v) => setType(v)}
            options={[
              { value: 'geosite', label: 'geosite' },
              { value: 'geoip', label: 'geoip' },
            ]}
          />
        </Form.Item>
        <Form.Item label={t('pages.index.customGeoAlias')}>
          <Input
            value={alias}
            disabled={editing}
            placeholder={t('pages.index.customGeoAliasPlaceholder')}
            onChange={(e) => setAlias(e.target.value)}
          />
        </Form.Item>
        <Form.Item label={t('pages.index.customGeoUrl')}>
          <Input
            value={url}
            placeholder="https://"
            onChange={(e) => setUrl(e.target.value)}
          />
        </Form.Item>
      </Form>
    </Modal>
  );
}
