// frontend/src/pages/index/StatusCard.vue
<script setup>
import { useI18n } from 'vue-i18n';
import { AreaChartOutlined, HistoryOutlined } from '@ant-design/icons-vue';

import { CPUFormatter, SizeFormatter } from '@/utils';

const { t } = useI18n();

defineProps({
  status: { type: Object, required: true },
  isMobile: { type: Boolean, default: false },
});

defineEmits(['open-cpu-history']);
</script>

<template>
  <a-card hoverable>
    <a-row :gutter="[0, isMobile ? 16 : 0]">
      <!-- CPU + Memory -->
      <a-col :sm="24" :md="12">
        <a-row>
          <a-col :span="12" class="text-center">
            <a-progress
              type="dashboard"
              status="normal"
              :stroke-color="status.cpu.color"
              :percent="status.cpu.percent"
            />
            <div>
              <b>{{ t('pages.index.cpu') }}:</b> {{ CPUFormatter.cpuCoreFormat(status.cpuCores) }}
              <a-tooltip>
                <template #title>
                  <div><b>{{ t('pages.index.logicalProcessors') }}:</b> {{ status.logicalPro }}</div>
                  <div><b>{{ t('pages.index.frequency') }}:</b> {{ CPUFormatter.cpuSpeedFormat(status.cpuSpeedMhz) }}</div>
                </template>
                <AreaChartOutlined />
              </a-tooltip>
              <a-tooltip>
                <template #title>{{ t('pages.index.cpu') }}</template>
                <a-button size="small" shape="circle" class="ml-8" @click="$emit('open-cpu-history')">
                  <template #icon><HistoryOutlined /></template>
                </a-button>
              </a-tooltip>
            </div>
          </a-col>

          <a-col :span="12" class="text-center">
            <a-progress
              type="dashboard"
              status="normal"
              :stroke-color="status.mem.color"
              :percent="status.mem.percent"
            />
            <div>
              <b>{{ t('pages.index.memory') }}:</b> {{ SizeFormatter.sizeFormat(status.mem.current) }} /
              {{ SizeFormatter.sizeFormat(status.mem.total) }}
            </div>
          </a-col>
        </a-row>
      </a-col>

      <!-- Swap + Disk -->
      <a-col :sm="24" :md="12">
        <a-row>
          <a-col :span="12" class="text-center">
            <a-progress
              type="dashboard"
              status="normal"
              :stroke-color="status.swap.color"
              :percent="status.swap.percent"
            />
            <div>
              <b>{{ t('pages.index.swap') }}:</b> {{ SizeFormatter.sizeFormat(status.swap.current) }} /
              {{ SizeFormatter.sizeFormat(status.swap.total) }}
            </div>
          </a-col>

          <a-col :span="12" class="text-center">
            <a-progress
              type="dashboard"
              status="normal"
              :stroke-color="status.disk.color"
              :percent="status.disk.percent"
            />
            <div>
              <b>{{ t('pages.index.storage') }}:</b> {{ SizeFormatter.sizeFormat(status.disk.current) }} /
              {{ SizeFormatter.sizeFormat(status.disk.total) }}
            </div>
          </a-col>
        </a-row>
      </a-col>
    </a-row>
  </a-card>
</template>

<style scoped>
.text-center {
  text-align: center;
}
.ml-8 {
  margin-left: 8px;
}
</style>

// frontend/src/pages/index/StatusCard.tsx
import { useTranslation } from 'react-i18next';
import { Card, Col, Progress, Row, Tooltip } from 'antd';
import { AreaChartOutlined } from '@ant-design/icons';

import { CPUFormatter, SizeFormatter } from '@/utils';
import type { Status } from '@/models/status';
import './StatusCard.css';

interface StatusCardProps {
  status: Status;
  isMobile: boolean;
}

const TRAIL_COLOR = 'rgba(128, 128, 128, 0.25)';

export default function StatusCard({ status, isMobile }: StatusCardProps) {
  const { t } = useTranslation();
  const gaugeSize = isMobile ? 60 : 70;

  return (
    <Card hoverable className="status-card">
      <Row gutter={[0, isMobile ? 16 : 0]}>
        <Col xs={24} md={12}>
          <Row>
            <Col span={12} className="text-center">
              <Progress
                type="dashboard"
                status="normal"
                strokeColor={status.cpu.color}
                trailColor={TRAIL_COLOR}
                percent={status.cpu.percent}
                size={gaugeSize}
              />
              <div>
                <b>{t('pages.index.cpu')}:</b> {CPUFormatter.cpuCoreFormat(status.cpuCores)}
                <Tooltip
                  title={
                    <>
                      <div>
                        <b>{t('pages.index.logicalProcessors')}:</b> {status.logicalPro}
                      </div>
                      <div>
                        <b>{t('pages.index.frequency')}:</b>{' '}
                        {CPUFormatter.cpuSpeedFormat(status.cpuSpeedMhz)}
                      </div>
                    </>
                  }
                >
                  <AreaChartOutlined />
                </Tooltip>
              </div>
            </Col>

            <Col span={12} className="text-center">
              <Progress
                type="dashboard"
                status="normal"
                strokeColor={status.mem.color}
                trailColor={TRAIL_COLOR}
                percent={status.mem.percent}
                size={gaugeSize}
              />
              <div>
                <b>{t('pages.index.memory')}:</b> {SizeFormatter.sizeFormat(status.mem.current)} /{' '}
                {SizeFormatter.sizeFormat(status.mem.total)}
              </div>
            </Col>
          </Row>
        </Col>

        <Col xs={24} md={12}>
          <Row>
            <Col span={12} className="text-center">
              <Progress
                type="dashboard"
                status="normal"
                strokeColor={status.swap.color}
                trailColor={TRAIL_COLOR}
                percent={status.swap.percent}
                size={gaugeSize}
              />
              <div>
                <b>{t('pages.index.swap')}:</b> {SizeFormatter.sizeFormat(status.swap.current)} /{' '}
                {SizeFormatter.sizeFormat(status.swap.total)}
              </div>
            </Col>

            <Col span={12} className="text-center">
              <Progress
                type="dashboard"
                status="normal"
                strokeColor={status.disk.color}
                trailColor={TRAIL_COLOR}
                percent={status.disk.percent}
                size={gaugeSize}
              />
              <div>
                <b>{t('pages.index.storage')}:</b> {SizeFormatter.sizeFormat(status.disk.current)} /{' '}
                {SizeFormatter.sizeFormat(status.disk.total)}
              </div>
            </Col>
          </Row>
        </Col>
      </Row>
    </Card>
  );
}
