// frontend/src/pages/index/VersionModal.tsx
import { useCallback, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Alert, Button, Collapse, List, Modal, Radio, Spin, Tag, Tooltip } from 'antd';
import { ReloadOutlined } from '@ant-design/icons';

import { HttpUtil } from '@/utils';
import type { Status } from '@/models/status';
import CustomGeoSection from './CustomGeoSection';
import './VersionModal.css';

interface BusyEvent {
  busy: boolean;
  tip?: string;
}

interface VersionModalProps {
  open: boolean;
  status: Status;
  onClose: () => void;
  onBusy: (e: BusyEvent) => void;
}

const GEOFILES = [
  'geosite.dat',
  'geoip.dat',
  'geosite_IR.dat',
  'geoip_IR.dat',
  'geosite_RU.dat',
  'geoip_RU.dat',
];

export default function VersionModal({ open, status, onClose, onBusy }: VersionModalProps) {
  const { t } = useTranslation();
  const [modal, modalContextHolder] = Modal.useModal();
  const [activeKey, setActiveKey] = useState<string | string[]>('1');
  const [versions, setVersions] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);

  const fetchVersions = useCallback(async () => {
    setLoading(true);
    try {
      const msg = await HttpUtil.get('/panel/api/server/getXrayVersion');
      if (msg?.success) setVersions(msg.obj || []);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (open) fetchVersions();
  }, [open, fetchVersions]);

  function switchXrayVersion(version: string) {
    modal.confirm({
      title: t('pages.index.xraySwitchVersionDialog'),
      content: t('pages.index.xraySwitchVersionDialogDesc').replace('#version#', version),
      okText: t('confirm'),
      cancelText: t('cancel'),
      onOk: async () => {
        onClose();
        onBusy({ busy: true, tip: t('pages.index.dontRefresh') });
        try {
          await HttpUtil.post(`/panel/api/server/installXray/${version}`);
        } finally {
          onBusy({ busy: false });
        }
      },
    });
  }

  function updateGeofile(fileName: string) {
    const isSingle = !!fileName;
    modal.confirm({
      title: t('pages.index.geofileUpdateDialog'),
      content: isSingle
        ? t('pages.index.geofileUpdateDialogDesc').replace('#filename#', fileName)
        : t('pages.index.geofilesUpdateDialogDesc'),
      okText: t('confirm'),
      cancelText: t('cancel'),
      onOk: async () => {
        onClose();
        onBusy({ busy: true, tip: t('pages.index.dontRefresh') });
        const url = isSingle
          ? `/panel/api/server/updateGeofile/${fileName}`
          : '/panel/api/server/updateGeofile';
        try {
          await HttpUtil.post(url);
        } finally {
          onBusy({ busy: false });
        }
      },
    });
  }

  const activeKeyStr = Array.isArray(activeKey) ? activeKey[0] : activeKey;

  return (
    <Modal
      open={open}
      title={t('pages.index.xrayUpdates')}
      closable
      footer={null}
      onCancel={onClose}
    >
      {modalContextHolder}
      <Spin spinning={loading}>
        <Collapse
          accordion
          activeKey={activeKey}
          onChange={setActiveKey}
          items={[
            {
              key: '1',
              label: 'Xray',
              children: (
                <>
                  <Alert
                    type="warning"
                    className="mb-12"
                    message={t('pages.index.xraySwitchClickDesk')}
                    showIcon
                  />
                  <List bordered className="version-list">
                    {versions.map((version, index) => (
                      <List.Item key={version} className="version-list-item">
                        <Tag color={index % 2 === 0 ? 'purple' : 'green'}>{version}</Tag>
                        <Radio
                          checked={version === `v${status?.xray?.version}`}
                          onClick={() => switchXrayVersion(version)}
                        />
                      </List.Item>
                    ))}
                  </List>
                </>
              ),
            },
            {
              key: '2',
              label: 'Geofiles',
              children: (
                <>
                  <List bordered className="version-list">
                    {GEOFILES.map((file, index) => (
                      <List.Item key={file} className="version-list-item">
                        <Tag color={index % 2 === 0 ? 'purple' : 'green'}>{file}</Tag>
                        <Tooltip title={t('update')}>
                          <ReloadOutlined
                            className="reload-icon"
                            onClick={() => updateGeofile(file)}
                          />
                        </Tooltip>
                      </List.Item>
                    ))}
                  </List>
                  <div className="actions-row">
                    <Button onClick={() => updateGeofile('')}>
                      {t('pages.index.geofilesUpdateAll')}
                    </Button>
                  </div>
                </>
              ),
            },
            {
              key: '3',
              label: t('pages.index.customGeoTitle'),
              children: <CustomGeoSection active={activeKeyStr === '3'} />,
            },
          ]}
        />
      </Spin>
    </Modal>
  );
}

// frontend/src/pages/index/VersionModal.vue
<script setup>
import { ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { Modal } from 'ant-design-vue';
import { ReloadOutlined } from '@ant-design/icons-vue';
import { HttpUtil } from '@/utils';
import CustomGeoSection from './CustomGeoSection.vue';

const { t } = useI18n();

const props = defineProps({
  open: { type: Boolean, default: false },
  status: { type: Object, required: true },
});

const emit = defineEmits(['update:open', 'busy']);

const activeKey = ref('1');
const versions = ref([]);
const loading = ref(false);

// Geofiles list is hardcoded in the legacy panel — same set of files
// served from /panel/api/server/updateGeofile/{name}.
const GEOFILES = ['geosite.dat', 'geoip.dat', 'geosite_IR.dat', 'geoip_IR.dat', 'geosite_RU.dat', 'geoip_RU.dat'];

async function fetchVersions() {
  loading.value = true;
  try {
    const msg = await HttpUtil.get('/panel/api/server/getXrayVersion');
    if (msg?.success) versions.value = msg.obj || [];
  } finally {
    loading.value = false;
  }
}

function close() {
  emit('update:open', false);
}

function switchXrayVersion(version) {
  Modal.confirm({
    title: t('pages.index.xraySwitchVersionDialog'),
    content: t('pages.index.xraySwitchVersionDialogDesc').replace('#version#', version),
    okText: t('confirm'),
    cancelText: t('cancel'),
    onOk: async () => {
      close();
      emit('busy', { busy: true, tip: t('pages.index.dontRefresh') });
      try {
        await HttpUtil.post(`/panel/api/server/installXray/${version}`);
      } finally {
        emit('busy', { busy: false });
      }
    },
  });
}

function updateGeofile(fileName) {
  const isSingle = !!fileName;
  Modal.confirm({
    title: t('pages.index.geofileUpdateDialog'),
    content: isSingle
      ? t('pages.index.geofileUpdateDialogDesc').replace('#filename#', fileName)
      : t('pages.index.geofilesUpdateDialogDesc'),
    okText: t('confirm'),
    cancelText: t('cancel'),
    onOk: async () => {
      close();
      emit('busy', { busy: true, tip: t('pages.index.dontRefresh') });
      const url = isSingle
        ? `/panel/api/server/updateGeofile/${fileName}`
        : '/panel/api/server/updateGeofile';
      try {
        await HttpUtil.post(url);
      } finally {
        emit('busy', { busy: false });
      }
    },
  });
}

watch(() => props.open, (next) => { if (next) fetchVersions(); });
</script>

<template>
  <a-modal :open="open" :title="t('pages.index.xrayUpdates')" :closable="true" :footer="null" @cancel="close">
    <a-spin :spinning="loading">
      <a-collapse v-model:active-key="activeKey" accordion>
        <a-collapse-panel key="1" header="Xray">
          <a-alert
            type="warning"
            class="mb-12"
            :message="t('pages.index.xraySwitchClickDesk')"
            show-icon
          />
          <a-list bordered class="version-list">
            <a-list-item v-for="(version, index) in versions" :key="version" class="version-list-item">
              <a-tag :color="index % 2 === 0 ? 'purple' : 'green'">{{ version }}</a-tag>
              <a-radio
                :checked="version === `v${status?.xray?.version}`"
                @click="switchXrayVersion(version)"
              />
            </a-list-item>
          </a-list>
        </a-collapse-panel>

        <a-collapse-panel key="2" header="Geofiles">
          <a-list bordered class="version-list">
            <a-list-item v-for="(file, index) in GEOFILES" :key="file" class="version-list-item">
              <a-tag :color="index % 2 === 0 ? 'purple' : 'green'">{{ file }}</a-tag>
              <a-tooltip :title="t('update')">
                <ReloadOutlined class="reload-icon" @click="updateGeofile(file)" />
              </a-tooltip>
            </a-list-item>
          </a-list>
          <div class="actions-row">
            <a-button @click="updateGeofile('')">{{ t('pages.index.geofilesUpdateAll') }}</a-button>
          </div>
        </a-collapse-panel>

        <a-collapse-panel key="3" :header="t('pages.index.customGeoTitle')">
          <CustomGeoSection :active="activeKey === '3'" />
        </a-collapse-panel>
      </a-collapse>
    </a-spin>
  </a-modal>
</template>

<style scoped>
.mb-12 { margin-bottom: 12px; }
.version-list { width: 100%; }
.version-list-item { display: flex; justify-content: space-between; align-items: center; }

.reload-icon {
  cursor: pointer;
  font-size: 16px;
  margin-right: 8px;
}

.actions-row {
  display: flex;
  justify-content: flex-end;
  margin-top: 12px;
}
</style>
